### ISSUE TITLE
[Safe Creation] Connect wallet step

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1003]
## What is the feature about

Implements the connect wallet + mobile QR as first step in safe creation.

## The list of requirements

- Should be the first step in safe creation
- Should display a button to connect with the wallet
- Should display a QR code for mobile pairing
- Should disable the Continue button until a wallet is connect
- If the wallet is disconnected at any step of the safe creation it should either jump back to this step or disable the continue button

## Designs/sketches
<img width="364" alt="Screenshot 2022-10-28 at 15 54 45" src="https://user-images.githubusercontent.com/5880855/198626064-b03aac80-1716-44e1-ab8c-f41a070fdd37.png">

## Links

Figma: https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=51%3A5661

**Comment by DiogoSoaress** [comment]
Also to complete this point
> If the wallet is disconnected at any step of the safe creation it should either jump back to this step or disable the continue button

we previously discussed to disable the "continue" button if the wallet is in the wrong chain
