### ISSUE TITLE
[Safe Apps Analysis] 01. Open count vs transactions made inside the app (Frontend)

### ISSUE THREAD

**Issue by yagopv** [safe-global/web-core#1009]
# What it solves

We are creating a report showing the number of openings per app and the number of transactions confirmed or rejected

# Links

[Notion. Open count vs transactions made inside the app](https://www.notion.so/gnosis-safe/Open-count-vs-transactions-made-inside-the-app-482b367e1dcf41898c15598a670f7dee)

# Report location

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/1576776/201660312-f36641f9-0cf6-400f-8ff4-072d9c44e336.png">

**Comment by yagopv** [comment]
Aha, i see. Not sure how to get that as i cannot see the way to create "computed" columns in the exploration. I have to investigate a little

**Comment by clemoon** [comment]
@yagopv I don't see the rate being displayed in the table, could you figure out a way to do this?

**Comment by yagopv** [comment]
Nope yet. GA4 does not have the concept of calculated fields as in the 'legacy' Google Universal Analytics (https://support.google.com/analytics/answer/6121409?hl=en#zippy=%2Cin-this-article)

I'm looking to other project now to generate the reports => https://datastudio.google.com and probably we can do this kind of things there but could not figure out yet

**Comment by clemoon** [comment]
The number of Transaction Confirmed on the table is sometimes greater than the number of open count (e.g Aave 3). I think the calculation should be using the backend transaction count per app to be accurate

**Comment by yagopv** [comment]
Yep, the backend analytic are going to be separated from this. Perhaps we can merge the data in some way.

I'm checking the app and sometimes i can see we are sending duplicated Open events to GA so we have some issue there. I will check this and the moment where we send the Confirmed or Rejected events to fine tune

**Comment by clemoon** [comment]
Did we find any way to fine tune here? Unless we find a way to do so, I suggest we drop the "open app" count because it doesn't match with the transactions confirmed and rejected. We can't make sense of transactions confirmed and rejected being greater than the app openings. This would only be valuable to know *per session*
