### ISSUE TITLE
Some icons are too small

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1025]
Some icons need `fontSize="small"` removed.

From @usame-algan's comment:

There are a few more icons that appear smaller than they used to be:

Address Book:
<img width="223" alt="Screenshot 2022-11-01 at 16 14 34" src="https://user-images.githubusercontent.com/5880855/199268093-2c0b9c88-fb65-4779-b703-466ddf0864fa.png">
<img width="668" alt="Screenshot 2022-11-01 at 16 14 54" src="https://user-images.githubusercontent.com/5880855/199268182-2332b91d-0777-44e7-b75a-24d5bd54b366.png">

Owner Settings:
<img width="806" alt="Screenshot 2022-11-01 at 16 15 14" src="https://user-images.githubusercontent.com/5880855/199268232-533a8b71-0899-47e5-8046-313a6362dc9e.png">

Assets:
<img width="230" alt="Screenshot 2022-11-01 at 16 20 29" src="https://user-images.githubusercontent.com/5880855/199269455-3a848668-8c00-4d48-abd5-128bdbcf13b5.png">

There is some inconsistency with the icon viewboxes (some have a larger viewbox but overall smaller icon). Could this be related to how they are exported from [Figma](https://www.figma.com/file/HKW5iarMST9rL7Kxkf59qY/MUI-for-Figma?node-id=10964%3A70434)?

**Comment by iamacook** [comment]
It seems this requires more than removing the prop. Some of the icon groups have varying padding sizes. We need to sync with design about this. cc @liliiaorlenko

**Comment by liliiaorlenko** [comment]
> It seems this requires more than removing the prop. Some of the icon groups have varying padding sizes. We need to sync with design about this. cc @liliiaorlenko

which icons should I fix exactly or all of them? maybe we can have short call

**Comment by iamacook** [comment]
> which icons should I fix exactly or all of them? maybe we can have short call

It's not a problem anymore. I managed to tackle it.
