### ISSUE TITLE
Update mobile address book layout

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1028]
## What is the feature about

The current mobile address book layout does not match that of [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=1004%3A49906). We should adjust the layout to match that.

## Designs/sketches
<img width="394" alt="Screenshot 2022-11-08 at 17 57 26" src="https://user-images.githubusercontent.com/5880855/200627836-37eed87b-9314-4a47-acef-b280e45a704e.png">

**Comment by usame-algan** [comment]
cc @liliiaorlenko

**Comment by liliiaorlenko** [comment]
I fixed the design, we had a changes a month ago, but mobile wasnt updated, but the current look is alright for now

**Comment by liliiaorlenko** [comment]
Small extra fixes for web 
<img width="1477" alt="Screenshot 2023-01-03 at 14 02 07" src="https://user-images.githubusercontent.com/94694401/210363247-7b6f5d70-9111-4076-9026-a169a67f9c81.png">

**Comment by liliya-soroka** [comment]
Verified
