### ISSUE TITLE
Test the new prod site

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1039]
We need to do a round of QA on the new prod.
Specific attention to analytics and data migration

**Comment by francovenica** [comment]
That last ticket 1069 is the only blocker. I'll check with the other QA's tomorrow for a quick final look and we can create the RC

**Comment by francovenica** [comment]
The site is live. 

The only major issue we had was some problems regarding the migration, that made a form crash the site. A fix was implemented to validate addresses and also to not migrate Rinkeby data.
