### ISSUE TITLE
Issues with gas estimation on Volta chain

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#1044]
## Bug description
I am getting an error in the tx pop up when creating a batched transaction from the tx-builder safe app in volta chain.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Volta

## Steps to reproduce
 1. Go to the tx-builder safe app and create a transfer tx. See that no warning is shown.
 2. Go to the tx-builder safe app and create a batch of 2 transfer txs. See that a gas estimation error is shown.
 (this process can be seen on the video below)

## Expected result
No gas estimation issues on UI

## Obtained result

https://user-images.githubusercontent.com/92332710/199692504-5b962021-c06e-4f52-8b5f-38f796d81c07.mp4

**Comment by JagoFigueroa** [comment]
Lowering the priority of this as it is a testnet plus removing the [soft release] tag as it is also happening on the old web interface ;)

**Comment by iamacook** [comment]
`estimateGas` seems to be throwing:

![image](https://user-images.githubusercontent.com/20442784/199726718-2540a209-6e49-4da4-8fdc-e582a9023e3f.png)

![image](https://user-images.githubusercontent.com/20442784/199726735-eef2640f-a42e-4edf-b938-6d1c8eab3f5f.png)

Volta should be Berlin compatable but I did check removing `type` to no avail. As it's a testnet, I will move this to the backlog for now.
