### ISSUE TITLE
[Soft release] - Sidebar is slightly narrower than before

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1048]
## Bug description
The sidebar where the safes owned in that particular network is narrower than in https://web-core.pages.dev/. 
Is already pretty narrow so being even more it hides the last part of the addresses of the safes

Env:
https://app.safe.global/welcome

https://github.com/safe-global/web-core/issues/1039

## Screenshots
![sidebar width](https://user-images.githubusercontent.com/4503659/199728052-4537d791-cff3-42a5-ac9d-1028d961eb48.gif)

**Comment by francovenica** [comment]
Question: Shouldn't the "Add Safe" button should also be available in this view of the safes in the sidebar?

**Comment by katspaugh** [comment]
There's no space for it there. I would close this, as there's a ticket to revamp the whole "owned safes on the welcome page" concept.
