### ISSUE TITLE
[Soft release] Trying to execute a tx with a non-owner shows warning message

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1057]
## Bug description
When a tx is fully sing a non-owner can execute it. When trying to execute the tx it shows the warning message "the tx might fails" shows even that the values estimated (gas limit, fee, etc) is exactly the same as with an owner of the safe

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli
 - Env: https://app.safe.global/
 - Test ticket: #1039  
## Steps to reproduce
 1. Go to a safe, create any tx and fully sign it, do not execute it
 2. Change the address connected to a non-owner and try to execute

## Expected result
Review step shows normal

## Obtained result
The review step shows the warning message.
The values estimated for the non-owner are the same as the one for the owner

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/199882241-bdbbcc5d-fc83-470f-a0c8-374be9f77368.png)

**Comment by katspaugh** [comment]
Might be an error with signature generation. The last time I fixed this, it was creating an "owner" signature for non-owners.

**Comment by francovenica** [comment]
LGTM. The warning doesn't show anymore for non-owners when executing the tx
