### ISSUE TITLE
[Soft release] Send funds form crashes the page

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1069]
## Bug description
Just trying to open the send funds form crashes the page
Tryied with a ledget and MM, in ethereum and goerli, so the device and network seems to be irrelevant

## Environment
 - Browser: Chrome
 - Wallet: Any
 - Chain: Any
 - Env: https://app.safe.global/

Main ticket: #1039 

## Steps to reproduce
 1. Go to a safe you own
 2. Click New transactions > Send funds

## Screenshots
![crash](https://user-images.githubusercontent.com/4503659/200213056-b9acdf1a-897b-4a1f-b140-58b7cbe14845.gif)

**Comment by katspaugh** [comment]
Can't reproduce. Tried with Ledger on localhost and prod, on both 1.1.1 and 1.3.0 Safes.

**Comment by katspaugh** [comment]
It was likely due to a bogus entry in the address book where the address is undefined.
