### ISSUE TITLE
[Create safe] Switching chains while a safe is being created displaying information about that safe on other chains

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#1095]
## Bug description
A bit tricky. While a safe is being created, if we switch to another chain, information will be displayed as if we were creating a safe on the new chain that it was selected when that is not true & will block users from creating new safes on other chains while the current one is being processed.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Any

## Steps to reproduce
 1. Create a safe with a gas limit low enough so that it wont finish creating
 2. Switch to another chain

In my case I was able to reproduce this on Optimism while the chain was being slow and wanted to continue creating safes on other chains on the meanwhile but I couldn't because of this inheritance.

## Expected result
I am able to create a new safe in other chains while the one from Optimism (taking my case as reference) is stuck on creation.

## Obtained result

https://user-images.githubusercontent.com/92332710/200525273-01d6724e-5ee3-4218-a6ca-7e55a71bd568.mp4

**Comment by iamacook** [comment]
I will close this as we have almost finished [our implementation of the redesigned Safe creation](https://github.com/safe-global/web-core/issues/864).
