### ISSUE TITLE
Option for importing and exporting all user data

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1097]
## What is the feature about

User data like address book entries, added safes, selected currency etc. is stored locally. Currently, it is only possible to export address book entries but not all user data.

## The list of requirements

- Create a new "Data" section on the settings page
- Add an Import and Export button
- Add an Export button on the old app (gnosis-safe.io)
- The import should support exported data from gnosis-safe.io
- The import from gnosis-safe.io should merge the current local storage if possible
- The import from app.safe.global should override the local storage

## Mockups

<img width="874" alt="Screenshot 2022-11-08 at 10 57 19" src="https://user-images.githubusercontent.com/5880855/200540858-f3e80932-958b-4e82-bfcd-1d93a055aa08.png">
<img width="644" alt="Screenshot 2022-11-08 at 10 55 18" src="https://user-images.githubusercontent.com/5880855/200540893-dec89b00-7063-42ba-9fa0-e0315b0b0539.png">

##Checklist
https://www.notion.so/gnosis-safe/Data-Migration-safe-react-to-web-core-c14bb73c6f4a4fd7a529f2a892b871c4

**Comment by katspaugh** [comment]
I would make it its own settings page.

Also, this feature could be used to move data between browsers/devices in future, so let's not mention "gnosis-safe.io" specifically.
