### ISSUE TITLE
[Goerli & L2s] Keystone not working

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1110]
> Can not create a new safe wallet on Goerli testnet.  The error message shows that the chain ID does not match the chain ID of common. Please see the first picture for more details below.

> Transaction sent failed on Goerli testnet. The error message shows that the method eth_signTypeData_v4 does not exist/is not available.  Please see the second screenshot for more details below.

> We did not test all the chains. And from what we’ve got now, it only works on the Ethereum mainnet but not on any other chains we tested.

**Comment by iamacook** [comment]
> The error message shows that the chain ID does not match the chain ID of common.

This was the same error shown with other hardware wallets. A fix is open for it [here](https://github.com/safe-global/web-core/pull/1085).

**Comment by iamacook** [comment]
@katspaugh, who reported this?

> We did not test all the chains. And from what we’ve got now, it only works on the Ethereum mainnet but not on any other chains we tested.

The initially chosen network in the account scanner modal needs to be also set to the desired network:

![image](https://user-images.githubusercontent.com/20442784/200791190-d2129c0e-55c3-427c-8b14-e5ccfec04ae1.png)

**Comment by katspaugh** [comment]
Fixed in #1085.

**Comment by francovenica** [comment]
I don't have a keystone device.
@liliya-soroka can you check this one?

**Comment by liliya-soroka** [comment]
waiting for the fix

**Comment by liliya-soroka** [comment]
Verified, the keystone flow works if the correct network is selected in the onboard connect window
