### ISSUE TITLE
Aborting fetching component for router

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1112]
## Bug description

When opening the app, an error is thrown: "Aborting fetching component for router".

After [some reasearch](https://github.com/vercel/next.js/discussions/39040), it seems as though multipl calls to `router.push`/`router.replace` can interfere with each other. As we are calling `router.replace` in a `useEffect` in `@/pages/index.tsx`, this seems like the likely culprite. We should only be calling this once.

## Steps to reproduce
 1. Open the app at `/home` and observe the console error.

## Expected result

No error is thrown.

## Obtained result

"Aborting fetching component for router" is shown in the console.

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/200780439-e40f816e-c4b2-4954-ba00-3274592875c8.png)

**Comment by francovenica** [comment]
Looks good. The error doens't show anymore
As suggested, tested by just going to the welcome page, by going to an specific network and by loading the last used safe automatically
