### ISSUE TITLE
Redesign import dialog for address book

### ISSUE THREAD

**Issue by schmanu** [safe-global/web-core#1118]
## What is the feature about
For the global `Import all data` feature we redesigned the file upload / import dialog.
We should also apply this redesign to our 'Import addressbook' dialog.

## The list of requirements
- [x] Redesign dropzone
- [x] Redesign summary of import (outside / instead of dropzone)

## Designs/sketches
https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2053%3A57776

**Comment by francovenica** [comment]
Small thing, should we ask to edit the help blog with the new images? https://help.gnosis-safe.io/en/articles/5299068-address-book-export-and-import

**Comment by schmanu** [comment]
I adjusted the error message. Only the bottom message is now visible.
I will ping the rebrand team about the help articles.

Also I created this issue: #1174

**Comment by francovenica** [comment]
LGTM.
I also checked that in the import data you can still see the error message that was removed for this modal here.
