### ISSUE TITLE
[Safe Apps Analysis] 07. Page views i.e users opening screens in a Safe App (Frontend)

### ISSUE THREAD

**Issue by yagopv** [safe-global/web-core#1126]
# What it solves

We want to discover how people are using our main Safe apps

# Links

[Notion.  Page views i.e users opening screens in a Safe App](https://www.notion.so/gnosis-safe/Page-views-i-e-users-opening-screens-in-a-Safe-App-bf7468e26554410bbb149d614f5cc616)

**Comment by yagopv** [comment]
@clemoon, as we talk in the daily. What we want to analyze here ?  What do you think is interesting for us to know (i guess in WalletConnect and Transaction Builder only)

**Comment by clemoon** [comment]
Closing this issue following confirmation that it's not needed at the moment
