### ISSUE TITLE
[Safe Apps Analysis] 18. Safe Apps WAU, MAU (Frontend)

### ISSUE THREAD

**Issue by yagopv** [safe-global/web-core#1140]
# What it solves
We are creating a report showing the daily, weekly and montly variations in active users

# Links
[Notion. Safe Apps WAU, MAU](notion.so/gnosis-safe/Safe-Apps-WAU-MAU-d83982db920b4423be15aad06670e4a5)

# Report

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/1576776/201683412-06323646-b21a-41b9-aba4-aa6888f5f746.png">

**Comment by clemoon** [comment]
@yagopv why is the WAU and DAU the same here? It should be different. For instance if I take a sample of two weeks (like in the screenshot, there should be different values for WAU vs DAU) - some users only check weekly while some others check daily. 
<img width="1148" alt="Screenshot 2022-11-16 at 15 06 26" src="https://user-images.githubusercontent.com/21241679/202202055-763dffef-1e4c-40e3-ba6c-2b8989514506.png">

**Comment by clemoon** [comment]
Ok let's keep it under review pending until we can see the difference soon!

**Comment by clemoon** [comment]
The data is now showing more consistent so I'll move this to QA done!
