### ISSUE TITLE
Invalid chain short name in the URL error is not caught

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1154]
## Bug description

Opening the app with a safe address that contains an invalid shortname i.e. undefined:0x... will result in an error that is not caught.

Sentry: https://sentry.io/organizations/gnosis/issues/3740249359/?project=6769196&query=is%3Aunresolved&referrer=issue-stream

## Steps to reproduce
 1. Go to the Safe app
 2. Open a specific safe
 3. Change the shortname in the url to something that is not a chain
 4. Observe the app crashing and spamming errors in the console

## Expected behaviour

There are multiple ways we could solve this:

- Navigate user to `/welcome`. This is the same behaviour as on safe-react
- Show the 404 page
- Show a "Safe couldn't be loaded" error. (This would still do backend requests which is not ideal imo)
- Show a new error e.g. "Safe couldn't be loaded. Chain xyz does not exist". (This would still do backend requests which is not ideal imo)

Lets go with solution 1

**Comment by francovenica** [comment]
LGTM
Invalid chain prefix takes the user to the /welcome page. The error is logged in the console
Valid chain ID but with a safe that doesn't exist in that network shows the error "safe couldn't be loaded".
