### ISSUE TITLE
[EIP-1271] "Messages" routes/tab

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1155]
## What is the feature about

Implementation of the new EIP-1271 "Messages" tab under transactions, as well as routes.

## The list of requirements

- [x] Create `/transactions/messages` route
- [x] Create `/transactions/{{messageHash}}` route
- [x] Add "Messages" to transactions navigation tabs
- [x] Add page placeholder

## Designs/sketches

![image](https://user-images.githubusercontent.com/20442784/201890944-5fa54338-80cd-4a6c-888b-854f44af8bc3.png)
![image](https://user-images.githubusercontent.com/20442784/201891064-ddd72b40-e0cb-453d-a026-7ae989203634.png)

## Links

- [Problem statement](https://www.notion.so/gnosis-safe/EIP-1271-signatures-can-only-be-generated-on-chain-2800b5e516124d959c38ba8f2042f9f7?d=e8ca1d332df54ae587e66240fd40e230#a8489e3724234f75a9c3d389e323a725)
- [Figma design](https://www.figma.com/file/x1uuIJsOZkyv5cwNlDdVC1/EIP-1271?node-id=146%3A3470&t=F7CHK05WWFuPl1sq-0)

**Comment by regalwright** [comment]
> ## What is the feature about
> Implementation of the new EIP-1271 "Messages" tab under transactions, as well as routes.
> 
> ## The list of requirements
> * [x]  Create `/transactions/messages` route
> * [x]  Create `/transactions/{{messageHash}}` route
> * [x]  Add "Messages" to transactions navigation tabs
> * [x]  Add page placeholder
> 
> ## Designs/sketches
> ![image](https://user-images.githubusercontent.com/20442784/201890944-5fa54338-80cd-4a6c-888b-854f44af8bc3.png) ![image](https://user-images.githubusercontent.com/20442784/201891064-ddd72b40-e0cb-453d-a026-7ae989203634.png)
> 
> ## Links
> * [Problem statement](https://www.notion.so/gnosis-safe/EIP-1271-signatures-can-only-be-generated-on-chain-2800b5e516124d959c38ba8f2042f9f7?d=e8ca1d332df54ae587e66240fd40e230#a8489e3724234f75a9c3d389e323a725)
> * [Figma design](https://www.figma.com/file/x1uuIJsOZkyv5cwNlDdVC1/EIP-1271?node-id=146%3A3470&t=F7CHK05WWFuPl1sq-0)
