### ISSUE TITLE
[Transfer funds] Pressing enter will set the amount to max

### ISSUE THREAD

**Issue by schmanu** [safe-global/web-core#1164]
## Bug description
https://github.com/5afe/safe-support/issues/66

When pressing enter in the transfer funds modal the amount is set to max.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to transfer funds
 2. enter an amount
 3. press enter

## Expected result
Either nothing should happen or we should submit the form

## Obtained result
The amount is set to max

**Comment by francovenica** [comment]
LGTM.
Pressing enter in the input doesn't inputs the max amount anymore
