### ISSUE TITLE
[Safe creation] The browser hangs if "Upload an image" is used in "scan QR code" on add owners step

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1171]
1. start safe creation flow
2. add name
3. go to the next step 
4. click add owner->scan QR code
5. Upload an image -> Upload a valid QR code
Current result: The browser hangs
Expected result: It should be possible to add an owner using "Upload an image" on Scan QR code window

ENV: https://creation.web-core.pages.dev/new-safe/create
wallet: paired mobile app
relates to : https://github.com/safe-global/web-core/issues/864

**Comment by francovenica** [comment]
Fixed and merged already in the epic

**Comment by francovenica** [comment]
Fixed and merged already in the epic
