### ISSUE TITLE
[Landing page] fix Try Demo button link

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1172]
## Bug description
The link has a safe address, but it needs to have a "/home" at the end to actually go to that safe

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any
 - Env: https://gnosis-safe.io/

## Steps to reproduce
 1. Go to https://gnosis-safe.io/
 2. Check the try demo button in the middle

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/202201223-46c0c5de-6e7a-4b05-899e-b671690ee7ff.png)

**Comment by iamacook** [comment]
This seems to be working fine for me?

**Comment by francovenica** [comment]
LGTM
The /home is added if the safe address is on its own
Checked the redirectio to "last used" safe 
The navigation through the safe works fine
