### ISSUE TITLE
[safe creation]failed creation screen UI issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1175]
## Bug description
There are some diff from the design on the "failed creation" screen:
1. color of the message: the green on the design, the red after implementation
2. the position of the buttons is wrong

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to safe creation flow
 2. go to the last step
 3. click to submit to the wallet for signing
 4. reject in the wallet
## Expected result
![image](https://user-images.githubusercontent.com/338622/202205477-97662ceb-2d77-4faf-b681-a2a0e8440a91.png)

## Screenshots
![image](https://user-images.githubusercontent.com/338622/202204273-ee01b945-9020-47b0-b086-824939877798.png)

relates to https://github.com/safe-global/web-core/issues/864

**Comment by francovenica** [comment]
Looks good:
![image](https://user-images.githubusercontent.com/4503659/203188907-ce4c0a76-df52-420a-84fb-bfe03c3e95ba.png)
