### ISSUE TITLE
[Safe creation]Threshold number is missed when the owner is deleted from the step 3 if threshold=max number

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1178]
## Bug description
Threshold number is missed if the owner is deleted from the step 3 but the old max threshold is used on the review screen in safe configuration 

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain:Goerli

## Steps to reproduce
 1. Go to safe creation flow
 2. go to the safe owners step
 3.  add 2 owners
 4. set up threshold as 2
 5. remove one owner
 Current result: The setup threshold is empty.
<img width="428" alt="image" src="https://user-images.githubusercontent.com/338622/202207906-0e2eb417-2b5a-412b-9f60-554858b1df0e.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/338622/202208951-a419224e-0fc2-4f45-8193-734c5a784dac.png">

## Expected result
the threshold should take into account removed owner if it was set up to the max available number

relates to : https://github.com/safe-global/web-core/issues/864

**Comment by francovenica** [comment]
LGTM
