### ISSUE TITLE
[Safe creation] - 2nd step name is different than the one in the desing

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1184]
## Bug description
In the desing the name is "Select network & add name". In the current implementation is "Select network and name safe".
I haven't seen any conversation were the name was changed.

##Epic
#864 

## Screenshots
Design:
![image](https://user-images.githubusercontent.com/4503659/202326828-558a39f1-1e06-4b8e-a9d2-7f53f40e1ed4.png)

![image](https://user-images.githubusercontent.com/4503659/202326860-e41d27b7-bd0a-4791-a590-7fef02f489cd.png)

**Comment by francovenica** [comment]
Before doing anything in this ticket. I've seen that a bunch of the text in the design are not the same as the one in the app. Have all these texts changed in a ticket/discussion?

**Comment by iamacook** [comment]
> I've seen that a bunch of the text in the design are not the same as the one in the app. Have all these texts changed in a ticket/discussion?

I reviewed and adjusted text throughout development. I would suggest @liliiaorlenko verifies the current text implementation first.

**Comment by usame-algan** [comment]
We updated the texts in the design and implemented them with #1198
