### ISSUE TITLE
[safe creation] Dark theme issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1191]
see details in the - https://5afe.slack.com/archives/C03DAGWJCR5/p1668614769462569

**Comment by francovenica** [comment]
I'll leave what Liliya wrote here so we don't have to go the slack converstaion.

I've checked the list and the issues were fixed

-progress bar should be green/blue as at the claiming app
-the tips fades out a little, can we add a border of main colour shade, if tip is light blue - add a full blue border to the tip
-at the review screen, the network fee doesnt have a styling, pls apply the same border (6px) and a colour (#EFFFF4) as on a light mode
-at the safe indexing pages the icons is reeeaaally tiny, could ve make them bigger, 16px like other icons?
-also the colour of notification is a bit fades away, which colour could we apply or also add a corresponding border colour
the icons on welcome page is black and would be great if they are white
