### ISSUE TITLE
Banner is displayed over the app header 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1202]
## Bug description
The banner is displayed aover the app header, as a result, it's not possible to keep the banner and connect an owner's wallet
## Environment
 - Browser: any
 - Wallet: any
 - Chain: any

## Steps to reproduce
 1. Go to safe. global with the banner enabled

## Expected result
It should be possible to see the header and connect the wallet without the banner closing.

## Screenshots
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/338622/203026293-40b87892-3467-471f-b74f-521c41f9ac0a.png">

**Comment by usame-algan** [comment]
A possible solution would be to show a notification instead.
<img width="1567" alt="Screenshot 2022-12-05 at 13 56 33" src="https://user-images.githubusercontent.com/5880855/205651217-2a246575-84f5-4ee7-a57e-dd95064a301f.png">
