### ISSUE TITLE
Add loading icon when the address check is in progress

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1203]
## Bug description
Add loading icon when the address check is in progress .
It's really useful when the back-end is slow for some reason.
We had green loading icon in safe-react
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to add existing safe flow on staging CGW ( it's slow now)
 2. add valid address
Current result: Continue button stays grey for a long time and it seems that the UI does nothing

## Expected result
add loading icon to the field to show that the address check is in progress
## Screenshots
<img width="852" alt="image" src="https://user-images.githubusercontent.com/338622/203028374-5db1f4ce-6e4a-459f-9e29-1f7d2c200f78.png">

**Comment by usame-algan** [comment]
I tried reproducing it without success. There is a loading icon in the name field when ENS is resolving but the Continue button is only disabled if there is an invalid address so it should not be affected by it. The valid address check is done without anything asynchronous going on so we don't have a loading state there.

**Comment by francovenica** [comment]
I've checked this in the new Add safe workflow and there it works fine, the load icon shows up until the safe is validated.
I'll close this one
