### ISSUE TITLE
[EIP-1271] Test dApp

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1207]
## What is the feature about

A demo app to trigger EIP-1271 signing.

## The list of requirements

- Create a new dApp with support for off-chain signing (we can use the `safe-apps-test-app` for testing Safe Apps/WC Safe Apps connection for Safe Apps integration testing).
- Include actions that trigger:
  - `eth_sign`
  - `eth_signTypedData`

## Links

- [Problem statement](https://www.notion.so/gnosis-safe/EIP-1271-signatures-can-only-be-generated-on-chain-2800b5e516124d959c38ba8f2042f9f7?d=e8ca1d332df54ae587e66240fd40e230#a8489e3724234f75a9c3d389e323a725)
- [Test repo](https://github.com/5afe/eip-1271-dapp)

**Comment by katspaugh** [comment]
Does the safe-apps-test-app connect via WalletConnect?

**Comment by iamacook** [comment]
> Does the safe-apps-test-app connect via WalletConnect?

It's possible to connect Safe-Safe via WC and use Safe Apps as far as I am aware.

**Comment by katspaugh** [comment]
I'm talking about directly connecting a Safe as a wallet to a 3rd-party dapp that knows nothing about Safe.

**Comment by iamacook** [comment]
> directly connecting a Safe as a wallet to a 3rd-party dapp that knows nothing about Safe.

Valid point. I'll reopen this.

**Comment by liliya-soroka** [comment]
done
