### ISSUE TITLE
[Safe token widget] Adjust amount after redeem deadline is reached

### ISSUE THREAD

**Issue by schmanu** [safe-global/web-core#1208]
**Note: Add this to first december sprint**
## What is the feature about
Once the redeem deadline of the airdrop contracts (user & guardian) is reached, we have to adjust the voting power in the safe token widget.

Currently it just adds all allocations from our hosted data.

Then we need to check on-chain if the tokens have been redeemed and only count allocations which have been redeemed.

## The list of requirements
- Adjust formula after 27th December

Note: We will create a new issue to implement these changes in the safe-claiming-app

**Comment by liliya-soroka** [comment]
Verified: web-core changes were checked together with claiming app changes
