### ISSUE TITLE
[Safe Creation] Some GTM Events are missing

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1213]
## Bug description

- Some GTM events are not sent in the new creation flow (https://github.com/safe-global/web-core/issues/864#issuecomment-1321371393)

## Expected result

- Send number of owners and threshold event
- Send safe name event
- Send tx confirmation event
- Send events when user opens a hint

**Comment by francovenica** [comment]
Looks good

Safe name
Owner amount
Policies
and every tip have their own tracking event.
