### ISSUE TITLE
Refactor `TxSigners` to match `MsgSigners`

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1218]
## What is the feature about

`TxSigners` uses MUI's `Stepper` component and it is overly complex/has visual inconsistencies when compared to the design.

## The list of requirements

- Remove `Stepper` from `TxSigners`
- Use `MsgSigners` `List` implementation for transaction confirmations in `TxSigners
- Use icons from `MsgSigners` instead of those from MUI

Note: it would be worthwhile migrating the CSS from `MsgSigners` to `TxSigners` as the "Messages" code always imports CSS from the transaction list.

## Designs/sketches

- [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=265%3A9731&t=QCxWXBVhxT0b29nF-0)

**Comment by DiogoSoaress** [comment]
Even when missing confirmations in the off-chain signatures, we display the `signed` icon
![Screenshot 2022-12-28 at 11 13 17](https://user-images.githubusercontent.com/32431609/209803929-2bead749-af09-4b24-b556-3075c2cb5ad5.png)
whereas if we miss confirmations in the queue we have a RadioButtonUnchecked icon
![Screenshot 2022-12-28 at 11 13 25](https://user-images.githubusercontent.com/32431609/209804013-be500750-ca44-4c88-b484-73a2017a112c.png)
which gives a better visual feedback if missing confirmations/signatures.

Is it something we should align in both steppers?

**Comment by liliiaorlenko** [comment]
If threshold is not reached we show RadioButtonUnchecked
https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=3232%3A70591&t=HnzOAX46QougL99X-1

**Comment by liliya-soroka** [comment]
Verified, done.
Thank you @DiogoSoaress
