### ISSUE TITLE
Reference transaction `trusted` flag when showing the `UnsignedWarning`

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1220]
## What is the feature about

The `UnsignedWarning` is currently shown when no signatures are present. However, the gateway will soon forward the `trusted` flag of each transaction as well, which should also be referenced.

## The list of requirements

The conditional rendering logic needs to be extend to include the `trusted` flag as follows:

```ts
{!trusted && <UnsignedWarning />}
```

## Links
- [Gateway issue](https://github.com/safe-global/safe-client-gateway/issues/1005)

**Comment by katspaugh** [comment]
Shouldn't we use _only_ the trusted flag?
@Uxio0 it's always `trusted=true` for signed transactions, right?

**Comment by Uxio0** [comment]
Yes, `trusted` flag is all you need. Transactions signed but at least one owner are `trusted`. Even if you remove the owner, transaction will still be `trusted`

**Comment by katspaugh** [comment]
@francovenica the trusted flag is now on staging backend, please test the following cases:

* A delegate-created tx should NOT be marked as untrusted
* MMI txns should NOT be untrusted
* Regular transactions proposed w/o a signature SHOULD be untrusted (ask a dev to make you one)

**Comment by iamacook** [comment]
>     * Regular transactions proposed w/o a signature SHOULD be untrusted – you can create them on this branch https://drafts.web-core.pages.dev – just uncheck the Sign checkbox in the tx modal. But view them via a deep link on dev.

I just created an unsigned transaction on staging here for you to confirm: `gor:0x65c57CC1317a1f728E921Cbf7bC08b3894196D29/transactions/tx?id=multisig_0x65c57CC1317a1f728E921Cbf7bC08b3894196D29_0xec49a9f9eee0446834c1c4ee00ca1b366f604d5e09555c34c9cd9a29c508757f`

![image](https://user-images.githubusercontent.com/20442784/203928791-09e582f2-ee98-4dca-a6db-b3d376470102.png)

**Comment by JagoFigueroa** [comment]
Adding this scenario affecting safe apps:

https://user-images.githubusercontent.com/92332710/204233045-86ac699d-b277-4a82-ba96-05557874f42b.mp4

When the pop up to view the transaction is clicked, txs are showing as untrusted for me until the transaction is indexed. Then it will lose this status.

**Comment by katspaugh** [comment]
@JagoFigueroa fixed in #1261. Immediately executed transactions in 1/x Safes won't be visible until executed.
