### ISSUE TITLE
[Mobile pairing] - Cannot switch the account connected to the web app

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1233]
## Bug description
After pairing, switching the owner in the mobile app doesn't change it in the web app. 

## Environment
 - Browser: Chrome
 - Wallet: Mobile pairing (iOS safe mobile app)
 - Chain: Any
 - Env: https://app.safe.global/welcome

## Steps to reproduce
 1. Have at least 2 privated keys imported into your $afe mobile phone app
 2. Connect using mobile pairing and pick
 3. one of the accounts
 4. In the top right corner of the web app the owner should be shown connected with mobile pairing
 5. Switch to the other

## Expected result
In the top right corner it changes from one owner to the other

## Obtained result
The current owner address "flickers" for split second but doesn't change to the owner you picked in the mobile app. It remains the same

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/203670526-da790742-4c32-485e-8b20-0b35c876e68e.png)

Every flickr is me trying to change owner
![flickr](https://user-images.githubusercontent.com/4503659/203671777-7ffc2e85-4f0f-49ee-a4b3-32716b982f8f.gif)

**Comment by usame-algan** [comment]
Tested this with WalletConnect and have this issue there too.

**Comment by francovenica** [comment]
Looks good. Works fine with both WC (MM phone app) and Safe mobile app pairing
