### ISSUE TITLE
Prevent scroll from altering `type="number"` fields

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1234]
## Bug description

Scrolling on a trackpad or mousewheel increases/decreases the value of `type="number"` fields. This should not happen in order to prevent unexpected nonces, etc.

Note: this is relevant for *all* `type="number"` fields across the app.

Mui docs on type number fields: https://mui.com/material-ui/react-text-field/#type-quot-number-quot

## Steps to reproduce
 1. Open the transaction creation modal and edit the nonce value.
 2. Scroll on the trackpad or mousewheel inside the field.

## Expected result

The field values do not change.

## Obtained result

The field values change.

## Screenshots

![scrollnumber](https://user-images.githubusercontent.com/20442784/203728220-c47af505-6545-47e9-a2a4-e5d97e82ca2d.gif)

**Comment by francovenica** [comment]
LGTM. Never thought about this, good catch
