### ISSUE TITLE
Retrieve Fallback Handler via `safe-core-sdk`

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1236]
## What is the feature about

Now that the `safe-core-sdk` [supports management of the Fallback Handler](https://github.com/safe-global/safe-core-sdk/issues/262), we should leverage that instead of instantiating it ourselves.

## The list of requirements

- Update the `safe-core-sdk` to a version that supports the above.
- Instantiate the Fallback Handler via it.

**Comment by francovenica** [comment]
Safe creation LGTM
