### ISSUE TITLE
Don't propose unsigned transactions

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1261]
In a 1/X Safe, it's possible to create and immediately execute a transaction w/o signing it.

We're currently "proposing" such txns to the backend, where they are marked as untrusted until indexed.

@Uxio0 says we shouldn't do this. The ability to "propose" w/o signatures will be removed in the future on the backend.

**Comment by iamacook** [comment]
We need to ensure this works well with smart contract wallet owners. Currently, if a Safe owns a Safe ("parent" vs. "nested"), the "parent" can queue the approval of a transaction of the "nested" Safe. As such, the "nested" Safe currently proposes a transaction without signatures.
