### ISSUE TITLE
[Update notification] - Is shown to non owners in the list of past notification

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1267]
## Bug description
Comming from a safe you own that requires updating, if you switch to another safe that you don't own the notification is triggered again and is listed in the past notifications (the bell in the top) for that safe you are currenlty in

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet
 - Env: https://release-1-1-0.web-core.pages.dev/

## Steps to reproduce
 1. Have two safes in the sidebar, one you own < 1.3.0 and another you don't own of any version
 2. Go to the safe < 1.3.0 you own
 3. See the notification popping up and check the bell in the top bar
 4. Clear the notifications
 5. Go to the other safe you don't own

## Expected result
No notification should shown. No past notifications should be listed in the past notifications list

## Obtained result
No notification is shown, but still you can see it in the past notification list

## Screenshots
Here I'm in a safe that I own and is fully Updated
Change to a safe that requires updating
Then changes to a safe I don't own and is fully updated
The notification in the list still has the link of this safe I don't own
![notifications](https://user-images.githubusercontent.com/4503659/204415799-bf3924a9-0150-4e6e-aacc-2b47a5436ea9.gif)

**Comment by katspaugh** [comment]
I think it's OK that it's shown in the history, but it's definitely a bug that the link takes you to the current Safe settings, not the one the notification was triggered in.

**Comment by francovenica** [comment]
That third notification is generated when I enter into that last safe that I don't own and doesn't need to be updated. So that notification should not be generated at all.
