### ISSUE TITLE
Fix the text in the error message when the tx will most likely fail

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1277]
Steps:
1. go to the safe gno:0x9DF58F04F3e914ED8D972146401C85313A53FecA on prod env
2. try to execute the tx with nonce=44

Current result:
"missing revert data in call exception; Transaction reverted without a reason s
tring" 
![Image](https://user-images.githubusercontent.com/338622/204533187-c195199b-3175-4124-b7a3-b494c61f4d30.png)

Expected result: Could we control the view of the error ?

Prod env.
Chain: Gnosis chain

**Comment by usame-algan** [comment]
> Could we control the view of the error ?

Not sure I understand, could you expand a bit more on what is expected?

**Comment by DiogoSoaress** [comment]
@liliya-soroka you mean the error message wrapping better? i.e, without breaking "string" ?
