### ISSUE TITLE
Cant create tx on goerli

### ISSUE THREAD

**Issue by liliiaorlenko** [safe-global/web-core#1283]
## Bug description
Address: gor:0x462e80c8E2dD569883D8C54bF5dfAd9C264065BE
<img width="1728" alt="Screenshot 2022-11-29 at 16 49 20" src="https://user-images.githubusercontent.com/94694401/204582498-4a0d55f5-3ed8-481b-a206-3d6d2decaece.png">
<img width="1724" alt="Screenshot 2022-11-29 at 16 50 18" src="https://user-images.githubusercontent.com/94694401/204582502-3185a476-7587-4c96-957c-bff9a3948fb3.png">
<img width="1728" alt="Screenshot 2022-11-29 at 16 50 48" src="https://user-images.githubusercontent.com/94694401/204582508-76aae270-ed76-4aed-a486-08a3c17a9c2f.png">

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Send tokens 
 2. Select token address and amount - NEXT
<img width="1143" alt="Screenshot 2022-11-29 at 16 55 29" src="https://user-images.githubusercontent.com/94694401/204578513-711e7e96-4966-48b3-8d44-e92769909f78.png">
3. 1 second loading of the next modal...
4. This view occurs
<img width="1728" alt="Screenshot 2022-11-29 at 16 50 48" src="https://user-images.githubusercontent.com/94694401/204578651-c0149257-9471-40d6-a12a-77e8e4ba7c7b.png">

After reproducing issue again, tx went through, but
1. Send tokens
2. Select token address and amount - NEXT
3. Review transaction - SUBMIT
4. Notifications show that tx went through but the screen looks like this
<img width="1726" alt="Screenshot 2022-11-29 at 17 00 28" src="https://user-images.githubusercontent.com/94694401/204580369-7957053c-8754-4cdc-a34a-970efbf79b51.png">

After waiting for 2-3 minutes, tx is still indexing
<img width="1728" alt="Screenshot 2022-11-29 at 17 11 09" src="https://user-images.githubusercontent.com/94694401/204582193-794b62a3-6430-4eda-8380-0b960bf0002d.png">

Only when I refresh the page this screen disappears. 

## Screenshots
<img width="1728" alt="Screenshot 2022-11-29 at 16 50 48" src="https://user-images.githubusercontent.com/94694401/204577878-5e306e5c-0606-44f7-bc82-2bacb9f0c55f.png">

**Comment by DiogoSoaress** [comment]
I don't think the slow indexer is a bug that we can solve on the FE given the backend was experiencing some delay on Goerli.

I will reproduce the error that seems coming from the `undefined` address and fix it.
