### ISSUE TITLE
Open accordions with a smooth transition

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1303]
## What is the feature about

Open accordions with a smooth transition. This was tried in #1064 but resulted in too many network requests on page load. Instead we could change the logic to only fetch when the accordion is expanded.

## The list of requirements

- Open accordions with a smooth animation
- Only fetch their data once they are expanded

**Comment by francovenica** [comment]
@usame-algan The multisig call everytime you open a tx:
![multisig call](https://user-images.githubusercontent.com/4503659/205947131-f06d2c09-52bc-40a0-9231-54ee54ac9295.gif)
