### ISSUE TITLE
[Safe creation] - Cancelling with trezor makes the process get stuck 

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1316]
## Bug description
When cancelling the safe creation tx, it makes the last step that is waiting for the response of "accept" or "reject" get stuck and never end
This happens in both the old and new safe creation flow

EDIT: The same issue happens with Ledger ( I assume it has the same origin). The difference is that it doesn't shows the same errors in the network tab

## Environment
 - Browser: Chrome
 - Wallet: Trezor One
 - Chain: Ethereum mainnet
 - https://app.safe.global/open

## Steps to reproduce
 1. Connect with trezor and Go to https://app.safe.global/open
 2. Get to the last step of the safe creation
 3. Click sign and wait for your trezor to show the Accept/cancel options
 4. Press cancel

## Expected result
The last step shows that the user cancelled the tx. Shows a notification saying the same. Shows the Cancel/Retry buttons

## Obtained result
It keeps waiting for a response. Errors are shown in the console

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/206058961-53b56e74-79dd-4781-95cc-d1ad8a4a18b7.png)
![image](https://user-images.githubusercontent.com/4503659/206058969-d0f2c8b8-0390-418a-ad77-b59e4962cecc.png)
Is weird that the request is hitting that IP instead of the prod url.
All those errors (listen, 10, null) show similar URL with that IP

**Comment by francovenica** [comment]
The same issue happens with Ledger ( I assume it has the same origin). The difference is that it doesn't shows the same errors in the network tab

**Comment by usame-algan** [comment]
This looks like the same issue that https://github.com/safe-global/web-core/pull/1293 fixed. Can you check if it still happens on dev?

**Comment by francovenica** [comment]
Yes, in the #1293 the issue doesn't happen.
I'll close this ticket and recheck during regression
