### ISSUE TITLE
Add option to update `CompatibilityFallbackHandler`

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1318]
## What is the feature about

Setting the `CompatibilityFallbackHandler` (`CFH`) is not a necessity when deploying a Safe. This means that some "normal" functionality may not be available, e.g. [EIP-1271 signature validation](https://github.com/safe-global/safe-contracts/blob/main/contracts/handler/CompatibilityFallbackHandler.sol#L28). As the address needs to be manually set, it also allows for custom `CFH`s to be set in its place.

We should add a CRUD in the Safe settings to allow for the modification of the `CFH` address/setting it to the "recommended" deployment address. It would also be beneficial to show what it entails and whether one is set or not.

## The list of requirements

- Add a new section to the settings displaying the current  `CFH` deployment address used.
- Display associated information regarding what the  `CFH` is and what address is currently set/whether it is the "recommended" one.
- Add a CRUD modal flow to create a transaction that modifies the set `CFH`.
- The fallback handler section in the settings should only be visible if the current contract version supports fallback handlers

## Designs/sketches

tbd

## Links

- [Discussion thread](https://5afe.slack.com/archives/C03DAGWJCR5/p1670412974409759) regarding missing `CFH`s during early development of `web-core` resulting in this issue.

**Comment by schmanu** [comment]
I'm closing it as we decided it is too technical and for the users who need to do this the transaction builder Safe app works perfectly.
