### ISSUE TITLE
Better formatter for exact token amounts

### ISSUE THREAD

**Issue by DiogoSoaress** [safe-global/web-core#1321]
## What is the feature about
Using the utils [number formatter](https://github.com/safe-global/web-core/blob/5fc780a46b7400416ba812bfc8a4e1a2a7acf2d3/src/utils/formatNumber.ts#L96-L104) does not give a very precise view to the amount of tokens to be transferred.

Implement a new formatter to provide the exact amount of tokens with the token decimals precision and for large integer values.

## The list of requirements
Values like `8647590866.12348974303845098` to be represented like
<img width="590" alt="Screenshot 2022-11-28 at 18 23 34" src="https://user-images.githubusercontent.com/32431609/206213686-fd17ddf6-ba15-4f6a-8643-f586495ded1a.png">
instead of
![Screenshot 2022-12-07 at 16 01 51](https://user-images.githubusercontent.com/32431609/206213887-8c460335-64b4-4936-b3ae-344bb933294d.png)

**Comment by katspaugh** [comment]
Before we create more inconsistency in how we format numbers in different components, I'd suggest we document all the situations in which we need to format amounts and come up with a strategy. I suspect there are places where we want a terser (rounded) display and precision in other places.

**Comment by DiogoSoaress** [comment]
> Before we create more inconsistency in how we format numbers in different components, I'd suggest we document all the situations in which we need to format amounts and come up with a strategy. I suspect there are places where we want a terser (rounded) display and precision in other places.

Good idea. I will create a doc and bring it up tomorrow for after the daily

**Comment by iamacook** [comment]
I'm going to close this as we already implemented it [here](https://github.com/safe-global/web-core/pull/1265).
