### ISSUE TITLE
Amount input not formatted in Send tokens modal

### ISSUE THREAD

**Issue by DiogoSoaress** [safe-global/web-core#1325]
## Bug description
- In "Send tokens" modal, the selected asset balance can have a different formatting than the amount.
- The input also accept both `,` and `.` as decimal separators and does not format the inputted number with thousands separator.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to Send Tokens modal
 2. Insert an amount sufficient to see the thousand separators

## Expected result
Amount input is formatted as per locale

## Screenshots
<img width="187" alt="206214106-e5e88ffe-449d-4eda-804b-705d6f272459" src="https://user-images.githubusercontent.com/32431609/206254709-89993e2b-3a33-4f9b-8814-1ac8bb05cb47.png">

**Comment by katspaugh** [comment]
If we decide to format numeric inputs, I suggest that we do it only on blur.

**Comment by katspaugh** [comment]
Let's not format it for now.
