### ISSUE TITLE
App crashes on the Settings->Modules page for Safes with the wrong mastercopy

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1327]
A user reported a mystery Polygon Safe with the mastercopy set to the same address as the owner of the Safe.

The app starts frantically reloading the page in a loop if you open this Safe's Settings->Modules.

Need to catch and properly handle this error.

See https://5afe.slack.com/archives/C03BHKS5K6D/p1670470859871949

**Comment by liliya-soroka** [comment]
Verified: unsupported version is shown on the safe settings and module tab is not reloaded
