### ISSUE TITLE
The "expand sidebar" button is inaccessible with a keyboard on safe apps view 

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/web-core#1331]
## Bug description
The button cannot be focused using keyboard

## Environment
 - Browser: Arc
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to https://app.safe.global/gor:0x6Aa244e4eeE4F31d391674BD8cDf6Bc38Ad1D83B/apps?appUrl=https://apps.gnosis-safe.io/wallet-connect
 2. Try to focus the sidebar button using keyboard only

## Expected result
The button is focusable

## Obtained result
Button cant be focused

**Comment by DaniSomoza** [comment]
Hi For me its working fine.

I press 5 times the  `Tab` key and the sidebar button is focus, then I can collapse the sidebar by pressing the `Enter` key:


https://user-images.githubusercontent.com/26763673/207051158-4839d93c-5232-4618-8a0e-194651088b3c.mov

**Comment by yagopv** [comment]
@JagoFigueroa can you take a look? I think is working fine now

**Comment by JagoFigueroa** [comment]
It is working for me as well señores, I've checked on the same browsers as you Yago and the sidebar can be focused + there is feedback in both dark and light themes. I will go ahead and close this ticket.

Un abrazo 😉
