### ISSUE TITLE
 "Overwrite data?"  is shown before dropping a file 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1356]
Regression issue for the 1.2.0 rc
        4. Hola again! For this señor [ticket](https://github.com/safe-global/web-core/pull/1306) regarding the export/import for this case mentioned on the ticket:

- Show the "Overwrite data?" alert only after dropping a file

I can see that we are showing the alert before uploading the JSON file. Nothing major or anything but Is it expected?

<img width="620" alt="Screenshot 2022-12-13 at 09 59 35" src="https://user-images.githubusercontent.com/92332710/207273560-9c5c8d62-6859-45c5-b3e9-ecce221e7aa6.png">

Cheers!

_Originally posted by @JagoFigueroa in https://github.com/safe-global/web-core/issues/1341#issuecomment-1347973277_

**Comment by iamacook** [comment]
We previously discussed this and agreed to show the warning all the time.
