### ISSUE TITLE
[Replace tx] Edit nonce is available during signing "unsigned tx" in the queued list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1364]
## Bug description
Edit nonce is available during signing "unsigned tx" in the queued list
## Environment
 - Browser: Chrome
 - Wallet: MMI extension
 - Chain: Goerli

## Steps to reproduce
 1. Create a tx in the safe using MMI extension => unassigned tx is created in the queued list as Next tx- 

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/338622/207379387-bfe51124-4f8c-4988-a119-f833d525a092.png">

2. go to the web-core interface and start the signing process with the owner EOA
3. go to the advanced option
4. Edit nonce is available 
Current result: nonces of all  txs in the queued list is available for selecting 

5. select another nonce and finish signing
Current result: the original ts stays unassigned and a new tx appears under selected nonce

## Expected result
Do we want to allow "edit nonce" for unassigned tx? It's not allowed during signing existed tx in general.

## Screenshots
<img width="657" alt="image" src="https://user-images.githubusercontent.com/338622/207380165-a1af84a4-c93f-4d17-887e-70ac83f8bdf9.png">

**Comment by katspaugh** [comment]
True, good argument.
