### ISSUE TITLE
Rpc issues with default mainnet.optimism.io

### ISSUE THREAD

**Issue by miguelmota** [safe-global/web-core#1366]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Optimism

## Steps to reproduce

1. Go to gnosis safe app and click Hop Protocol app
2. Select Optimism as "from" chain and Mainnet as "to" chain 
![DeepinScreenshot_select-area_20221212180524](https://user-images.githubusercontent.com/168240/207208303-443572a7-6487-4fe6-be18-bc056619e465.png)

Observe console and network errors because it's using `https://mainnet.optimism.io` as specified in gnosis safe endpoint `https://safe-client.safe.global/v1/chains`

![DeepinScreenshot_select-area_20221212181806](https://user-images.githubusercontent.com/168240/207209909-9d95290c-9b00-4675-9120-e26a565c5cb0.png)

Going to Hop Protocol app directly and following same "from" and "to" chain steps does not result in errors.

My metamask is not using mainnet.optimism.io, it's using a separate alchemy endpoint. Hop UI is also not using mainnet.optimism.io, so this appears to be an issue specific to gnosis safe ui.

## Expected result

No rpc errors

## Obtained result

Rpc 429 errors

## Screenshots

![DeepinScreenshot_select-area_20221212175933](https://user-images.githubusercontent.com/168240/207208128-8d9137a2-05e1-40fe-b057-e45270abdcb9.png)

Is there a way to change the default optimism provider on gnosis safe ui? Thanks in advance

**Comment by katspaugh** [comment]
Thanks, @miguelmota, we'll take a look. Transferred the issue to our new repo: https://github.com/safe-global/web-core

You can't yet change the RPC via the UI, but we're working on it.

**Comment by katspaugh** [comment]
We've now set the default RPC to Infura. Should be much more reliable.
Thanks for the report @miguelmota!

**Comment by miguelmota** [comment]
Great!
