### ISSUE TITLE
confirmations list is not updated on tx details without expand/collapse the tx or manual refresh

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1374]
## Bug description
confirmations list is not updated on tx details without expand/collapse the tx or manual refresh
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Go to the queued tx list
 2. expand tx and click the "Confirm" button on tx details without tx execution
 3. wait till the number of confirmations is updated 

## Expected result
Make sure that the tx details in expanded view is updated too after signature is received without extra step from the user
## Obtained result
the tx header is updated with the correct number of confirmations, but the tx details in expanding a view is not updated. It might be the reason of some support comments about the wrong number of confirmations, because if I change the MM owner Confirm button is available and I can add one extra signature 
## Screenshots
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/338622/207619809-d6a0a667-4edf-472a-a448-6464c275078b.png">
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/338622/207620583-6809f11f-f482-411e-8665-6961e2067617.png">

**Comment by iamacook** [comment]
I would suggest we first tackle [this](https://github.com/safe-global/web-core/issues/1218) as it may fix this issue.
