### ISSUE TITLE
[EIP-1271]Sign message modal issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1392]
## Bug description
Sign message modal issues:
1. will we have app logo and name at the top of the Message as on the design?
2.  Copy button is not seen if the Safe Message is too long 
3.  @liliiaorlenko , could you check the view of the modal in dark theme ( it looks too black-white )
4.  EIP-712 : some long parameters are not seen in the modal - Could we truncate it?  @liliiaorlenko , may be hide the message by default ?
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Try to create off-chain message

## Expected result
https://www.figma.com/file/x1uuIJsOZkyv5cwNlDdVC1/EIP-1271?node-id=1%3A2&t=beNQIp51uWjCLjmD-0
## Screenshots
EIP- 191  :  <img width="679" alt="image" src="https://user-images.githubusercontent.com/338622/208614513-2b045249-681d-476b-b4e2-6cafaf89ceab.png">

EIP-712:  
<img width="698" alt="image" src="https://user-images.githubusercontent.com/338622/208617833-e65ce138-32b8-47bf-88f9-0606707b901c.png">

**Comment by iamacook** [comment]
> could you check the view of the modal in dark theme ( it looks too black-white )

The modal uses the theme and matches the others.

**Comment by liliya-soroka** [comment]
Reopened:
2. I don't see copy button at all now and even part of the "safe message" or "message hash" is hidden
![Image](https://user-images.githubusercontent.com/338622/208909024-0d3d1381-c0af-4309-a9ba-56a912b84f55.png)


4.the problem with long data was not solved . Could we have the same view for it as on create tx modal window?

![Image](https://user-images.githubusercontent.com/338622/208909234-b6c091a4-6ce1-4ed7-8275-348c60611abb.png)

**Comment by liliya-soroka** [comment]
Verified in the epic PR
