### ISSUE TITLE
[EIP-1271] Format the message nicely

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1393]
## Bug description
Message text is displayed above confirmation block on message detail - EIP-712
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Create EIP-712 sign message 
 2. go to the messages list
 3. open message details 

## Screenshots
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/338622/208631967-b35f9ef3-401e-441f-989d-42c2b4ba5dd4.png">

**Comment by liliya-soroka** [comment]
Reopened:
for macbook 13"

**Comment by liliya-soroka** [comment]
@schmanu , the issue is back 
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/338622/210222279-068f642f-2f5a-4f14-a4ce-5dc2c56e67d4.png">

after [[EIP-1271] Message parameter in case of EIP-712 has diff from the design state on Confirm message modal#1438](https://github.com/safe-global/web-core/issues/1438) fix

**Comment by katspaugh** [comment]
Merged the fix into the epic branch.

**Comment by liliya-soroka** [comment]
Now the block with data pushes the confirmation block, so I need to scroll the page horizontally, but it's not obvious 


![Image](https://user-images.githubusercontent.com/338622/212093327-a5f012b5-246d-4e28-8dc0-0acc042a2baa.png)

**Comment by katspaugh** [comment]
Horizontal scroll is def a bug.

Bonus idea from @schmanu: since we know the types of each field, we can display it the same as the decoded data in txns (addresses as EthHashInfo, etc).

**Comment by liliya-soroka** [comment]
@johannesmoormann  , @katspaugh , @liliiaorlenko  I need help with approving the current view  

The message details in case of EIP-71
https://user-images.githubusercontent.com/338622/212734224-1bd99014-a99e-4025-92bf-8d58e674ceaa.mov


Create message modal 
https://user-images.githubusercontent.com/338622/212734577-02b50557-b20d-4bb7-849f-414f943ef3fb.mov

I would say that it's ok for the integration phase, but I don't like it as a ready-to-prod release view.

**Comment by liliiaorlenko** [comment]
what do you think about this approach, we click on show all + new expand icon and we open full screen modal with data
<img width="756" alt="Screenshot 2023-01-17 at 11 19 10" src="https://user-images.githubusercontent.com/94694401/212872589-9bf4bb0d-0050-4d98-b06b-2a2427077ddb.png">
<img width="752" alt="Screenshot 2023-01-17 at 11 19 16" src="https://user-images.githubusercontent.com/94694401/212872599-c0dd505d-f58d-4fd5-b3cb-3e3a4f1dd986.png">

**Comment by liliya-soroka** [comment]
Verified
