### ISSUE TITLE
[EIP-1271]Status is not changed from confirming to Confirmed without manual page refresh

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1394]
## Bug description
Status is not changed from confirming to Confirmed without manual page refresh
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Create a few messages
 2. Go to the Messages tab
 3. confirm all messages to change "Need confirmation" ->"Confirming"->"Confirmed" states
 Current result: The message stays in the "Confirming" state. Only manual; page refresh updates the state to "Confirmed"

## Expected result
Update the state at the same time when the message about "confirmed" message appears on UI

## Screenshots
<img width="277" alt="image" src="https://user-images.githubusercontent.com/338622/208634262-5a0f6f40-f9ee-4cb7-9d0e-0dce47c6ce5f.png">

**Comment by liliya-soroka** [comment]
Verified

**Comment by francovenica** [comment]
I've checked for 1/x safes and the status looks good as well
