### ISSUE TITLE
Remove old safe creation and AB test

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1404]
## Description

The A/B test results for the new safe creation flow were positive so we want to clean up the old components and the A/B test setup.

## Requirements

- Copy existing tests from `src/components/create-safe` into the new directory `src/components/new-safe`
- Remove `src/components/create-safe`
- Remove AB test related logic (this will most likely be replaced at a later time with something like Google Optimize)

**Comment by katspaugh** [comment]
Only `/new-safe/create` and `/new-safe/add` should remain.
