### ISSUE TITLE
[Safe Apps Discoverability] Add drawer with Safe App details

### ISSUE THREAD

**Issue by dasanra** [safe-global/web-core#1414]
## What is the feature about
Currently we are not able to display much information to the users before opening a Safe App. The list is getting big and we can't make list elements bigger. Meanwhile we are also not showing all the information we have from a Safe App.

## The list of requirements

- [x] Add drawer and display after clicking on a list element
- [x] Show app image
- [x] Display Safe App title
- [x] Display Safe App description
- [x] Display available chains
- [x] Display related tags

## Designs/sketches
https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2231%3A64547&t=TbMGxqHlZIwALJBx-0
![imagen](https://user-images.githubusercontent.com/25051234/208899766-de87ca90-2c00-43c5-996a-450a3fb685e2.png)

## Links
 - [Problem statement](https://www.notion.so/gnosis-safe/Safe-Apps-Interface-Discoverability-Features-0c4bd0da771843bcb06e1253aa5bacde)
 - [Designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2231%3A64547&t=TbMGxqHlZIwALJBx-0)

**Comment by katspaugh** [comment]
I see that the app links on the Dashboard are still opened directly in fullscreen, is this intended?

Also, do you think we should show the drawer for bookmarked apps? Presumably, the user has already seen the info and trusts the app when they pinned it. @clemoon wdyt?

**Comment by clemoon** [comment]
Good suggestion! I would be in favour of not showing the drawer for custom apps. Looping in @liliiaorlenko for her design lenses

**Comment by clemoon** [comment]
Regarding the app links on the dashboard, I would be in favour of directing the user to the safe apps page with the drawer opened as they click on the app but again I think this needs a UX design consideration from Lila

**Comment by katspaugh** [comment]
Just to be clear, I was talking about pined apps, not custom apps, although the same applies to custom apps as well.

**Comment by clemoon** [comment]
From my pov the drawer should be removed for custom apps (because to tags/info have to be provided) however it makes sense to keep the drawer for bookmarked apps. We should keep reinforcing the t&cs (make them clickable via the drawer) in the user flow, as it's a legal requirement from management

**Comment by yagopv** [comment]
> Regarding the app links on the dashboard, I would be in favour of directing the user to the safe apps page with the drawer opened as they click on the app but again I think this needs a UX design consideration from Lila

I think should be better to open the drawer in the Dashboard instead redirecting. When the user click there on the "Open App" button then redirect

**Comment by katspaugh** [comment]
@yagopv if you make the drawer a "global" component, please keep in mind we'll likely reuse the same drawer for the tx flow (@liliiaorlenko is working on a new tx flow design). So you might want to abstract the drawer itself as part of the PageLayout.

**Comment by liliiaorlenko** [comment]
1. Should the drawer open also in the dashboard view?
Yes, it should. I want to promote this opening of the drawer to bring more conciseness of app use. If later users will find drawer been to much we can maybe think of adapting it. 
2. Should we show the drawer on custom apps?
I think we can keep it without drawer, maybe when we can collect more data about custom apps we can implement it, but not now.

**Comment by yagopv** [comment]
So,
- Show in Dashboard (open the drawer in the dashboard imo, @clemoon  proposed to redirect to the list and open there but i'm not very convinced, not sure what others think)
- Show for app list and bookmarked
- Don't show for Custom apps

@katspaugh about the global component ... as the drawer is from material and part of the [component itself](https://github.com/safe-global/web-core/blob/57c5c519fdc07546fa0e9dc691886b417f232357/src/components/new-safe-apps/SafeAppPreviewDrawer/SafeAppPreviewDrawer.tsx#L33) i think is not necessary to abstract it and add to the page layout. My plan is to add a hook for managing it and use both the hook and the component where necessary
