### ISSUE TITLE
[EIP-1271] Move link on the article to the top as on the design

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1430]
## Bug description
 Move the link on the article to the top as on the design
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Go to the messages tab when there is at least one message
Current result: there is no possibility to read the article as the link on the article can be seen only on the empty Messages tab

## Expected result
Could we implement it according to the design?
## Screenshots
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/338622/209122856-d3a0590f-4157-4dc4-bdca-8feb1a504e5e.png">

**Comment by usame-algan** [comment]
I think it should also not say "Transactions" at the top when on the Messages page.

**Comment by katspaugh** [comment]
What should it say then? It's the name of the parent "page".

**Comment by DiogoSoaress** [comment]
Do I get it correctly that we want to show a tooltip and a link to a help center article? @liliiaorlenko If so, which tooltip should we display on the InfoIcon?

**Comment by katspaugh** [comment]
No tooltip, it's just a static icon. The article itself is the tooltip.
