### ISSUE TITLE
[EIP-1271] verify signature doesn't work for the 1.1.1 safes

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1431]
## Bug description
verify signature doesn't work for the 1.1.1 safes
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Create and confirm the message fully in the 1.1.1 safe
 2.  click Verify signature in the testDapp to check that 3rd party apps will be able to verify if the message is confirmed fully and can be used

Current result: Unable to fetch message is displayed.

## Expected result
The status of the message should be validated instead of the problem with fetching the message
## Screenshots
<img width="488" alt="image" src="https://user-images.githubusercontent.com/338622/209124957-845fb0b8-c0ce-4491-8296-240fc12b091c.png">

**Comment by liliya-soroka** [comment]
set up as minor , as most likely the 3rd party apps will use Goerli for the v1 integration. And it was possible to create only 1.3.0 safes on Goerli in the new interface.
But the issue should be checked for future real releases, as we have 1.1.1 safes on Ethereum on prod

**Comment by schmanu** [comment]
@liliya-soroka This should be fixed in our web-app but it still needs to fixed in the tx service.

I'm moving this issue into `Ready for QA` but to properly test it this needs to be fixed and merged: https://github.com/safe-global/safe-eth-py/issues/421

**Comment by DiogoSoaress** [comment]
Should we label it `blocked` or something alike? QA can't really test it without touching the code. cc @katspaugh
