### ISSUE TITLE
[EIP-1271] "Sign" is used instead of "Confirm" on the queued tab

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1435]
## Bug description
 "Sign" is used instead of "Confirm" on the queued tab
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Check tx details with buttons on Queued list in the Epic -1271
 Current result: Seems that the button implementation for the Messages tab also changed the button name on the queued list 
"Sign" is used instead of "Confirm"

## Expected result
Could we align here?
 Personal opinion: I prefer "Confirm," as the tx status is " awaiting your confirmation."

## Screenshots
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/338622/209139709-f4f912c2-f289-4c99-a80e-36e1a11d0bda.png">

**Comment by usame-algan** [comment]
I agree, lets rename it to Confirm to be in line with Transactions and the status message.

**Comment by schmanu** [comment]
@liliya-soroka: given how trivial this change is I skipped QA. It was also tested during review.

**Comment by SKYBITDev3** [comment]
A better word is "Accept" to prevent confusion with the blockchain transaction processing by miners or validators. I created an issue about this: https://github.com/safe-global/safe-contracts/issues/659
