### ISSUE TITLE
[EIP-1271] Dates don't match with the subsections in the list

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1447]
## Bug description
The list shows the messages created in a specific date. that date is not correct for a lot of messages

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: goerli
 - Env and safe: https://eip_1271--webcore.review-web-core.5afe.dev/gor:0x24F8542Da0C5f267c177a224270442C73804EE80/transactions/messages

## Steps to reproduce
 1. Visit the safe provided. Not every message is broken, so the issue is not consistent

## Expected result
The messages should be ordered in the date they were created

## Obtained result
Some messages have a creation 1 day more than the subsection they were put

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/209272097-5e85c0bd-a938-406d-bf1c-4f4d8ee37809.png)

**Comment by katspaugh** [comment]
Looks like it's the same as #539.

**Comment by katspaugh** [comment]
I suggest we close this as a duplicate, it's a backend bug anyway.

**Comment by schmanu** [comment]
I agree: Closing because the labels are provided by the tx service so it is not a frontend issue, plus there is a duplicate issue open.
