### ISSUE TITLE
[Safe Apps] Enable toggle pinning directly in search results

### ISSUE THREAD

**Issue by GollyTicker** [safe-global/web-core#1457]
## What is the feature about
In the `/apps` view, enable the user to pin an app they directly searched for.

As a user of the Gnosis Safe Web UI, I was trying to use RocketPool and a few other apps. I saw, that it's possible to pin apps - but I didn't understand, why I couldn't do that directly from the search. Instead I have to manually scrool down and pin the app myself to have it in the pinned section.

Currently, it looks like this:
![image](https://user-images.githubusercontent.com/4527862/209648896-65cd8b8d-2eed-4aef-abef-29335af233a0.png)
I think, it just makes sense to allow the user to directly pin what they searched for, because they will know, whether they'll use the app regularly and want to pin it.

## The list of requirements
* user can click on the pin toggle (top right of app card) in the search results in the say way as they can do it in the other apps sections
* the (un-)pinning of an app has the same effect like in other sections

## Designs/sketches
I would like to make it to this:
![image](https://user-images.githubusercontent.com/4527862/209649193-6819fa27-7e0c-4a99-ae12-2367cdb7cd2c.png)

## Links
I looked a little into the code and it seems like it just needs a `onPinApp={togglePin}` on [this line in the SafeAppList](https://github.com/safe-global/web-core/blob/6550a7e5cc1441bbab6993e973388b6955fc3dcd/src/components/safe-apps/SafeAppList.tsx#L77).

I've not tried or tested this out yet though. Are you okay with this minor improvement?

**Comment by katspaugh** [comment]
There was [a recent attempt to fix it](https://github.com/safe-global/web-core/pull/1388) in the same way as you suggest but it was discarded because custom apps (user-added apps) should not be bookmarkable as per the discussion there. Which is itself an arguable limitation, personally.

**Comment by GollyTicker** [comment]
Ah, thanks for the link. I had searched for related issues, but didn't think about searching in the closed ones :sweat_smile: 

Ok, I see the discussion. I don't know/understand enough about custom apps to comment this - but my understanding is, that it should ideally also be possible to pin them.

Shall this issue be kept open so that it can be considered with/after the Safe Apps re-design?

**Comment by katspaugh** [comment]
Sure. You could also fix it as you suggested but exclude custom apps, should be easy.

**Comment by GollyTicker** [comment]
I actually meant including the custom apps. But I can make an attempt an implementation for only the default apps. (Have not react experience, but will try ^^.)

I think it's best if you ppl decide whether to include the custom app pins lateron or not.

**Comment by GollyTicker** [comment]
I am not sure I understand the expected behavior.

> custom apps (user-added apps) should not be bookmarkable as per the discussion there

If custom apps are not supposed to be pinned, then it looks to me that the current code does not satisfy this requirement.  Custom apps can still be pinned in the "All Apps" section.

[The code indeed makes the pins appear for all app cards in the "All Apps" section.](https://github.com/safe-global/web-core/blob/dev/src/components/safe-apps/SafeAppList.tsx#L67) This is also what happens when I try to add a custom app card in a local dev setup:

![safe-react-custom-pin](https://user-images.githubusercontent.com/4527862/209697622-06509d5f-01c9-4ff6-bae5-a938fadc9960.gif)

As you can see, the pin is still visible for custom apps.

Note: I changed the code in [this function](https://github.com/safe-global/web-core/blob/dev/src/hooks/safe-apps/useRemoteSafeApps.ts#L31) to only return the "Curve" app as a pre-defined app. I did that, because I didn't have any valid custom app URL - so I used the $SAFE Claim App url as a fake custom app.

Hence, my question: If we make pins possible within the search, then why exclude the custom apps? They can be pinned in the "All Apps" section already. I think it's confusing, if custom apps are only pinnable in the all apps section, but not in the search - esepcially when pre-defined apps were to become always pinnable.

Additionally. Is there a reason why custom apps can only be removed in the custom apps section and not in the all apps section? Is that simply an oversight, because the [current implementation](https://github.com/safe-global/web-core/blob/dev/src/components/safe-apps/SafeAppList.tsx#L67) makes the decision on whether a delete button should be shown outside the `SafeAppList`? If a list contains both custom and pre-defined apps, then the [decision of whether to show the 'remove button'](https://github.com/safe-global/web-core/blob/dev/src/components/safe-apps/SafeAppsSection/CollapsibleSection.tsx#L59) needs to be a list-element-dependent argument (and not a constant `onDeleteApp`).

**Comment by dasanra** [comment]
We are currently working on a facelift for the Safe Apps list section. That is why we are not currently working to fix this specifically, as the UX flows will change after. All these minor bugs will be reviewed during that process to see how they match with the new UX

https://github.com/safe-global/web-core/issues/1443

**Comment by GollyTicker** [comment]
Allright. Then I'd keep this issue open until after the new UX has arrived. Thanks for the clarification.

**Comment by GollyTicker** [comment]
Cool, the new UI upgrade has this feature already implemented:
![image](https://user-images.githubusercontent.com/4527862/219499415-2707262d-d910-4ca1-bd8d-399fb9f2ece9.png)


Thanks!
