### ISSUE TITLE
[Send funds] The modal is missing the "Balance" amount

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1469]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet
 - Env: https://release_1_2_1--webcore.review-web-core.5afe.dev/

## Steps to reproduce
 1. Go to any safe with funds
 2. Open the "Send funds" modal

## Expected result
Balance amount displayed

## Obtained result
The balance amount is missing

## Screenshots
RC:
![image](https://user-images.githubusercontent.com/4503659/210100999-2fb47f59-3984-4dae-84ae-398b0ada5782.png)

Prod:
![image](https://user-images.githubusercontent.com/4503659/210102165-402a88d2-875d-43c1-9448-66e436dfecc4.png)

**Comment by katspaugh** [comment]
It was intentionally removed as per @lukasschor’s request. See https://github.com/safe-global/web-core/pull/1429

**Comment by francovenica** [comment]
Ah, missed it. Thanks for the clarification.
