### ISSUE TITLE
Tx stuck in "Submitting" if rejected in the wallet after a page reload

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1489]
* Open a fully signed tx
* Press Execute
* Do not approve or reject in the wallet
* Refresh the page
* Reject the execution in the wallet
* The tx is now infinitely "Submitting"

<img width="477" alt="Screenshot 2023-01-05 at 15 24 58" src="https://user-images.githubusercontent.com/381895/210802526-49618c58-8985-4b66-8498-836e59cf2a4a.png">

**Comment by katspaugh** [comment]
The cause of this bug is that there's no subscription to the transaction rejection event after a page reload.

One solution would be to not persist pending statuses or persist only for the session.

**Comment by DiogoSoaress** [comment]
> The cause of this bug is that there's no subscription to the transaction rejection event after a page reload.

I was thinking if dispatching the `TxEvent.EXECUTING` event for the pending txs upon initializing would re-subscribe to the transaction rejection. Do you think it could be an approach?

**Comment by iamacook** [comment]
> I was thinking if dispatching the `TxEvent.EXECUTING` event for the pending txs upon initializing would re-subscribe to the transaction rejection. Do you think it could be an approach?

We could alternatively not dispatch events before the SDK is called.

**Comment by katspaugh** [comment]
> re-subscribe to the transaction rejection

Yeah, I actually thought we had some tx monitor in place that would time out after a certain period.

**Comment by katspaugh** [comment]
> We could alternatively not dispatch events before the SDK is called.

How would that help? AFAIU, the SDK _is_ called, the wallet pops up but you just close the app/refresh the page.

**Comment by iamacook** [comment]
> How would that help? AFAIU, the SDK _is_ called, the wallet pops up but you just close the app/refresh the page.

We [dispatch the relevant `TxEvent` before the SDK is called in some places](https://github.com/safe-global/web-core/blob/dev/src/services/tx/tx-sender/dispatch.ts#L118-L123), which in turns saves the transaction as pending. The refresh prevents the "counter-event" from being dispatched upon rejection, hence never clearing the pending status.

> I actually thought we had some tx monitor in place that would time out after a certain period.

This should be investigated. The monitor [should kill pending transactions after 6.5 minutes](https://github.com/safe-global/web-core/blob/dev/src/services/tx/txMonitor.ts#L13).

**Comment by francovenica** [comment]
> This should be investigated. The monitor [should kill pending transactions after 6.5 minutes](https://github.com/safe-global/web-core/blob/dev/src/services/tx/txMonitor.ts#L13).

Can confirm that this is not working properly. I reproduced the issue in prod and a tx has been stuck in submitting for 1h now.
