### ISSUE TITLE
Update to react-hook-form > v7.41.1 breaks form validation

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1501]
## Bug description

Updating the react-hook-form package to > v7.41.1 causes issues with form validation in create safe and other forms.

Possibly a misconfiguration on our side. Adjusting validation props in `AddressBookInput` and removing `register` in `NameInput` fixes the issue.

## Steps to reproduce
 1. Update react-hook-form to > v7.41.1
 2. Go to safe creation
 3. Press Next
 4. Observe that the Next button is disabled until the user focuses an input field

## Screenshots
<img width="806" alt="Screenshot 2023-01-09 at 13 24 30" src="https://user-images.githubusercontent.com/5880855/211307321-5193f3d5-112e-4782-9c99-31d9296af5cc.png">

**Comment by katspaugh** [comment]
The red outline appears even with the current downgraded RHF.

**Comment by katspaugh** [comment]
Since the bug was resolved, I'm closing this but here's a tech debt ticket to upgrade RHF eventually: #1592.
