### ISSUE TITLE
"Deselect all" unhides tokens on all networks 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1513]
## Bug description
Deselect all unhides tokens on all networks 
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet/Goerli

##Steps:
1. open safe on Ethereum and hide tokens
2. Go to Goerli   and hide Goerli eth
3. Open hidden tokens for the Goerli safe and use deselect all ->save
4. come back to the ethereum safe => all tokens are displayed for the safe step 1

## Expected result
Unhide tokens on one network should not unhide a token on another network

**Comment by schmanu** [comment]
this should be fixed by https://github.com/safe-global/web-core/pull/1508/commits/cb5a1afab7174c28b92e24dc04fda63022f30b22
