### ISSUE TITLE
[EIP-1271] Normalize EIP 712 messages before submitting to services

### ISSUE THREAD

**Issue by schmanu** [safe-global/web-core#1517]
## Bug description
Currently we submit the EIP 712 messages as we retrieve them to our tx service.
We should first create the payload using`_TypedDataCoder.getPayload` to verify and normalize the message.

From the ethers docs:
>Returns the standard payload used by various JSON-RPC eth_signTypedData* calls.
>All domain values and entries in value are normalized and the types are verified.

## Steps to reproduce
 1. Send a typed data message without EIP712 domain type or without `primaryType` set.
 2. It will be accepted and signed by the interface but then fails when submitted to the tx service.

## Expected result
It shoud either fail before signing, when we verify the message in our interface or go through without errors.

## Obtained result
It fails when submitted to tx services.

**Comment by nlordell** [comment]
Also worth noting that the on-chain EIP-712 signing works without `primaryType` set - so this would be important in order to keep the same SDK API for both on-chain and off-chain signing.

**Comment by liliya-soroka** [comment]
Verified in the epic PR
