### ISSUE TITLE
[Switching account] Tx signing with trezor and ledger

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1519]
## Bug description
Switching to physical devices and trying to execute a tx shows an error initializing the SDK and an error in the send funds modal "unknown account"
I only encounter this issue when changing from any wallet to the trezor or ledger wallet

Note: This issue doens't happen if you connect with the ledger/trezor manually (no switching) and try to sign a tx

## Environment
 - Browser: Chrome
 - Wallet: Ledger NanoS, Trezor One
 - Chain: Goerli
 - Env: https://release_1_3_0--webcore.review-web-core.5afe.dev/gor:0x24F8542Da0C5f267c177a224270442C73804EE80/home
 - RC: #1508 

## Steps to reproduce
 1. Go to app and connect with Trezor or ledger
 2. Connect now with a MM account
 3. Switch back to the ledger/Trezor device
 4. Try to execute a send funds tx

## Expected result
Execution of the tx normally

## Obtained result
Sdk initialization error and "unknown account" error in the send funds modal

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/211681834-4d24a0f3-46fc-4902-b4bb-33c2c5d614b9.png)

**Comment by katspaugh** [comment]
Both signing and executing worked for me with Ledger and MM connected simultaneously.

**Comment by iamacook** [comment]
I just tested this with my Ledger and it signed and executed fine. However, I encountered some other issues.

1. I signed a queued transaction first with my Ledger then switched to MM. Attempting to sign or sign and execute it showed this error:

![image](https://user-images.githubusercontent.com/20442784/211769337-31a6a225-3c61-4e66-bc52-8937ff46d7a4.png)

2. If disconnecting the Ledger and trying to reconnect it, it's not possible to select the network to scan for accounts:

![switch accounts back](https://user-images.githubusercontent.com/20442784/211769581-22dadbc8-2fed-45a4-b5c6-b8584e068855.gif)

**Comment by katspaugh** [comment]
I couldn't reproduce the v4 issue.

**Comment by iamacook** [comment]
> I couldn't reproduce the v4 issue.

It seems to have resolved itself.

I've just tested the above on my Trezor and it works as well.

**Comment by katspaugh** [comment]
@francovenica please try again, maybe it was a temporary RPC issue.

**Comment by francovenica** [comment]
I'm still getting the issue. It happens to me when I have both trezor and ledger connect and switch back and forth

**Comment by francovenica** [comment]
It seems it happens if the user that switches to a phyisical device that was previously connected does not pick network and address from the modal when switching in.
