### ISSUE TITLE
[Tx details] the icon in UI is misplaced

### ISSUE THREAD

**Issue by liliiaorlenko** [safe-global/web-core#1524]
## Bug description

<img width="655" alt="Screenshot 2023-01-11 at 13 53 50" src="https://user-images.githubusercontent.com/94694401/211811607-b8ed1eb3-aed1-44f7-881e-562034de964f.png">

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to Transactions
 2. Expand the details of some tx

## Expected result
The icon should be centered.

**Comment by abheektripathy** [comment]
would like to contribute on this.

**Comment by katspaugh** [comment]
Sounds great, @abheektripathy! Let us know if you need any help on this. 👍

**Comment by abheektripathy** [comment]
hey @katspaugh the icon is technically centered inline to the parent element, should i put the button component(TransferActions) inside the EthHashInfo component itself? 
<img width="657" alt="Screenshot 2023-01-19 at 1 26 13 PM" src="https://user-images.githubusercontent.com/90976669/213385915-718bc752-df87-4235-b917-654c9e07a116.png">

**Comment by abheektripathy** [comment]
hi @katspaugh i have been stuck on an error, from quite a while. Im passing `txinfo` as prop into the `EthHashInfo` component and then passing the `TransferActions` inside it.


Should i open a pr so you can review my code changes?
Any insights would be helpful.



the issue seems to be this.
![Screenshot 2023-01-20 at 11 37 59 AM](https://user-images.githubusercontent.com/90976669/213630238-6783f04e-eb2a-4323-b287-940639f53fad.png)

**Comment by iamacook** [comment]
@abheektripathy, If you open a PR, we will happily review your code.

> Im passing `txinfo` as prop into the `EthHashInfo` component and then passing the `TransferActions` inside it.

It's better if you pass `TransferActions` as `children` to `EthHashInfo`:

```ts
<EthHashInfo>
  <TransferActions />
</EthHashInfo>
```

> the issue seems to be this.
> ![Screenshot 2023-01-20 at 11 37 59 AM](https://user-images.githubusercontent.com/90976669/213630238-6783f04e-eb2a-4323-b287-940639f53fad.png)

`txInfo` looks to be `undefined`. [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) could help.
