### ISSUE TITLE
Show pending actions for added Safes in sidebar 

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/web-core#1534]
## What is the feature about

Having multiple Safes makes it hard to know where my attention is required. 

Around 53% of users have more than 1 Safe added. More than 37% of users have more than 2 Safes added. And around 25% have more than 5 Safes. 

As a user, I would like to see no. of queued transactions (1-10, >10) for all added Safes in the sidebar on request. 

In the best case I can do so considering my connected wallet: 
As a user, I would like to see no. of queued transactions (1-10, >10) where the signature of the connected wallet is missing or that need to be executed for all added Safes in the sidebar on request. 

## The list of requirements

- Calculate and display number of loaded Safe pending transactions on Safe list sidebar opening
- Calculate and display number of transaction confirmations your connected account can sign

## Designs/sketches

https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2152%3A61404&t=ZKu0Dt7eBwMnnwYe-0

**Comment by katspaugh** [comment]
This would require requesting the queue for each of the added Safes. Johannes suggests we do it on an explicit button press.
Need to align with backend wrt load.
