### ISSUE TITLE
failed to upgrade  to v1.3.0 

### ISSUE THREAD

**Issue by masayil** [safe-global/web-core#1535]
![image](https://user-images.githubusercontent.com/65291464/212232963-a14d2b8b-a714-4d92-9d8b-50bc9b92397e.png)
My gnosis safe  can work at v1.2.1. but cannot get right 'MultiSend contract address' at v1.3.0
MultiSend address:
https://explorer.bas.metaapesgame.com/address/0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761

**Comment by masayil** [comment]
web-core:
https://gnosis-safe.metaapesgame.com/

**Comment by katspaugh** [comment]
Looks like you're talking about a forked version of the UI on a not-officially supported chain.
In that case please reach out for help in our dev channel on Discord, this is not really a bug in the UI.
Cheers!

**Comment by masayil** [comment]
ok

**Comment by masayil** [comment]
@katspaugh
