### ISSUE TITLE
Transactions that "will fail" cannot be submitted

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1536]
See https://github.com/5afe/safe-support/issues/115

**Comment by iamacook** [comment]
> It looks like this occurs any time the transaction will fail. In the image below, the `Timelock::executeTransaction:Transaction hasn't been queued` in the console is expected. However, I would expect to still be able to submit this tx, since I know the execution will work when the final multisig signer gets around to sign it (just like in the old UI).
> 
> Of note, this Safe is v1.1.1, which might be causing this?
> 
> <img alt="safeErr" width="1715" src="https://user-images.githubusercontent.com/9441295/214489734-6bee4f3e-3d14-4170-9968-dadb36affd5b.png">

Briefly looking through the code, it seems as though the transaction is not being created by the SDK.

The lack of transaction presence [blocks the submit button](https://github.com/safe-global/web-core/blob/dev/src/components/tx/SignOrExecuteForm/index.tsx#L209) and the simulation block [shows a `Skeleton` when no transaction is present](https://github.com/safe-global/web-core/blob/dev/src/components/tx/TxSimulation/index.tsx#L95-L101).

The transaction should be created in the [`ReviewSafeAppsTx` modal](https://github.com/safe-global/web-core/blob/dev/src/components/safe-apps/SafeAppsTxModal/ReviewSafeAppsTx.tsx#L38) by [`createMultiSendCallOnlyTx`](https://github.com/safe-global/web-core/blob/dev/src/services/tx/tx-sender/create.ts#L88). Looking through the SDK, I can only find [one instance](https://github.com/safe-global/safe-core-sdk/blob/main/packages/safe-core-sdk/src/utils/transactions/utils.ts#L53) where it [could be throwing](https://github.com/safe-global/safe-core-sdk/blob/main/packages/safe-core-sdk/src/utils/transactions/gas.ts#L79). Maybe that's the source of the issue? This is somewhat of an assumption though.
