### ISSUE TITLE
Merge `initialState` and persisted state on hydration

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1551]
## Bug description

We currently overwrite slice `initialState` on [persisted state hydration](https://github.com/safe-global/web-core/blob/dev/src/store/storeHydrator.tsx#L25). This means [it overwrites everything](https://github.com/safe-global/web-core/blob/dev/src/store/index.ts#L63-L68), e.g. potential new keys.:

```ts
const initialState = {
  test: {
    foo: true,
    bar: false
  }
};
```

```ts
const persistedState = "Hello world!";
```

```ts
const state = "Hello world!";
```

In the above example, accesing `state.test.foo` would crash the app.

## Steps to reproduce

Create a new nested object in the `settingsSlice` `intialState` and attempt to access it via a selector *without* optional chaining.

## Expected result

The app doesn't crash and it shows the value, with the value populated in the state.

## Obtained result

The app crashes and the value is not present in the state.

## Potential solution

Instead of shallow spreading the persisted state over the entire store, it would be better to leverage [`merge` from `lodash`](https://lodash.com/docs/4.17.15#merge) in the `action.payload`.

```ts
this.store.dispatch({
  type: HYDRATE_ACTION,
  payload: merge({}, initialState, getPersistedState()),
})
```

**Comment by liliya-soroka** [comment]
Verified
