### ISSUE TITLE
Creating a safe on Arbitrum instantly times out

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1558]
## Bug description

The create safe transaction on Arbitrum results in an error that is not handled. The flow defaults to a Timeout error instead. The transaction still gets executed though.

## Steps to reproduce
 1. Go to Safe
 2. Create a new safe on Arbitrum
 3. Observe an instant timeout error

## Screenshots
<img width="1339" alt="Screenshot 2023-01-18 at 15 13 23" src="https://user-images.githubusercontent.com/5880855/213235582-25d30507-cdbb-47a7-99fb-0b3acfba707d.png">

**Comment by usame-algan** [comment]
@francovenica can you check if this is reproducible?

**Comment by liliya-soroka** [comment]
works on production 
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/338622/213388502-115ffddf-6be7-4f86-8cdd-4a966ebd89b7.png">

and on dev
<img width="990" alt="image" src="https://user-images.githubusercontent.com/338622/213388780-f5aa0f9d-1531-4e44-a51a-55dffadfe46b.png">
