### ISSUE TITLE
Unable to select certain NFTs when trying to send assets 

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1560]
Crosspost from https://github.com/5afe/safe-support/issues/119

### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

User trying to transfer NFTs but is unable to select the BoredApeYachtClub (without space), whichever user chooses it automatically selects the bored ape yacht club (with space) which is a malicious NFT, same behavior for the otherdeed NFT. Other NFTs are working fine.

Issue only occurs in the new interface (tested different browsers). Old interface works fine. 

https://user-images.githubusercontent.com/114049668/213335195-3e9870b8-efd2-43e3-bc82-9cb307d12166.mov

safe address: eth:0xd99e9aeC0a12a710420f27Cf13fcD248F8470b00

### Date and time this happened or you first noticed this issue

19-01-2023

### Network

Ethereum Mainnet

### Safe Address

0xd99e9aeC0a12a710420f27Cf13fcD248F8470b00

### Token Type

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by katspaugh** [comment]
This'll be fixed in #1479.
