### ISSUE TITLE
Always propose Safe Apps transactions

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1563]
## Bug description

Safe Apps transactions propose [an "origin" that includes metadata about the app](https://github.com/safe-global/web-core/blob/dev/src/utils/transactions.ts#L181-L195). This metadata is used to display details of the app in the transaction list.

A [recent optimisation](https://github.com/safe-global/web-core/pull/1298/files#diff-70addbd231a36637989f9e3732bed07149598277eee9498f69fb69dc12463ffcR161-R169) removed proposal of immediately executed transactions, thus also the proposal of Safe App metadata.

We should *always propose* Safe App transactions, including their metadata.

## Steps to reproduce
 1. Create and immediately execute a Safe App transaction.
 2. After being successfully indexed, observe no Safe App metadata in the transaction list for the transaction.

## Expected result

The transaction is shown with the [associated metadata of the Safe App](https://github.com/safe-global/web-core/blob/dev/src/hooks/useTransactionType.ts#L80).

## Obtained result

The transaction is shown as a standard transaction.

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/213418850-3c7f7863-a265-4189-b798-838b03b0bed3.png)

## Links

- [Discussion](https://5afe.slack.com/archives/C03DAGWJCR5/p1674118750610329)

**Comment by katspaugh** [comment]
As discussed with Uxio, we'll restore the previous system where immediately executed txs will be always proposed.
