### ISSUE TITLE
8 wallets are displayed by default when no selected wallets in the config service

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1596]
8 wallets are displayed by default when no selected wallets in the config service
1. add new network to the config service 
2. all wallets should be off for the network
3.  switch to the new network on web-core
4. click connect 
Current result: 

![Image](https://user-images.githubusercontent.com/338622/214608456-1e7a2ad6-16eb-4654-a71c-acc9039338f5.png)

**Comment by katspaugh** [comment]
@liliya-soroka I've temporarily disabled all wallets on Celo to test a fix I made.
