### ISSUE TITLE
Fix to one size all modals

### ISSUE THREAD

**Issue by liliiaorlenko** [safe-global/web-core#1611]
## Bug description

Align modals "Replace owner" and "Add new owner" to the size of other modals like "Edit owner name"

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Settings
 2. Manage safe owners

## Screenshots
<img width="1718" alt="Screenshot 2023-01-30 at 11 39 15" src="https://user-images.githubusercontent.com/94694401/215455316-3e46db13-a846-4fdb-a9c4-4a54b7edc784.png">
<img width="1724" alt="Screenshot 2023-01-30 at 11 39 22" src="https://user-images.githubusercontent.com/94694401/215455327-938c91d3-9fe1-4db5-9054-2a8950296c50.png">
<img width="1721" alt="Screenshot 2023-01-30 at 11 41 25" src="https://user-images.githubusercontent.com/94694401/215455333-25711d9b-02c8-4890-a176-914620761ceb.png">
<img width="1721" alt="Screenshot 2023-01-30 at 11 41 43" src="https://user-images.githubusercontent.com/94694401/215455336-efceaee5-7015-4cbb-86e3-493db8121508.png">

**Comment by katspaugh** [comment]
Usame: each screen in the same modal flow has the same width. E.g. replace owner has a sidebar layout which makes all other modal in that flow wide.

**Comment by katspaugh** [comment]
I suggest we close this since the modals will be completely redesigned soon.
