### ISSUE TITLE
Change error message: "The Safe SDK could not be initialised..." 

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/web-core#1632]
## Bug description

Currently we display the error message "The Safe SDK could not be initialized. Please try connecting the wallet again."

## Environment

Occurred on
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Polygon
 

## Steps to reproduce
not clear

## Expected result

Provide better user guidance. If not clearer instructions can be found, use the following message:

"Please try connecting your wallet again."

## Screenshots
<img width="379" alt="image (6)" src="https://user-images.githubusercontent.com/93598450/216269873-97fd5e81-d25e-42a3-a2f4-012d5f6f642f.png">

**Comment by iamacook** [comment]
> On optimism, we have this error together with the next errors in the console, and the MM is disconnected from our UI. Should we also research how to fix unexpected disconnect? :
> 
> ![Image](https://user-images.githubusercontent.com/338622/216969987-f347dc77-5e97-40d5-9715-9c2ab3490c68.png)

That error looks related to some form of rate limiting outside our control: "Your IP has exceeded its requests per second capacity. To increase your rate limits, please sign up for a free Alchemy account [...]".

Are you using Alchemy as your RPC provider? [It is not used in our configs](https://safe-client.safe.global/v1/chains/10).

In any case, I would suggest filing a separate issue as this one is related to notification clarification.

**Comment by liliya-soroka** [comment]
@johannesmoormann , we will show: 'Problem connecting to the RPC provider. Please try connecting your wallet again.'. Is it ok ?
