### ISSUE TITLE
[NFT page] Show image previews

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1633]
The OpenSea metadata format is now [supported by our backend](https://github.com/safe-global/safe-transaction-service/pull/1305/files), so many more image previews will be available.

However, the images are quite large so we shouldn't render them directly in the table.

We can show an image preview on hover or click, tho. Design needed.

**Comment by liliiaorlenko** [comment]
> The OpenSea metadata format is now [supported by our backend](https://github.com/safe-global/safe-transaction-service/pull/1305/files), so many more image previews will be available.
> 
> However, the images are quite large so we shouldn't render them directly in the table.
> 
> We can show an image preview on hover or click, tho. Design needed.

I updated [designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=3637%3A74678&t=69Y2M3Ep0IeLdqea-1) according this update:
- if preview is visible on a click, design for the modal full screen https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=4104%3A79658&t=yKNEKDMuH5GEyWdY-1
- rules for the view of NFT https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=4104%3A80451&t=yKNEKDMuH5GEyWdY-1:
if we can show NFT: icon of the NFT is black and locates us to the modal preview
if we cant show NFT: we show tooltip that recommend user to visit origin website of the NFT

**Comment by katspaugh** [comment]
@liliiaorlenko cool, thanks!

The icon on the left is currently the _collection_ logo though. It’s only a diamond when there’s no logo. E.g. ENS domains do have a logo.

**Comment by katspaugh** [comment]
That said, ENS seems to be the only logo we actually display, so we could as well just make it a static diamond icon.
