### ISSUE TITLE
[Hide tokens] Checkbox clicked instead of the Save button

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1636]
## Bug description
When you have the hide token menu open, the menu gets fixed as you scroll down. The issue is that when you click the save button and is over the checkboxes in the list, you click the checkbox instead of the save button

## Environment
 - Browser: Chrome
 - Wallet: any
 - Chain: any
 - Env: Prod

## Steps to reproduce
 1. Go to This safe that has a bunch of tokens in ETH eth:0x8675B754342754A30A2AeF474D114d8460bca19b
 2. Open the menu to hide tokens
 3. Scroll down a bit so the save button overlaps a checkbox
 4. Click the Save button where the checkbox in the row behind it would be

## Expected result
You click the save button

## Obtained result
You click the checkbox instead

## Screenshots
![save button](https://user-images.githubusercontent.com/4503659/216343447-206a200c-6317-45ff-a2c8-c69033a325b9.gif)

**Comment by katspaugh** [comment]
The button needs a stopPropagation probably.

**Comment by liliya-soroka** [comment]
Verified
