### ISSUE TITLE
Send NFT is missing on the "replace tx" form 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1647]
## Bug description
Send NFT is missing on the "replace tx" form 
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: any

## Steps to reproduce
 1. Go to queued list
 2. click replace tx icon
 Current result: 
<img width="772" alt="image" src="https://user-images.githubusercontent.com/338622/217246217-b1cd11e1-6948-4b63-b8be-7517bf73a895.png">

## Expected result
add the option to replace tx with send NFT tx

**Comment by katspaugh** [comment]
It's missing intentionally because that button just opens the NFTs page, and to replace a tx, you need to pass a nonce. The replacement flow would be too disconnected.
