### ISSUE TITLE
Optimism

### ISSUE THREAD

**Issue by shunkakinoki** [safe-global/web-core#1659]
## Bug description

Tx doesn't work on optimism!
(Prob a bug with tenderly

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to

**Comment by katspaugh** [comment]
@safe-global/safe-qa can you check? Might've been a temporary RPC issue.

**Comment by katspaugh** [comment]
Thanks, @liliya-soroka!
Since it seems to be related to the RPC settings in the user wallet, which is not something we control, I'm going to close this issue.
Thanks for flagging @shunkakinoki.
