### ISSUE TITLE
Can't set up gaslimit manually in case of "This transaction will most likely fail"

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1661]
## Bug description
Can't set up gaslimit manually in case of "This transaction will most likely fail"
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce 
 1. Try to execute the tx that will fail with GS013 ( I have tried to send NFT from my test safe to 1.0.0 safe )
 2. open advanced estimation parameter
 Current result: Gas limit - Cannot estimate. 

3. edit gas limit and save edited data 
4. reopen estimation parameters
Current result: Gas limit - Cannot estimate. 

## Expected result
It should be possible to enter gaslimit manually 
## Screenshots
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/338622/218341104-bfbca31a-b055-438f-9177-09f396659f6b.png">

**Comment by katspaugh** [comment]
To devs: make sure it's possible to change the gas limit in any case. Write tests for this.

**Comment by mahdit8** [comment]
But still I face same issue @liliya-soroka 

<img width="608" alt="Screen Shot 2023-03-22 at 18 16 28" src="https://user-images.githubusercontent.com/75958335/226882947-26acd1c8-a230-4af5-a3a5-9f23e1568721.png">
