### ISSUE TITLE
UI displaying wrong transaction nonce when quickly executing transactions

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/web-core#1667]
## Bug description

When executing a transaction (tested with a 1/n Safe) and quickly creating a new transaction, the UI will show the nonce of the previously executed transaction but submit the transaction with the correct nonce (or at least a nonce higher then is being displayed). 

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet and Görli

## Steps to reproduce
 
With a 1/n Safe create and execute multiple transactions and observe the nonce being displayed in the UI. 

## Expected result

The submitted and signed nonce should always match the displayed nonce in the UI.  

## Obtained result

see video

https://user-images.githubusercontent.com/93598450/218501568-b099bce8-6b67-48bf-8921-343a3563bebf.mp4
<img width="1174" alt="image (7)" src="https://user-images.githubusercontent.com/93598450/218501713-4e50e0f4-13c4-4514-8bd8-98effafa631f.png">

**Comment by mikhailxyz** [comment]
> The contract doesn’t care what nonce a tx has in the data, it always [just increments its own nonce](https://github.com/safe-global/safe-contracts/blob/main/contracts/Safe.sol#L141-L142) on each execution.

This is only true for pre-validated signatures (aka msg.sender based ones). For all other types nonce is a part of the signed transaction hash and a different nonce on-chain would result in a failed transaction authorization.

More context:
https://github.com/safe-global/safe-contracts/issues/187

**Comment by katspaugh** [comment]
Thanks for the correction, makes sense. 👍
