### ISSUE TITLE
Skeleton loaders around Safe

### ISSUE THREAD

**Issue by liliiaorlenko** [safe-global/web-core#1671]
## Bug description
Pages that don't have a skeleton:
- Assets (Tokens and NFTs)
- Address Book (Not sure)
- Apps
- Settings (Not sure)

@liliya-soroka if you can help with further investigation of states thats needed skeletons
If design is needed let me know, but the skeletons thats already exist is great for the reference.

**Comment by katspaugh** [comment]
@francovenica I've already merged the changes to dev (to fix the tests), so please test it directly on dev.

**Comment by liliiaorlenko** [comment]
I found that we missing skeleton also for tx preview :(

**Comment by katspaugh** [comment]
@francovenica this was reopened due to Lilia's comment above, and it's now fixed, so please take another look. Not a priority tho.
