### ISSUE TITLE
Button to "unfurl" all actions

### ISSUE THREAD

**Issue by bh2smith** [safe-global/web-core#1687]
## What is the feature about
Some large multi-send transactions consists of several (e.g. [59](https://app.safe.global/eth:0xA03be496e67Ec29bC62F01a428683D7F9c204930/transactions/queue)) transfers which need to be validated by safe owners before signing. Currently, this means they need to click to "unfurl" several actions one by one in order to verify.

## The list of requirements

Single button to "Expand All" actions

## Designs/sketches

Before:
![Screenshot 2023-02-21 at 15 20 13](https://user-images.githubusercontent.com/11778116/220370519-59dea37d-13eb-4968-948f-b6ee085137cb.png)

Click this "Button":

<img width="220" alt="Screenshot 2023-02-21 at 15 20 20" src="https://user-images.githubusercontent.com/11778116/220370564-17e636e1-4b8e-463d-ad75-4f587ac44a4b.png">

After:
![Screenshot 2023-02-21 at 15 21 11](https://user-images.githubusercontent.com/11778116/220370672-052806be-fbfc-45e7-86c8-387f3810efe4.png)

Originally posted [here](https://cowservices.slack.com/archives/C03DVQREAH0/p1676988311577459) in slack.

**Comment by katspaugh** [comment]
@liliiaorlenko please propose a design for this, cheers

**Comment by liliiaorlenko** [comment]
I created version [one](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=4427%3A82927&t=AcEHAjVrPNcgs2mo-1) and version [two](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=4427%3A84247&t=AcEHAjVrPNcgs2mo-1)
whats your preferred one?

**Comment by katspaugh** [comment]
Voting for this one:

<img width="682" alt="Screenshot 2023-02-28 at 13 16 59" src="https://user-images.githubusercontent.com/381895/221852110-79ff29b5-615e-4867-a960-12b0d8d78026.png">

**Comment by blacktieaccountant** [comment]
@iamacook , any estimate to have this button deployed?
