### ISSUE TITLE
[Mobile] Hamburger menu not working on welcome page

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1695]
On mobile, tapping on the hamburger menu on the Welcome page does nothing (because there’s no sidebar).
We should probably hide the button.
![B4D4D73F-07E8-46D1-A308-9C56F720F785](https://user-images.githubusercontent.com/381895/220991124-75ad2bc2-7851-46e6-b240-c6e0423f3229.jpeg)

**Comment by alindsharmasimply** [comment]
Hey @katspaugh , kindly check out my PR.
