### ISSUE TITLE
Spending limits: Table header is displayed when no records

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1703]
## Bug description
Table header is displayed when no records
## Environment
 - Browser: FF
 - Wallet: MetaMask
 - Chain: Ethereum mainnet/Goerli

## Steps to reproduce
 1. Go to the spending limits page in the safe without the spending limits module enabled or to the Base network ( no support for spending limits)

## Expected result
Make sure that the table is displayed only when it's not empty
## Screenshots
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/338622/221552810-2300ade1-01f0-4035-bd4e-6cc7ff9925d3.png">
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/338622/221553079-3c4f3bb8-f7c9-4039-bbc6-ca60cac523a0.png">

**Comment by oraliahdz** [comment]
HI, I would like to help. Is this still available?

**Comment by katspaugh** [comment]
@oraliahdz hey, absolutely! Go ahead 🤩

**Comment by oraliahdz** [comment]
Perfect. Just to clarify, What needs to appear then? That section in blank? A message? Something else?

**Comment by katspaugh** [comment]
Nothing, just this top part should remain:
<img width="783" alt="Screenshot 2023-02-28 at 20 10 53" src="https://user-images.githubusercontent.com/381895/221955092-2a2b35af-1740-474f-81a1-c6776883caf6.png">
