### ISSUE TITLE
Better indication of why certain actions are disabled

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1708]
In some situations we disable/hide transaction-related buttons:

* when the wallet isn't connected
* when the wallet is on the wrong chain
* when the wallet isn't an owner/spending limit beneficiary

## Problems
1. In some places in the UI, we just disable transaction buttons, in some we hide them completely. This makes the UI inconsistent.
2. There's no explanation why those buttons are disabled.
3. There's no way for the user to know how to fix that.

## The list of affected buttons
* The New transaction button in the sidebar
* Add owner button (currently hidden completely!)
* The final Submit button in the tx review modal
* The Send button in the Assets
* Possibly many more buttons throughout the app

## Solution
1. Always show all actionable buttons but disable them if the action cannot be performed.
2. Show a tooltip near the button explaining why
3. ~In the tooltip, show a button "Connect wallet" or "Switch chain"~

<img width="377" alt="Screenshot 2023-02-28 at 08 52 51" src="https://user-images.githubusercontent.com/381895/221823960-02b5e956-8ed2-467a-93b2-5110a68bd4ab.png">

**Comment by katspaugh** [comment]
@liliiaorlenko please propose a design for this (doesn't have to be the exact solution described).

**Comment by liliiaorlenko** [comment]
3. In the tooltip, show a button "Connect wallet" or "Switch chain" - as a designer Im against this solution.
