### ISSUE TITLE
Unable to execute transaction and let it fail

### ISSUE THREAD

**Issue by GopherJ** [safe-global/web-core#1752]
## What is the feature about

sometimes we just want the transaction to fail so that we can execute the next one and we dont need to send reject transaction. seems now this is not possible or am I missing something

**Comment by iamacook** [comment]
Your suggestion makes sense – it would be an easy way to get rid of a "stuck" transaction. However, our backend will only remove a transaction from the queue if it’s successfully executed. So while it’s possible to try and execute a failing transaction from the UI, it won’t work on the backend.

You can either create a replacement transaction or set the nonce of a new transaction to be the same as the one to-be-replaced.
