### ISSUE TITLE
Bug in URL encoding for Safe Apps

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1780]
We're seeing a lot of page views like this in GA:

<img width="380" alt="Screenshot 2023-03-17 at 15 42 00" src="https://user-images.githubusercontent.com/381895/225937095-e7721588-1c04-4501-8983-453e2b09f1bc.png">

The appUrl parameter is present twice, with the wrong encoding and no encoding.

**Comment by GermaVinsmoke** [comment]
Any steps for reproducing this? Because the encoding is there.

Also, is there a place to communicate instead of Github issues 😅

**Comment by katspaugh** [comment]
I've no idea tbh, it shouldn't be happening, looking at the code.

**Comment by katspaugh** [comment]
I've checked Analytics for the last 30 days, and the double appUrl is gone.

All the Safe App urls are still encoded like `%3FappUrl` but that seems to be a GA thing, so it's fine.
<img width="484" alt="Screenshot 2023-04-26 at 15 49 43" src="https://user-images.githubusercontent.com/381895/234579785-bd6e70c4-32bc-40ae-a6c5-8a0ab63408fb.png">
