### ISSUE TITLE
Unhandled exception in useOnboard

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#1783]
`getAddress` needs to be wrapped in a try-catch and the error properly handled.

<img width="883" alt="Screenshot 2023-03-20 at 08 06 50" src="https://user-images.githubusercontent.com/381895/226270016-927141d1-0daa-4640-b49e-753daac92aaf.png">

https://gnosis.sentry.io/issues/3897265821/?project=6769196&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d

**Comment by deepaksing** [comment]
Hi @katspaugh, i would like to work on this issue can you assign this to me.

**Comment by katspaugh** [comment]
Sure thing, thank you @deepaksing!
