### ISSUE TITLE
The relayer counter shows the wrong values sometimes.

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1791]
The relayer counter shows the wrong values sometimes. Here I should always see 4 out of 5, but sometimes it shows 5 out of 5.
![relayer counter](https://user-images.githubusercontent.com/4503659/226700392-6e38a3fb-f199-4416-bdec-09ae454615ed.gif)

_Originally posted by @francovenica in https://github.com/safe-global/web-core/issues/1776#issuecomment-1478358721_

**Comment by liliya-soroka** [comment]
Same for me https://drive.google.com/file/d/1R2DVV3msp_Ad5xPTy1IjIr9kTmOxHYIi/view?usp=sharing

**Comment by liliya-soroka** [comment]
Relay back-end side issue
