### ISSUE TITLE
Incorrect `safeTxGas` used in Safe App transaction simulation

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1795]
## Bug description

https://github.com/5afe/safe-support/issues/160

When simulating a Thales transaction via WC, our simulation is not using the correct `safeTxGas`.

This is likely related to the fact that the App [can propose the `safeTxGas` via WC](https://github.com/safe-global/safe-apps-sdk/blob/main/packages/safe-apps-provider/src/provider.ts#L81-L98) and it is proposing a high value. We should check that the standard gas limit is higher than that of the `safeTxGas`, e.g. get the gas limit of the last block and check that it is higher than the proposed `safeTxGas`.

`safeTxGas` values are also not good. If possible, we should look into subtracting ~10% of it here (see discussion thread).

## Environment
 - Browser: Chrome
 - Wallet: MetaMask controlling nested Safe via WC
 - Chain: Optimism

## Steps to reproduce

Simulate a Thales transaction on Optimism and observe it failing.

## Expected result

Simulation succeeds.

## Obtained result

Simulation fails because of high `safeTxGas`.

## Links

- [Discussion](https://5afe.slack.com/archives/C03DAGWJCR5/p1679487311386139)
- [Safe simulation](https://dashboard.tenderly.co/public/safe/safe-apps/simulator/ee587701-1e38-4751-a74d-2e6c685a64c8)
- [Manual simulation](https://dashboard.tenderly.co/KirilA/project/simulator/883d4c95-2439-4f9e-ac39-063fb252a878)

**Comment by rmeissner** [comment]
this is about `safeTxGas` right? not `baseGas`. .... Setting `safeTxGas` changes the behavior and should only be done if we are sure that this is the expected behavior.

**Comment by DiogoSoaress** [comment]
I've observed that the the dApp is passing the same `safeTxGas` and `gasLimit` (15M) in the failing simulations.

Would we like to show
![Screenshot 2023-04-26 at 15 56 29](https://user-images.githubusercontent.com/32431609/234599657-f3216c7b-629a-4016-9905-7d19fc02e587.png)

for this invalid transaction data or is this an error that we can provide a more informative error modal?
