### ISSUE TITLE
Signing a message from a DApp crashes the app

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1799]
## Bug description

When triggering a message signing from within a DApp (e.g. Snapshot), the app crashes, throwing the following error:

![image](https://user-images.githubusercontent.com/20442784/227313895-356a48b6-e0cb-49d7-b287-dbacd6ecc199.png)

## Environment
 - DApp: Monerium, Snapshot (probably any dapp that requests a signature)
 - Chain: Ethereum/Gnosis Chain

## Steps to reproduce
 1. Open Snapshot.org
 2. Connect a Safe via WalletConnect
 3. Edit Profile on Snapshot
 4. Safe crashes 

## Expected result

The signing modal opens and you are able to sign a message.

## Obtained result

The app crashes.

**Comment by katspaugh** [comment]
I can't reproduce it on snapshot.org anymore. Maybe there were issues on the WC bridge?
In any case, the app shouldn't crash. We should catch and handle that error properly.

**Comment by iamacook** [comment]
> I can't reproduce it on snapshot.org anymore. Maybe there were issues on the WC bridge? In any case, the app shouldn't crash. We should catch and handle that error properly.

Neither can I.

I'd suggest we tackle this immediately after https://github.com/safe-global/web-core/pull/1746 is merged as that touches everything `EthersAdapter` related.
