### ISSUE TITLE
Older Safes prevent hardware wallets from signing

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1813]
## Bug description

Safes version <1.1.0 do not support `eth_sign`. On older Safes we therefore [only sign with `eth_signTypedData`](https://github.com/safe-global/web-core/blob/dev/src/services/tx/tx-sender/sdk.ts#L44-L46). Hardware wallets, however, predominantly only support `eth_sign`.

When a hardware wallet is connected to a Safe version <1.1.0 and you try to sign, we [throw and error on signing](https://github.com/safe-global/web-core/blob/dev/src/services/tx/tx-sender/sdk.ts#L65-L67) saying that the signing method is not supported and provide no further details. We should provide more information and perhaps disable signing entirely.

## Environment
 - Browser: any
 - Wallet: Ledger/Trezor Model T
 - Chain: any

## Steps to reproduce
 1. Connect a hardware wallet and attempt to queue a transaction.
 2. Observe the unclear error message.

## Expected result
Possible options: (tbd)

- Notification is shown.
- "New transaction" button is disabled.
- Information box is shown on transaction review.
- Submit button is disabled.

## Obtained result
Error is thrown with no clear explanation.

## Screenshots
![image](https://user-images.githubusercontent.com/20442784/228207099-1899cef2-6634-4d34-b02b-205d05ee690a.png)

**Comment by usame-algan** [comment]
Can we use `personal_sign` in those cases?
