### ISSUE TITLE
Directly executing txs is blocked while txs are pending

### ISSUE THREAD

**Issue by schmanu** [safe-global/web-core#1817]
## Bug description
When a transaction in any Safe is pending, it is impossible to directly execute transactions in other 1/n Safes.
It only works from the confirmation modal in the queue.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Görli

## Steps to reproduce
 1. Execute a transaction in Safe A
 2. While the transaction is indexing, open a new 1/n Safe B with an empty queue
 3. In Safe B try to create a tx and witness that there is no Execute transaction option given. You can only sign and propose the tx.

## Expected result
We can only sign transactions in other 1/n Safes.

## Obtained result
In other Safes without pending txs, we should be able to directly execute transactions if it's the next nonce.

## Screenshots
Check that the next nonce is the same as in the created tx and the Safe is 1/3
![Screenshot 2023-03-28 at 18 50 05](https://user-images.githubusercontent.com/2670790/228311806-b523a722-f78e-4987-a957-6b8f3df3f268.png)
![Screenshot 2023-03-28 at 18 50 22](https://user-images.githubusercontent.com/2670790/228311801-22368f98-d85c-49a6-a9ab-16f0a9d76857.png)

**Comment by katspaugh** [comment]
It's not a bug, this limitation was deliberately added to avoid duplicate nonces. See #1676.
