### ISSUE TITLE
Unhandled error when executing transaction in queue

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1829]
## Bug description

There is an unhandled error when executing a transaction from the queue sometimes.

Sentry: https://gnosis.sentry.io/issues/3979496225/events/edb6e22d75db48009523c3ad6880c6cd/?project=6769196

## Environment
 - Browser: any
 - Wallet: any
 - Chain: any

## Steps to reproduce
 1. Go to a safe
 2. Queue up a transaction
 3. Navigate to the queue
 4. Execute the transaction

## Expected result

- The transaction disappears after being processed

## Obtained result

- An unhandled error occurs

## Screenshots

<img width="989" alt="Screenshot 2023-03-31 at 12 00 33" src="https://user-images.githubusercontent.com/5880855/229148407-b8a1927a-31ca-4fcf-8fe3-c588a100b0bd.png">

**Comment by JagoFigueroa** [comment]
Looks good to me, I've been signing and executing a bunch of transactions from the queue on different L2s and the error did not pop up for me once.

Cheers!
