### ISSUE TITLE
Switching network doesn't work with MM wallet

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1853]
## Bug description
When clicking the button on the topbar to change your wallet to the current network the MM popUp shows up twice, and never changes the network
This happens when trying to change to Optimism, Arbitrum, aurora, BNB, avalanche.
For polygon it even ask me to add the network to the MM every time (even tho the Polygon network is already in the MM extension)

No problem changing to Goerli or ETH

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Most of them
 - Env: Prod

## Steps to reproduce
 1. Go to the app in ETH
 2. Connect with MM chrome extension
 3. Try to change to Arbitrum, Optimism, Avalanche
 4. The MM popUp ask you to change the network

## Expected result
After clicking Accept, the network should change

## Obtained result
After clicking accept, the popUp shows again, clicking accept again shows an error in the middle of the screen.

## Screenshots
![change network](https://user-images.githubusercontent.com/4503659/230682851-334adb27-7ee8-4df6-9b91-a23fe9f37f13.gif)

**Comment by iamacook** [comment]
We're going to keep an eye on the MM thread and close this accordingly.

**Comment by usame-algan** [comment]
It seems to have been resolved. Tested with switching between multiple networks on our current prod app.
