### ISSUE TITLE
TX execution fails with default execution parameters on Gnosis Chain

### ISSUE THREAD

**Issue by biafra23** [safe-global/web-core#1859]
## Bug description
Tx fails with default parameters on Gnosis Chain

## Environment
 - Browser: Brave
 - Wallet: MetaMask
 - Chain: Gnosis Chain mainnet
 - Safe contract version: 1.1.1

## Steps to reproduce
 1. Click "New transaction" (Safe on Gnosis chain with a threshold of 1)
 2. Select sending Safe as Recipient address
 3. Select xdai as asset
 4. Enter 1 into the amount field
 5. Hit Next
 6. Observe warning: 
```
This transaction will most likely fail. To save gas costs, avoid creating the transaction.
missing revert data in call exception; Transaction reverted without a reason string
``` 
7. Click "Estimate Fee"
8. Click "Edit"
9. safeTxGas is 84920
10. Gas limit is: 71886
11. Click "Confirm"
12. Clcik "Submit"
 
## Expected result
Tx is excuted
## Obtained result
Tx fails

## How to fix (as a user)
Change safeTxGas to 0
or
increase Gas limit by factor 10

**Comment by iamacook** [comment]
I'm going to close this as it's related to underestimation. I've created [an issue](https://github.com/NethermindEth/nethermind/issues/5637) on Nethermind's board.
