### ISSUE TITLE
Transaction executed correctly but missing from transaction history

### ISSUE THREAD

**Issue by zupermann** [safe-global/web-core#1860]
## Bug description
Transaction executed correctly but missing from the transaction history.
Transaction with nonce 13 is missing for this safe: https://app.safe.global/transactions/history?safe=matic:0xA5CB3a8EBce37192f8768333D6aB3a6f3964EA9F

Next transaction went through fine and got the correct nonce (14).

A 2/4 safe was used, and on 2nd confirmation it was also executed.
Transaction batch was initiated by TX Builder, and signed with metamask. For 2nd confirmation and execution, a Ledger was used.

The transaction with nonce 13 that was executed correctly but did not appear in history: https://polygonscan.com/tx/0xfce4b0d333348d1e8dd5baa52e986b77688318fb7d14a420e6ade77fc874dc2a

Additional info: Transaction 13 remained a long time (about 10 minutes) in the queue before disappearing altogether. 

## Environment
 - Browser: Chrome
 - Wallet: MetaMask, Ledger
 - Chain: Polygon mainnet

## Steps to reproduce
 1. Create transaction batch with tx builder 
 2. Confirm it with metamask
 3. 2nd confirmation and execution with a Ledger.

## Expected result
1. Transaction is seen in the queue for a while and then in the transaction history

## Obtained result
1. Transaction was seen in the queue but never reached history.

## Screenshots
![Screenshot 2023-04-13 at 08 42 10](https://user-images.githubusercontent.com/4907747/231664261-bfbcb101-2299-4b13-927c-a821ced8333c.png)

**Comment by usame-algan** [comment]
Seems like an indexing issue. I can see the transaction with nonce 13 in the history now.
