### ISSUE TITLE
Dashboard widgets do not align correctly

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1863]
## Bug description

The "Connect & transact" widgets do not align correctly with the "New in Safe" on large and medium resolutions.

## Steps to reproduce

Open the Safe on Gnosis Chain. Observe the "Connect & transact" widgets not stacking on larger resolutions and not spanning the height of the "New in Safe" on medium resolutions,

## Expected result

The "Connect & transact" widgets always stack, spanning the height of the "New in Safe" widget when it is present.

## Obtained result

The "Connect & transact" widgets do not always stack/span the height of the "New in Safe" widget.

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/231756593-96a89be5-9c62-4ace-b9b1-2c5f5e1e690b.png)

![image](https://user-images.githubusercontent.com/20442784/231756652-924ad425-f6c7-4162-973d-3535ff866dac.png)

**Comment by AnshulKahar2729** [comment]
> > @iamacook let me know if I can solve the issue. If deepaksing won't.
> 
> @AnshulKahar2729, we have a couple [other good first issues](https://github.com/safe-global/web-core/labels/good%20first%20issue) open as well.

@iamacook let me know if I can help you.
