### ISSUE TITLE
USDC Balance to Value calculation is wrong

### ISSUE THREAD

**Issue by 0xSage** [safe-global/web-core#1872]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Gnosis Chain

## Steps to reproduce
 1. Send some USDC into Safe
 2. Go to Assets > Tokens tab
 3. See Balance vs Value column

## Expected result
Value is correct

## Obtained result
Value shown is 100x smaller than actual monetary value.

## Screenshots
![Screenshot 2023-04-17 at 7 39 00 PM](https://user-images.githubusercontent.com/69952136/232474055-07d62979-2cd6-4a92-87fd-ee8ab1e95a40.png)

**Comment by katspaugh** [comment]
It's not a frontend bug. We get these prices from the transaction service which in turn gets them from a 3rd-party service and sometimes it comes as 0.
@Uxio0 please correct me if I'm wrong.

**Comment by JagoFigueroa** [comment]
Issue was on the backend side and should be resolved now 😄 

Cheers!
