### ISSUE TITLE
[Relaying] Allow execution via connected wallet as an alternative when relaying is enabled

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/web-core#1894]
## What is the feature about
For networks with relaying enabled, the user should have the choice to execute via their connected wallet as an alternative. 

## The list of requirements

Relay as default
Execution via connected wallet as a visible alternative 

- [x] design @liliiaorlenko 
- [x] frontend implementation 
  - [x] Transaction modal
  - [x] Batch execution
  - [x] Safe creation

**Comment by liliiaorlenko** [comment]
Proposed design : https://www.figma.com/file/M3J3IJ5YFxRKaT95F2uBAt/Relaying?node-id=2794%3A39235&t=2xEfWGpsqY8BETtZ-1

**Comment by liliiaorlenko** [comment]
Execution method for safe creation: [design](https://www.figma.com/file/M3J3IJ5YFxRKaT95F2uBAt/Relaying?node-id=1559%3A34683&t=j4XDqVyEYvjGk785-1)
