### ISSUE TITLE
Refreshing on Assets page of a safe shows 404

### ISSUE THREAD

**Issue by captain-woof** [safe-global/web-core#1900]
## Bug description

On Assets page of a Safe, reloading the page adds a trailing slash to `/balances`, and shows up 404.

This does not show up on the Next.js dev server, but only on a static build.

## Environment
 - Browser: Chrome
 - Wallet: Any
 - Chain: Any chain

## Steps to reproduce
 1. Select any safe
 2. Go to Assets page. Notice the page works correctly.
 3. Reload the page. Now it shows 404.

## Expected result

Reloading the page should show up the Assets page as usual, with no added trailing slash to pathname

## Obtained result

404 page comes up.

**Comment by katspaugh** [comment]
What HTTP server are you using?
