### ISSUE TITLE
Support changes to Eth balance shown in Assets due to Ethereum staking withdrawals 

### ISSUE THREAD

**Issue by arbora** [safe-global/web-core#1903]
## Bug description
When a Safe multisig is set as the withdrawal address for an Ethereum validator, and a withdrawal is sent to the address, the Safe frontend (and presumably backend) does not seem to register the withdrawal, because withdrawals are not normal transactions and do not trigger any smart contract code or events. As a result, the Ether balance shown in the Safe UI does not update, even though the actual Ether balance of the multisig smart contract is (in some cases significantly) higher after the withdrawal.

Note that this is not a smart contract bug as far as I am aware, just a display bug in the Safe frontend.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Create an Ethereum staking validator, with the withdrawal address set to a Safe multisig contract
 2. Run the validator until it has accumulated some staking rewards
 3. Wait for the next withdrawal (will occur within a few days)
 4. Observe the Ether balance in the Safe address on Etherscan versus in the Safe frontend. Etherscan shows the correct amount, accounting for the withdrawal; the Safe frontend does not.

## Expected result
The Safe frontend (Balances/Assets page) should show the full Ether balance for the multisig, including both incoming Eth from normal transactions, as well as Eth received via withdrawals.

## Obtained result
The Ether balance show in the Safe frontend does not update after withdrawals are received, only after normal transactions that change the Ether balance of the multisig.

**Comment by arbora** [comment]
Apparently it just takes upwards of 45 minutes for withdrawals to be noticed and applied to Safe balances in the frontend, but it does seem to happen. Closing this issue (although maybe with a small request to make withdrawals change the shown balance in a Safe as rapidly as normal transactions do, i.e. within seconds or a few minutes tops!)

**Comment by katspaugh** [comment]
FYI @Safe-infra
