### ISSUE TITLE
safe_token.svg image size too big

### ISSUE THREAD

**Issue by GermaVinsmoke** [safe-global/web-core#1908]
## Bug description
svg file present in `src/components/common/SafeTokenWidget/safe_token.svg` is 54KB in size which is too big for a SVG. Reason is base64 png image inside the SVG file.

Present in navbar, it loads up every time. So, it'll be better to get a proper SVG file.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Expected result
Image size should be atleast 10KB in worst case scenario.

**Comment by katspaugh** [comment]
Great catch!
@liliiaorlenko could you provide an actual vector image for the Safe token?

**Comment by GermaVinsmoke** [comment]
I can replace it after getting the icon 😂

**Comment by liliiaorlenko** [comment]
![Safe_Logos_Token](https://user-images.githubusercontent.com/94694401/234605176-872a355a-6d4a-42f0-912e-f4624e32333b.svg)

**Comment by katspaugh** [comment]
@liliiaorlenko this icon is still just a bitmap wrapped into an svg. I think it's the gradient. Can you somehow export it as a pure vector image?

**Comment by liliiaorlenko** [comment]
![Safe_Logos_Token](https://user-images.githubusercontent.com/94694401/234802156-19c6b19a-2dca-46de-97dd-34d5856473c5.svg)
pls check this version, I tried to fix all layers to vector
