### ISSUE TITLE
Add security recommendations steps

### ISSUE THREAD

**Issue by dasanra** [safe-global/web-core#455]
## What is the feature about
Add the security recommendations steps to the new codebase

## The list of requirements

- [ ] Add all the security steps and checks

## Links
Old epic ticket https://github.com/safe-global/safe-react/issues/3945
Current epic https://github.com/safe-global/safe-react/issues/4044

**Comment by clemoon** [comment]
Syncing with Lila on this tomorrow afternoon so we might be able to get a fix sooner than expected

**Comment by clemoon** [comment]
@dasanra I've pushed the sync with Lila to tomorrow same time because I'd like to better understand the solution space that's been explored by the team, the technical considerations, and the current solution. I'm setting us up on a quick sync on this for tomorrow morning

**Comment by clemoon** [comment]
The different flows are:
        - First time you open a safe app: 5 clicks steps 
        - Then if you open the same app: nothing
        - Any other new app: 2 steps 
        - Custom app: 5 click steps each time

**Comment by clemoon** [comment]
After consultation with Lila, we need to close this issue for now and won't be looking at implementing a fix before the next cycle. This issue needs research and design before solid alternatives can be suggested. I've added this as an epic in the newly created safe apps backlog: https://www.notion.so/gnosis-safe/Redesign-of-the-security-steps-6c27372778964be48cea9bdaed0f75c7 - please close the issue, thank you!
