### ISSUE TITLE
Switch network not loading last seen safe

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#458]
## Bug description
When switching to a network it should take the user to the last visited safe of that network

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Any
 - Env: https://web-core.pages.dev/

## Steps to reproduce
 1. Load a safe in any network (rinkeby for example)
 2. Go to any other network, you are taken to the welcome page
 3. Switch back to rinkeby

## Expected result
It takes you to the "last seen" safe

## Obtained result
It keeps you in the welcome page

**Comment by katspaugh** [comment]
For context: we made an exception for the Welcome/Add Safe/Create Safe pages. They just switch the network while remaining on the same page. This was done for this switcher:
<img width="697" alt="Screenshot 2022-08-31 at 08 11 01" src="https://user-images.githubusercontent.com/381895/187606423-8faa1eca-5624-4f5f-acc4-f9e228e8e8ae.png">
Perhaps we should make the header select always navigate to `/` (and thus trigger the last Safe redirect), and adjust the Add Safe/Create Safe network select.
