### ISSUE TITLE
Analytics tracking

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#471]
## Bug description
This list was taken from the Analytics > events folder in the web core repo and are the tracks that have issues (missing or dubious).
Anything in the code that had a comment of "not implemented" in any way was skipped

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby
 - Env: https://web-core.pages.dev/

## Steps to reproduce
 1. Make sure to have the Analytics checkbox marked in preferences

## Obtained result
Address book:
Import (button above the table)
Import (The submit button once you loaded)
These 2 buttons have the same track event, except from the button on top of the table has a undefined eventLabel and the other actually has it defined.

- Assets:
Differing Tokens: I couldn't find this trigger, is it sent in another action? there is no comment in the code

- Create safe form:
The "Continue" and "Back" button trigger the same event as the modals like "Send funds" with the "Category: 'modals'". Is this correct? This is also for the Load safe form

The Create safe, once is done, trigger 3 events that look exaclty the same
![image](https://user-images.githubusercontent.com/4503659/187234115-64b9c313-4e7a-45e1-a795-af1043d632a4.png)

"Get Started" and "go to safe" are events in the code, but they are not used because after the safe is created it goes straight to the safe, there is no more "get started" button

- Modals:
* [x] Opening the "Adv parameters" display triggers an event, so I assume there should be one for Transaction Details".  (fixed in #474)

- Overview:
Home (the top left icon) triggers the "Welcome home" event, but that logo no longer takes to the welcome page at all.

- Settings:
In the code there is "Owner" and "Treshold" events that don't have a trigger because there is no longer "owners" and "treshold" in the submenu button in settings.

**Comment by katspaugh** [comment]
Todo:
* [ ] pass `category: 'create-safe'` in useTxStepper in Safe Creation.

**Comment by francovenica** [comment]
In the ticket 474 I see that a new track event for "edit adv params" was added, but there was already an event for that button
![image](https://user-images.githubusercontent.com/4503659/187948926-539cb81e-e7b9-4569-96cd-82960d01cd4e.png)

**Comment by francovenica** [comment]
The Icon on the top write still shows the event "Welcome home", even tho that button doesn't take to the welcome page (actually it kinda work like a refresh page for the safe you are currently on). Are we going to leave the event anyways?

**Comment by francovenica** [comment]
LGTM
The edit button only triggers 1 event "Edit advanced param" and the logo on the top left corner doesn't trigger the "Welcome home" event anymore
