### ISSUE TITLE
Filter - "Incomming > From" is returning earlier values than the one set in the input

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#475]
## Bug description
I filter by "incomming" and only set the "From" field. Is expected that every tx shown is from that date forward. 
Is bringing dates from before that date

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby
 - Env: https://web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions/history

## Steps to reproduce
 1. Go to this safe https://web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions/history
 2. Filter in the history tab by "incomming" and in the From input set the Aug 30 2022

## Expected result
Show only tx of receive tokens from Aug 30 2022 forward

## Obtained result
I see results from 2021

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/187551769-78ba047b-8ea2-431d-975e-7e05168714d7.png)

**Comment by iamacook** [comment]
Can you please share the `GET` request as well? I am unable to replicate this:

![image](https://user-images.githubusercontent.com/20442784/187608529-f6e47f39-2e89-406a-b5a4-db3e55c6f907.png)

Looks like I need to adjust the UTC string conversion a bit:
`incoming-transfers/?safe=rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808&execution_date__gte=2022-08-29T22:00:00.000Z`

**Comment by francovenica** [comment]
Works fine, no more results from last year
