### ISSUE TITLE
[e2e tests]Update selectors for web-core tests

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#478]
- [ ]  Update selectors @Franco Venica
    - [x]  Dashboard
    - [x]  Address book
    - [x]  Load safe
    - [x]  Balances
    - [ ]  Tx history

 EDITED:
    ~~- [ ]  Tx modal~~ This one requires walletConnect
    - [ ] Landing (Test the cookie banner)

**Comment by francovenica** [comment]
I keep having issues with the CI. I'll keep doing test, make the work locally at least and then push them even if the CI fails the checks.

All the test are their own files and do not mess with anything else so even if some time is pass there should be no problem merging them in the main branch (they should not create conflicts)

**Comment by francovenica** [comment]
Balances is almost done. There is one step that currently requires a regex. We are debating if we can change to not use it
