### ISSUE TITLE
Remove owner in dark mode - The pink color is too bright

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#484]
## Bug description
For the dark mode the pink is too bright, and the text should be black.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Any

## Steps to reproduce
 1. Go to any safe with at least 2 owners
 2. Try to remove one and reach the review step

## Expected result
I'd let the designer to decide, but Id tone down the pink and make the text black

## Obtained result
![image](https://user-images.githubusercontent.com/4503659/187663835-f17fb58d-043a-4398-8398-c5d6db52c06a.png)

For comparison this is how it looks in the regular mode:
![image](https://user-images.githubusercontent.com/4503659/187663891-3f107cb1-58c2-4188-ac83-015add41f40c.png)

**Comment by iamacook** [comment]
I'll include this in my theming PR https://github.com/safe-global/web-core/pull/483.

**Comment by katspaugh** [comment]
It now looks like this, which I think is quite legible:

<img width="1018" alt="Screenshot 2022-09-22 at 11 20 42" src="https://user-images.githubusercontent.com/381895/191709511-4cff2d94-144f-4784-b887-73277798f943.png">

@francovenica should we close this?
