### ISSUE TITLE
Filter - Date sets 1 day earlier

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#499]
## Bug description
Setting a date in the From or To input will show as 1 day earlier after filtering.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
 1. Go to any safe, history tab
 2. Set the From or To field (or both) to any date, like 20/8/2022 and filter
 3. Open the filter again and see the dates saved

## Expected result
The dates are the ones that you filtered before

## Obtained result
Both dates are 1 day earlier, in this case it would be 19/8/2022
Note that the filter works fine (it will search taking in account the date used for filter, 20/8/2022 in this case). the issue is just the date it shows after filtering

## Screenshots
![date](https://user-images.githubusercontent.com/4503659/188032898-cababd6a-2b35-4504-b669-380178a35840.gif)

**Comment by iamacook** [comment]
This is timezone related.

**Comment by francovenica** [comment]
Looks good. The day remeains the same after aplying the filter.
Tried in a few timezones and it works fine.
