### ISSUE TITLE
Filter - "To" field filters out results on that same day

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#500]
## Bug description
The From field, if you set a date and there is a tx in that date it will show it in the results, but the To field will ignore them

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
 1. Go to this safe https://web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions
 2. Filter by Incomming From 1/8/2022 and To 24/8/2022. Tx on the 23rd and 19th should show up
 3. Now filter by 23/8/2022. The tx on the 23rd is not shown
 4. Try again with 19/8/2022. Now the tx on the 19th is not shown

## Expected result
The To should also include results from that day, the same as the From field is doing.

## Screenshots
![same day](https://user-images.githubusercontent.com/4503659/188033786-b020fcc3-8d0b-4943-81db-0b49c0518e12.gif)

**Comment by iamacook** [comment]
As with https://github.com/safe-global/web-core/issues/499, this is timezone related.

**Comment by francovenica** [comment]
Looks good. Tried a few dates for incoming/outgoing tx setting the "To" field on the date the tx were created and they all showed fine in the table.
