### ISSUE TITLE
Filter - Outgoing > Amount filter only searches for native network token

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#501]
## Bug description
NOTE: This issue was already present in safe-react. I'll report it again just for the record

Issue: When searching for outgoing > amount, the only results will search for the native network token (ETH for rinkeby, GNO fro gnosis...)

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions (rinkeby)
 2. Search for Outgoing > Amount  = 1

## Expected result
The results are only tx in ETH

## Obtained result
Results should also include the other tokens (in this safe in particular there are DAI and BAT tx with a 1)

**Comment by iamacook** [comment]
The linked Safe does not contain any transasfers matching the desired filter results.

This Safe does and returns an outgoing DAI transaction (nonce 284): [filtered results here](https://web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions/history?type=Outgoing&value=1000000000000000000).

**Comment by usame-algan** [comment]
In the Outgoing filter screen, we can add "(only ETH)" or something similar next to the Amount label

**Comment by francovenica** [comment]
LGTM, the message showing that only the main token of the network can be filtered is there.

Hopefully someday we can search for any token.
