### ISSUE TITLE
Wallet connect: can not sign if the wallet is connected via WC

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#503]
The same issue for the wallets connected via WC:
Steps:
1. open Metamask on the mobile device
2. connect Metamask to the safe via WC
3. try to sign tx
Current result: The error appears, and signing is not possible 

![Image](https://user-images.githubusercontent.com/338622/188088318-1dc2e58a-5548-4e74-b3dd-9f8004e16c9d.png)

**Comment by francovenica** [comment]
Even after the merge I still have the same issue
![image](https://user-images.githubusercontent.com/4503659/191701534-b62f0925-85d2-4c45-a1f1-32f2744c40f7.png)

**Comment by francovenica** [comment]
Tx can be signed using the WC connection with the MM phone app.
