### ISSUE TITLE
Batch transactions - Clicking the button crashes the page

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#508]
## Bug description
Just clicking the button crashes the page. 
Tried with new safes and old safes, with 1/x and 2/x policies, so it seems is any safe

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to a safe you own
 2. Create 2 tx that can be executed
 3. Have them fully sign
 4. Click the "Batch transaction" button

## Expected result
A modal pops up with the tx listed

## Obtained result
The page crashes imediately. It shows an error of "Invalid safe version"

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/188357272-94a6ef49-160d-4df4-b8a1-de2f8337fd45.png)

**Comment by iamacook** [comment]
I am unable to replicate this on 1.1.1-1.3.0 Safes. Can you provide Safes that throw (with signed transactions to test)?

## 1.1.1
![batch 1 1 1](https://user-images.githubusercontent.com/20442784/188384360-5affe3fe-7a85-4ecf-a694-a4391d8bace3.gif)

## 1.3.0
![batch 1 3 0](https://user-images.githubusercontent.com/20442784/188384391-2357ba7c-c70d-4d73-bf74-f5b12ae539fc.gif)

**Comment by francovenica** [comment]
It seems this issue was affecting safes 1.3.0+L2. I've checked a safe in rinkeby that has that version and a safe in GNO, both worked fine
Tested in safes 1.1.1 and 1.3.0 as well and it works fine as well.
