### ISSUE TITLE
Support Trezor on Multiple Chains

### ISSUE THREAD

**Issue by decanus** [safe-global/web-core#510]
## What is the feature about

Right now the UI only allows connecting to a hardware wallet directly when interacting with the Ethereum Main Chain. It should allow this on all chains however.

## The list of requirements

When changing to another chain, Trezor is still natively integrated.

**Comment by iamacook** [comment]
Thanks for submitting the issue, @decanus. The current wallet-chain support matches that of [safe-react](https://github.com/safe-global/safe-react). However, if you want to connect a hardware wallet that isn't natively supported in the UI, you can connect it via MetaMask.

Please be aware that this repo is still very much in development and not yet publicly announced.

**Comment by johannesmoormann** [comment]
@decanus atm all hands on getting this (web-core) project live to replace the currently used https://github.com/safe-global/safe-react project but once this is done (around the end of September), we will have capacity again.

**Comment by katspaugh** [comment]
Let's test both Ledger and Trezor on L2 chains and enable them if possible.

**Comment by francovenica** [comment]
Tried Trezor and Ledger in stg having CGW enabled.

I tried regular tx like Owner adding/removing and the Tx builder with test contracts. Those worked fine

Trying to execute a safe creation already throws an error of Tx underpriced. It seems to be a Polygon [issue](https://github.com/ethers-io/ethers.js/issues/2828)
This happens with both Trezor and Ledger. It does not happen with MM
![image](https://user-images.githubusercontent.com/4503659/212686431-085acbb7-cf48-41f7-9feb-fdebce1e64f9.png)

**Comment by francovenica** [comment]
GNO chain. 
I was only able to use it with Trezor One
Ledger nanoS doesn't have the gnosis app to install, so onboard js cannot fetch the accounts, so I can't use a ledger for this

It works with issues:

During safe creation, if you go too fast and click the "next" button in step 4 before the estimation ends you get an error. This estimation usually takes 1 or 2 secons, so not likely to happen very often
![image](https://user-images.githubusercontent.com/4503659/212786474-f078acee-3184-4bba-90a4-ba651ea6e049.png)

When I tried to delete an owner I got this error after confirming&Executing (a 1/1 safe). The error was shown in the modal an as a notification, but after 15 secs or so the modal closed itself and the tx actually executed (the owner was removed)
![image](https://user-images.githubusercontent.com/4503659/212786571-9a976e44-ec07-4c10-8b42-daf4d6969686.png)

**Comment by katspaugh** [comment]
Turned off Ledger on GC, kept Trezor.

**Comment by francovenica** [comment]
For Avalanche: TL:DR; leave trezor enabled, disable ledger
Using a Trezor One and Ledger Nano S

Trezor works fine. I was able to create a safe and sign tx on-chain and off-chain with no issues

With ledger it doesn't work. I was only able to to sign on-chain tx. Off-chain tx and safe creation is not possible with my device
Safe creation: 
![image](https://user-images.githubusercontent.com/4503659/212946940-6cb38bc7-bdb7-4cba-9979-6fd0c769cf06.png)

Signing off-chain tx:
![image](https://user-images.githubusercontent.com/4503659/212947049-fea7cc5b-1d88-4dda-9f35-b4a410d6bb6a.png)

**Comment by francovenica** [comment]
For Binance:
Tested with a Trezor One and a Ledger nano S

It works fine with both devices. Safe creation, on chain tx and off chain tx

**Comment by francovenica** [comment]
Tested in Arbitrum and Optimism.
For both networks Ledger is not available, so ledger must remain disabled
For both of the Trezor works just fine, keep that one enabled

We decided with the team that these networks are the ones we will check for these phyisical devices.
QA done
