### ISSUE TITLE
Safes 1.0.0 - pages crashes when trying to update the version

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#522]
## Bug description
Just clicking on the Update button makes the page crash and says the 1.0.0 is not a valid version

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to a safe 1.0.0
 2. Click the upgrade button

## Expected result
The popUp to review the tx shows up

## Obtained result
Page crashes

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/188875941-a2c8a5b9-a88d-4e4e-b6c1-50a129fcdb27.png)

**Comment by iamacook** [comment]
This error is thrown [when retrieving the contract instance via the Core SDK](https://github.com/safe-global/web-core/blob/main/src/services/contracts/safeContracts.ts#L23-L25). We have to check the version is supported as the Core SDK doesn't support <1.1.1 Safes. We will have to retrieve the contract instances outside of the Core SDK.

**Comment by iamacook** [comment]
After a test implementation of legacy Safe upgrading https://github.com/safe-global/web-core/pull/526#issuecomment-1240610159, it's evident that we'd need to implement a seperate transaction creation/execution method for older Safes. It's certainly important to allow users to upgrade though so this is a likely necessity.

**Comment by katspaugh** [comment]
I'll close this in favor of #1188.
