### ISSUE TITLE
[ConnectToWeb] Change Safe logo

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/web-core#546]
## Overview
We'd like to change the logo that is received when connecting the web app because it is not visible in dark mode.

## Requirements
Please use the logo from here: https://github.com/safe-global/safe-ios/issues/2606#issuecomment-1242060393

## Links
https://github.com/safe-global/safe-ios/issues/2606

**Comment by katspaugh** [comment]
@safe-global/safe-ios I've changed the logo in the linked PR (you can test it on https://pairing-logo.web-core.pages.dev/), however, the mobile app seems to ignore the passed `icons` array and always picks the site's favicon instead.
