### ISSUE TITLE
Add Status browser 

### ISSUE THREAD

**Issue by michelleplur** [safe-global/web-core#575]
![image](https://user-images.githubusercontent.com/52613476/191117746-26a57001-5cc9-4010-b943-6da459657d34.png)

## What is the feature about
Add Status so I can connect from my Status Browser to the Safe.
Weird thing I found: when i select Metamask when in Status Browser, Safe knows im in Status  because it says so in the copy.
So we're halfway there in implementing :)

## The list of requirements
Add an icon or automatically detect I'm already in the Status browser.

## Designs/sketches
![image](https://user-images.githubusercontent.com/52613476/191117988-c14e575a-865b-463a-bb78-92e8cf665a6b.png)
Add Status logo here 

## Links
https://status.im/img/logo.svg

**Comment by katspaugh** [comment]
Hi @michelleplur, thanks for the request, love the details!

I've just tested it in the new version of the app (https://web-core.pages.dev – careful, dev version; will be released soon), and Status is detected and connects correctly there. You need to select the "Detected Wallet".

<img width="762" alt="Screenshot 2022-09-20 at 08 28 07" src="https://user-images.githubusercontent.com/381895/191183484-d7372033-9e40-4f2b-88e2-4918a954c293.png">

**Comment by michelleplur** [comment]
Awesome, I tried it and indeed it works <3

**Comment by katspaugh** [comment]
Yes, perhaps this can be reported on their side.
We're using [onboard](https://github.com/blocknative/web3-onboard) and its injected wallet module, if it's of any help.
