### ISSUE TITLE
Transaction History filtering for Incoming includes other transactions

### ISSUE THREAD

**Issue by salis** [safe-global/web-core#591]
## Bug description
When filtering the transaction history for only `Incoming` transactions the results include some `Outgoing` transactions.

## Environment
 - Browser: Chrome | Firefox
 - Wallet: MetaMask
 - Chain: Any

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0x28924a93f932ED76a72fadA69d23587FAe406912/transactions/history?type=Incoming (Rinkeby)

## Expected result
Transaction History list should filter to show only 5 incoming transactions

## Obtained result
Transaction History list filtering erroneously includes 8 outgoing transactions along with 5 incoming transactions

**Comment by usame-algan** [comment]
@salis the transactions are displayed as incoming and outgoing because they are sent to the same safe address.
