### ISSUE TITLE
Incorrect routing when adding a custom app -> https://gnosis-safe.io/app/

### ISSUE THREAD

**Issue by salis** [safe-global/web-core#594]
## Bug description
When a user of https://web-core.pages.dev/ clicks to Add a Custom Safe App they are routed to https://gnosis-safe.io/app/ 

## Environment
 - Browser: Chrome | Firefox
 - Wallet: MetaMask
 - Chain: Any

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0x28924a93f932ED76a72fadA69d23587FAe406912/apps
 2. Click Add custom app

## Expected result
The Add custom app modal should appear with a form to enter the App URL and App Name.

## Obtained result
The user is routed to a default hosted version of the app at https://gnosis-safe.io/app/rin:0x28924a93f932ED76a72fadA69d23587FAe406912/apps

**Comment by mikhailxyz** [comment]
We were not sure if we would manage to add custom apps support before the release, so currently, it routes to the old app. It seems like we're on track so we'll remove it in one of the future iterations

**Comment by JagoFigueroa** [comment]
It should be fixed after the latest changes are merged. Thanks for reporting this! ;)
