### ISSUE TITLE
Actions within tables not visible on smaller screens

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#614]
## Bug description

Although tables are scrollable/swipeable on smaller screens, important actions within the tables are not immediately visible to the user.

## Environment
 - Browser: any
 - Wallet: any
 - Chain: any

## Steps to reproduce
 1. Open the Safe on a smaller screen
 2. Go to Settings / Address Book / Assets
 3. Observe actions not being visible in the table

## Expected result

- Actions should be visible at all times

Possible solutions: https://www.notion.so/gnosis-safe/Responsive-Tables-5dba28401551448f889c9881e80d38a1

## Obtained result

- Actions are only visible after horizontally scrolling the table

## Screenshots

<img width="336" alt="Screenshot 2022-09-22 at 17 44 21" src="https://user-images.githubusercontent.com/5880855/191792450-71c1bf3b-bd06-4ae7-bf23-e25c686e49d6.png">
<img width="337" alt="Screenshot 2022-09-22 at 17 44 42" src="https://user-images.githubusercontent.com/5880855/191792545-e5622a8c-a98e-494e-b18a-c18964fd235d.png">

**Comment by francovenica** [comment]
So this looks good for resolutions < 600px. 
Still there are some portview where the icons remain hidden. Should we tackle those width in this ticket as well? or should we open an issue for those other viewports? I'm good with both options

![portvie](https://user-images.githubusercontent.com/4503659/192377645-f2af536b-ec63-4e6e-9326-c5dc7630929c.gif)

**Comment by katspaugh** [comment]
@francovenica let's ignore this. It looks best on desktop (>=1024px) and mobile (<=600px), we can't optimize for everything in between.

I suggest we use the phone emulation button <img width="72" alt="Screenshot 2022-09-27 at 08 06 25" src="https://user-images.githubusercontent.com/381895/192445959-e2a8d233-6b40-4395-b72c-a59b73a365ad.png"> instead of resizing the window.
