### ISSUE TITLE
Modal to connect to the app via physical device keeps popping up

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#615]
## Bug description
When connected with a trezor or ledger, if you refresh the page the modal pops up so you can connect again. The issue is that the only way to make it not pop up again is by connecting with a wallet and disconnecting manually
In safe react, the behavior was that you would just disconnect if the page is refreshed and no popUp would show up

## Environment
 - Browser: Chrome
 - Wallet: Trezor/ledger
 - Chain: Any

## Steps to reproduce
 1. Go to the safe app
 2. Connect with trezor or ledger
 3. Refresh the page

## Expected result
The connection to the wallet is lost and nothing more

## Obtained result
The connection is lost and the popup keeps showing everytime you refresh the page, even if you are not connected

## Screenshots
no screenshots

**Comment by usame-algan** [comment]
This happens with WalletConnect too. It pops up automatically when reloading the page if its stored as the last connected provider and we try to automatically reconnect.

**Comment by katspaugh** [comment]
Same with metamask.

I suggest the following solution:
* instead of caching the last wallet label, persist the entire wallet info itself
* do _not_ connect automatically on page load, but display the wallet as if connected
* when the user does anything that requires an actual connection, then connect

**Comment by iamacook** [comment]
[Enabling the modals](https://github.com/safe-global/web-core/blob/main/src/hooks/wallets/useOnboard.ts#L145) may help.
