### ISSUE TITLE
Transactions list: NFT default icon is missed for outgoing/incoming txs on txs list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#628]
Expected result: if NFT image can not be displayed , the default NFT image should be used in the txs list for outgoing and incoming txs
<img width="79" alt="image" src="https://user-images.githubusercontent.com/338622/192013080-8787d001-30fb-417a-a971-3cbeab962917.png">

**Comment by francovenica** [comment]
I think the issue refers to the icon in the tx overview. It used to be the default "gray diamond" icon. Now is the NFT's default Icon if the category doesn't have an icon.
Looks fine.

![image](https://user-images.githubusercontent.com/4503659/192407833-12ab7c1f-0a9c-4952-8cbc-c377a336a619.png)
