### ISSUE TITLE
Create safe form - Open QR code crashes the page

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#629]
## Bug description
In the safe creation form, trying to use the QR code feature to add more owners crashes the page

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to the safe creation form
 2. In the owner step click on the QR code icon

## Expected result
The QR code modal opens up

## Obtained result
Page crashes

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/192161708-fa898c18-df81-4b21-aea9-8e69e13cfcbd.png)

**Comment by usame-algan** [comment]
Possibly related to #167

**Comment by liliya-soroka** [comment]
Same when QR scanner is colled from the Send funds/send NFT form

**Comment by francovenica** [comment]
LGTM.
It can be merged to main
