### ISSUE TITLE
Wallet connect signing - Data looks broken in the MM app

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#630]
## Bug description
Signing an off-chain tx shows the data in the MM pop up, but it looks broken, the text is broken characters.
Tried same safe, owner and same type of tx (send funds of Dai in rinkeby) in safe-react mainnet and the data there looks fine

Note: the tx can be signed and executed without issues. The only problem is how the data looks

## Environment
 - Browser: Chrome
 - Wallet: WC (MM phone app)
 - Chain: Rinkeby

## Steps to reproduce
 1. Go to a safe 2/x
 2. Connect with WC, using the MM phone app
 3. Sign a send funds tx
 4. Check the data in the popUp that shows in the phone

## Expected result
Data is readable

## Obtained result
The data text has broken characters and cannot be opened

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/192162314-c73d8052-a1f5-4882-a3ed-5cb77047f6c0.png)

This is how it looks in safe react for comparison:
![image](https://user-images.githubusercontent.com/4503659/192162325-3b06eb08-9d2e-47e5-b4a7-315eb1b688ce.png)
![image](https://user-images.githubusercontent.com/4503659/192162334-ced07e0a-918b-4d05-949f-93e085603992.png)

**Comment by usame-algan** [comment]
This is most likely because we now use `eth_sign` method instead of `eth_signTypedData` when connected via WC.

**Comment by katspaugh** [comment]
This will be fixed by adding heuristics for v4/v3 signatures in the Core SDK.

**Comment by katspaugh** [comment]
This is now fixed.

<img width="1020" alt="Screenshot 2022-11-17 at 13 12 02" src="https://user-images.githubusercontent.com/381895/202443014-851d6e7e-fb26-4d3a-b4b7-917c84b072e6.png">
