### ISSUE TITLE
[NFTs page] Better items grouping for NFTs

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#636]
## Bug description
Better items grouping for NFTs
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to the safe with many NFTs
 2. scroll the list down
Current result: If the group contains many items (more than 10), the same group will be displayed a few times. Sometimes because of the pagination the same group is displayed with 1 items and a few times with 10 items under it . The same item is displayed a few times( contact me to get safe address)

## Expected result
Make sure that the items are grouped correctly and that the group is displayed only once with all items

**Comment by liliya-soroka** [comment]
may we also sort the groups by group name ( alphabetically) or does new pagination not allow it?

**Comment by katspaugh** [comment]
We shouldn't do client-side sorting.

**Comment by liliya-soroka** [comment]
should we discuss it with back-end to have a proper sorting? Or have we discussed it with them ?

**Comment by francovenica** [comment]
I don't understand the issue (or at least how it looked before the fix).
currently if there are a lot of NFT's of the same category they just keep loading as you scroll:
![nfts](https://user-images.githubusercontent.com/4503659/192408004-32be90e2-711f-4dec-b70d-319eaaf651a7.gif)

**Comment by katspaugh** [comment]
@francovenica they were previously grouped into separate groups with the same name for each of the loaded sub-pages.
Closing as it's fixed now as per your screen recording.
