### ISSUE TITLE
[NFTs page] Display the Zerion Safe App

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#638]
This feature needs to be ported from safe-react:

<img width="705" alt="Screenshot 2022-09-26 at 11 52 06" src="https://user-images.githubusercontent.com/381895/192247179-cc47fe69-4087-4d1c-9ff7-663534f7a526.png">

The app is displayed based on a tag.

**Comment by francovenica** [comment]
Question. The app is there, but is not usable (it doens't load). Probably it doesn't work unless is a prod env. Should we ask help to the guys in the apps before closing this ticket? or by showing it is enough to close it?

**Comment by iamacook** [comment]
> Question. The app is there, but is not usable (it doens't load).

This seems to be an issue with a lot of apps. I think it may be related to the newly added CSP headers but I'm not sure. I'll create an issue and inform them.

**Comment by katspaugh** [comment]
It's not related to the CSP headers. Some safe apps just block all domains except for gnosis-safe.io.

**Comment by iamacook** [comment]
> It's not related to the CSP headers. Some safe apps just block all domains except for gnosis-safe.io.

Makes sense, thanks!
