### ISSUE TITLE
[Send NFT] Truncate NFT item name if it's too long for the name field on the Send NFT form

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#639]
## Bug description
Truncate NFT item name if it's too long for the name field on the Send NFT form

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b/apps
 2. select ENS NFT item for sending 
Current result:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/338622/192252157-7832486b-3d06-418f-986b-40e91df1045b.png">

## Expected result
<img width="577" alt="image" src="https://user-images.githubusercontent.com/338622/192252203-b961f7ec-d0cd-4310-8435-f995d83206cb.png">

**Comment by francovenica** [comment]
Looks good. 
Can we remove the horizontal scroll? there is no token with a name so long to justify the horizontal scroll 
![image](https://user-images.githubusercontent.com/4503659/192406620-8cf35b0e-9ddc-41e1-bbb0-2cff8934eb3e.png)
