### ISSUE TITLE
[Send NFT] NFT image and number of items in collection are missing in the "select NFT", "select NFT collection" drop-down list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#640]
## Bug description
NFT image is missed in the "select NFT" drop-down list and default NFT image is displayed instead of it
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b/apps
 2. try to send NFT that has image in our UI
 3. click select NFT drop-down

Current result: NFT default image is used instead of real images when they are available on UI
<img width="710" alt="image" src="https://user-images.githubusercontent.com/338622/192252953-78b11ca2-6138-4b95-b364-dade63e235a0.png">

## Expected result
The real images should be displayed in the drop-down list if they are available and can be displayed on UI
<img width="638" alt="image" src="https://user-images.githubusercontent.com/338622/192253075-73cc7eaa-f944-4d10-b65a-e9d0f8aef1de.png">

**Comment by liliya-soroka** [comment]
NFT collection image is also missed in the "select NFT collection" drop-down together with the number of available items in the collection :
Current result: 
![Image](https://user-images.githubusercontent.com/338622/192253632-b41f9d39-929d-452a-94da-e8730e117f30.png)

Expected result:
Collection image if it can be displayed
Default place holder if it can be displayed or not available


![Image](https://user-images.githubusercontent.com/338622/192253791-64bb0080-92eb-463a-9551-e38a33980f5f.png)

**Comment by francovenica** [comment]
It seems that there are NFT's that might not have a category name, causing the counter not to show and being truncated. We should give it a default name so is standard with the other NFT's categories

![image](https://user-images.githubusercontent.com/4503659/192408425-4544bd19-86ca-4c17-9507-8ae45caf00fb.png)

**Comment by francovenica** [comment]
LGTM. 
Added a default category for those NFTs that don't have it.
