### ISSUE TITLE
[Send NFT]Review tx screen doesn't have information about send NFT to check it

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#642]
## Bug description
Review tx screen doesn't have information about send NFT to check it
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b/balances/nfts
 2. start send NFT flow and go to the review screen
Current result: There is no NFT info on the review screen
<img width="633" alt="image" src="https://user-images.githubusercontent.com/338622/192255468-8879b315-888e-4382-99cd-bfdcabc17953.png">

## Expected result
The review tx screen for send  NFT should contain selected NFT item info
<img width="540" alt="image" src="https://user-images.githubusercontent.com/338622/192255578-695e7261-0a16-4d43-bac0-37a46ac5f729.png">

**Comment by katspaugh** [comment]
@francovenica @liliya-soroka please note that I moved the NFT preview to the top of the modal, in the same style as the token transfer modal.

**Comment by francovenica** [comment]
LGTM
![image](https://user-images.githubusercontent.com/4503659/192659991-b25cb21e-cd14-48c3-9921-ab0d5edf2278.png)
