### ISSUE TITLE
[Send NFT] No simulation and Submit is disabled for the tx that will most likely fail

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#644]
## Bug description
No simulation and Submit is disabled for the tx that will most likely fail
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b/balances/nfts
 2.  try to send NFT that can not be send from the safe
 Current result: The error is displayed on the review screen, 0 is displayed instead of safe nonce, there is no Simulate option and submit button is disabled
https://web-core.pages.dev/rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b/balances/nfts

## Expected result
the same tx from the safe-react: safe nonce is not 0, simulate and submit options are available
<img width="539" alt="image" src="https://user-images.githubusercontent.com/338622/192262755-e86c7f1f-5ada-4907-b61a-746a84e0d189.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/338622/192262859-40167898-796f-4f7b-b3e7-6d8c6b21bfe9.png">

**Comment by DiogoSoaress** [comment]
I was already able to debug it. There are 2 things:

1. Gas estimation fails because the transaction reverts (the NFT in this case ENS name is expired)
2. Simulation does not appear because it is not enabled in Rinkeby

**Comment by katspaugh** [comment]
Why does it work on prod then?

**Comment by DiogoSoaress** [comment]
> Why does it work on prod then?

In prod we are fetching the `https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/<safeAddress>/multisig-transactions/estimations/` endpoint with `data: '0x'` and `to: safeAddress` so the estimation does not fail.

**Comment by katspaugh** [comment]
By prod I meant the same request with the debug toggle on.

**Comment by DiogoSoaress** [comment]
It sends the right payload in prod. Ok, investigating further.

**Comment by liliya-soroka** [comment]
Both errors in another place : I like it . It would be nice to keep them both everywhere in case failing tx

![Image](https://user-images.githubusercontent.com/338622/193030626-5bbf6c56-fa2a-491d-b00c-cba098d10199.png)
