### ISSUE TITLE
[Queued list] the text above queued about tx in the next section is missing

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#655]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/queue
 Current result:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/338622/192309160-dc31bb3e-782c-4a97-b649-1e20417cf578.png">

## Expected result
QUEUE - TRANSACTION WITH NONCE 303 NEEDS TO BE EXECUTED FIRST

**Comment by francovenica** [comment]
Issue:
If there is no "next tx" the message next to the queue shows the wrong "next nonce".
In this case the next nonce is 1653.

Safe: https://queued-nonce-label.web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions/queue

![image](https://user-images.githubusercontent.com/4503659/192409836-17e79d03-23a1-463b-9adb-14762ed35599.png)
![image](https://user-images.githubusercontent.com/4503659/192409853-2de4a452-194d-4023-a4e1-b17470931613.png)

**Comment by iamacook** [comment]
> Issue: If there is no "next tx" (because you created a tx way ahead of the next nonce) the message right next to the queue label shows the wrong "next nonce".

This is now fixed:

![image](https://user-images.githubusercontent.com/20442784/192440824-49b040bc-42c0-4fe3-b0fc-cfe06178a3ee.png)

**Comment by francovenica** [comment]
I was expecting next to the Queue label to say "next tx is [NEXT_NONCE_EXPECTED]" even if there is no "next" tx.

The reason to ask for that text is that nothing tells you why you cannot execute the tx you have queued unless you go to the settings to check the next nonce

**Comment by francovenica** [comment]
Looks good now:
![image](https://user-images.githubusercontent.com/4503659/192778366-90b1bfda-9708-4dec-9dfc-30d81bbc1e3d.png)
