### ISSUE TITLE
[tx creation] Tx details is not opened for the rejection tx

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#656]
## Bug description
[tx creation] Tx details is not opened for the rejection tx
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/queue
 2. try to reject any tx in the queued list
 Current result: rejection tx is created but tx details for this tx is not opened

## Expected result
Open tx details for the rejection tx too

**Comment by francovenica** [comment]
LGTM

After a rejection is created it takes you to the "deep link" view.
