### ISSUE TITLE
[advanced parameters] sections titles are missing

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#661]
## Bug description
sections titles are missed
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/queue
 2. try to execute any tx and click "advanced parameters"
 Current result: There are no "Safe transaction", "Owner transaction (Execution)" sections titles
<img width="670" alt="image" src="https://user-images.githubusercontent.com/338622/192317670-6a3fdd44-5f1f-40be-97fc-03da8c5cf8c3.png">

## Expected result
Make sure that the sections titles are displayed:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/338622/192317754-7a2026bd-4d42-47da-8709-4755cd127df0.png">

**Comment by francovenica** [comment]
Looks good for both on-chain and off-chain tx modals adv options
![image](https://user-images.githubusercontent.com/4503659/192660251-e581dc6a-382d-4deb-9ff6-16d5e9bf4cbe.png)
![image](https://user-images.githubusercontent.com/4503659/192660262-af408697-1966-49b2-9a75-40347f151300.png)
