### ISSUE TITLE
Onboard styling doesn't match new theme

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#672]
## Bug description

Some elements of the onboard modal don't match that of the new theme. The CSS variables of onboard need to be better mapped to our new theme

## Steps to reproduce
 1. Connect varying wallets and observe the colours do not match perfectly to our new theme.

## Expected result

- The stepper is `primary.main` in light mode.
- THe checkmark is a darker color in light mode.

## Obtained result

- The stepper is green in light mode.
- The checkmark of a connected wallet is white (and hard to see) in light mode.

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/192445485-110c90e7-bbe7-47dc-9d8e-374546a76d05.png)

**Comment by francovenica** [comment]
Adding to this ticket. The onboard for the connection with physical devices needs revision
The light theme show the neon-green in buttons and other places
In the dark mode the "Confirm" button is purple

![image](https://user-images.githubusercontent.com/4503659/192644662-3605d93a-8c73-4aa0-a4c9-25a16751260e.png)
![image](https://user-images.githubusercontent.com/4503659/192644702-d81e052d-ae63-4676-9b9f-e9aa282d0714.png)

**Comment by francovenica** [comment]
LGMT
![image](https://user-images.githubusercontent.com/4503659/193657957-cb69ce90-21e7-4172-9456-29e609c18120.png)
![image](https://user-images.githubusercontent.com/4503659/193657977-6da1e82f-71f9-4e35-8dc1-7a2ec35296f2.png)
![image](https://user-images.githubusercontent.com/4503659/193657992-de6bfccf-d560-4c85-963a-c6dceffbb093.png)
![image](https://user-images.githubusercontent.com/4503659/193658007-3c6c4476-c081-42b1-89ed-56542cce2815.png)
