### ISSUE TITLE
[History] Execution time should be shown in history instead of N days ago

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#673]
## Bug description
Execution time should be shown in history instead of N days ago, as the data is displayed for each tx anyway
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/history
 Current result: N days ago is displayed instead of the execution tx in the list.
<img width="926" alt="image" src="https://user-images.githubusercontent.com/338622/192457959-f321896f-a544-4be1-9638-eedbe7bb55e6.png">

## Expected result
The execution time should be displayed in the history ( only history, the queued list still should use N min, N days ago)
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/338622/192458119-e45c7e8b-96ac-4f75-bbe0-8567f499b703.png">

**Comment by katspaugh** [comment]
N.B. since there are no date labels in the Queue and Filters, only History should show the time.

**Comment by francovenica** [comment]
Looks good
Only the history tab has the exact time of the tx
