### ISSUE TITLE
[Send Modals] Recipient name from the addressbook  is missing on Send forms

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#678]
## Bug description
Recipient name from the addressbook  is missing on Send funds and Send Nft form
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/address-book
 2. open Send funds/send NFTs form directly
 3. click in the recipient field and select an address from the addressbook
 Current result: The recipient name from the addressbook is not displayed in the form
<img width="648" alt="image" src="https://user-images.githubusercontent.com/338622/192464517-dd9f8d39-a226-4254-b254-45df2fdf16b4.png">

## Expected result
The recipient name should be displayed if it's taken from the address-book
<img width="590" alt="image" src="https://user-images.githubusercontent.com/338622/192464630-89fc530a-777c-43a5-bfa0-90939787d74b.png">

**Comment by francovenica** [comment]
Looks good:
![name](https://user-images.githubusercontent.com/4503659/192893929-13b3d12b-39aa-4d2c-9704-6c3c7f11eb4d.gif)

**Comment by liliya-soroka** [comment]
Verified and can be merged
