### ISSUE TITLE
Visual issues on UI on the first load

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#680]
## Bug description
When entering on the web application for the first time some styles of the page are not fully loaded causing visual inconsistencies for about 2-3 seconds.

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any

## Steps to reproduce
Open an incognito private window and access the [address book](https://web-core.pages.dev/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/address-book) or [settings](https://web-core.pages.dev/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/settings/setup)

## Expected result
No visual issues.
## Obtained result
Visual issues for about 2-3 seconds.

## Screenshots
![Captura de pantalla 2022-09-27 a las 10 02 42](https://user-images.githubusercontent.com/92332710/192479291-794859be-564f-4907-aa30-015d730c96a7.png)
![Captura de pantalla 2022-09-27 a las 10 37 33](https://user-images.githubusercontent.com/92332710/192479400-d216c230-ee30-4245-9c11-bdb25675188b.png)

**Comment by katspaugh** [comment]
<img src="https://media3.giphy.com/media/jquDWJfPUMCiI/200.webp" />

**Comment by katspaugh** [comment]
@JagoFigueroa we fixed it, it loads smoothly now 👍 
Please see the branch preview in the PR.

**Comment by JagoFigueroa** [comment]
Mucho smooth indeed, thanks! Todo bueno ;)
