### ISSUE TITLE
Transaction data overlapping on narrow resolutions

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#682]
## Bug description
Transaction information overlaps on smaller window resolutions causing visual issues on UI

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any

## Steps to reproduce
Go to either Transaction queue or [Transaction history](https://web-core.pages.dev/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/transactions/history)

in my 2k monitor, presentation issues start at around 1600px X xxxxpx resolution

## Expected result
No visual issues (at least until a reasonable resolution, like on og web)

## Obtained result
A couple examples: 
![Screenshot 2022-09-27 at 10 59 54](https://user-images.githubusercontent.com/92332710/192487217-a0ff59bc-967a-42a4-a8f3-764b1007425e.png)
Revamp (left) vs legacy (right)
![Screenshot 2022-09-27 at 11 14 15](https://user-images.githubusercontent.com/92332710/192487345-6f77f90e-4470-4de6-a944-941a14f6b436.png)

**Comment by francovenica** [comment]
This ticket is the same as #675

**Comment by liliya-soroka** [comment]
Verified
