### ISSUE TITLE
Recipient input - Using ENS name removes the network prefix after convertion

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#686]
## Bug description
Writing and ENS name translates it to its address. The issue is that the prefix is removed after this convetion

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
 1. Go to a safe you own in Rinkeby
 2. Open the send funds modal (no matter if you don't have funds in the safe)
 3. Write "francotest.eth" and should translate to rin:0x61a0c717d18232711bC788F19C9Cd56a43cc8872

## Expected result
The address is set with the prefix

## Obtained result
The prefix is removed after a few seconds

## Screenshots
![prefix](https://user-images.githubusercontent.com/4503659/192525428-7d3ecf12-39a8-46a1-8d47-d3b5d3ad8ffb.gif)

**Comment by katspaugh** [comment]
Tweaked the code, please see if it works now @francovenica

**Comment by francovenica** [comment]
Works fine now. Thanks
