### ISSUE TITLE
[Adding a custom safe app] App not opened on addition

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#692]
## Description
On web-core adding a custom app won't open it as it happens on legacy safe.

## Steps to reproduce
Go to Rinkeby (for example) and add [Snapshot](https://snapshot.org/) as a custom app

## Expected result
App opened after addition

## Obtained result
User redirected to /apps screen

**Comment by clemoon** [comment]
This is not a bug but the expected behaviour so we should keep it this way

**Comment by JagoFigueroa** [comment]
Closing this ticket then. Thank you monsieur ;)
