### ISSUE TITLE
[Add custom app] Pop up visual issues

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#697]
## Description
A small list of issues affecting this pop up on web-core that I think it would be nice to fix for the release.

## Issues:
 1. Increase visibility for app name field (for both light and dark themes). ![Screenshot 2022-09-27 at 12 21 20](https://user-images.githubusercontent.com/92332710/192501924-c5e1ce5f-08cb-48f9-abed-d4c8c8907f0d.png)

 2. Provide visual feedback in the buttons when they are not clickable due to an error like in legacy web: ![Screenshot 2022-09-27 at 12 19 25](https://user-images.githubusercontent.com/92332710/192501889-1ca56834-1c1f-41ab-8e8d-72ea928a86e7.png)

 3.  The safe apps icons on dark mode should not be black (Maybe green?):
![Screenshot 2022-09-27 at 12 28 15](https://user-images.githubusercontent.com/92332710/192502616-7826b2d9-ab5d-4f47-90e3-be8334898836.png)

4. Pop up covering the whole screen on smaller resolutions: ![Screenshot 2022-09-27 at 12 41 11](https://user-images.githubusercontent.com/92332710/192505228-d53b6478-039f-4de0-af9e-edd12f0ecdfc.png)

5. (optional and more like a question) shouldn't the 'save' button be 'add'?

**Comment by katspaugh** [comment]
The dim font color has been fixed on main.

**Comment by yagopv** [comment]
> The dim font color has been fixed on main.

Yep I saw it, but even with that i'm adjusting a little bit for the app name to stand out more as the field is disabled

**Comment by JagoFigueroa** [comment]
looking good! Mini issue I found is that when adding a custom app (like this one https://app.ihelp.finance/ for avalanche) the app icon for it is not displayed in the pop up anymore.
