### ISSUE TITLE
[Ledger/Trezor] Disable Edit option in the Execute Transaction modal for Trezor and Ledger devices

### ISSUE THREAD

**Issue by DaniSomoza** [safe-global/web-core#700]
## Overview

Update (19.12.22): There are [reports of Ledger devices having low estimations](https://5afe.slack.com/archives/C03BHKS5K6D/p1671455281406219). It seems as though gas prices are set too low and that transactions aren't making it into the mempool.

We need to investigate whether:
- estimations are correct
- hardware wallets can estimate themselves
- we disable them for hardware wallets

---

It seems that is not possible to set the `Gas Price` value if you are using directly a `Ledger` device.  (see [this ticket](https://github.com/safe-global/safe-react/issues/3222) for more details)

As an Improvement we can detect that the current owner is a `Trezor` or a `Ledger` device and disable the `edit` option or the `Max fee per gas` input.

## Designs
![Captura de pantalla 2022-07-01 a las 16 23 18](https://user-images.githubusercontent.com/26763673/176913593-718ba410-4ab1-4068-b5e5-3b781b276b8c.png)
![Captura de pantalla 2022-07-01 a las 16 23 36](https://user-images.githubusercontent.com/26763673/176913600-1ac04cd3-764a-4f47-af14-40ff10c2158d.png)

## Links

Issue: https://github.com/safe-global/safe-react/issues/3222

**Comment by katspaugh** [comment]
Tested with Ledger, it correctly receives both the default and a manually edited gas price.

![image](https://user-images.githubusercontent.com/381895/210803410-4bd467dc-6645-44d6-94a6-c448f669c26f.png)

**Comment by katspaugh** [comment]
@francovenica @liliya-soroka could you check with Trezor?

**Comment by francovenica** [comment]
Yes, works fine in a Trezor one. I also tried with my ledger and works fine as well
Tried with the default estimation and an edited estimation (editing gas limit, price and fee)

![image](https://user-images.githubusercontent.com/4503659/211219020-4814ded4-672b-4bba-87de-aa80e50dc7d7.png)

I'll close this one
