### ISSUE TITLE
Webapp doesn't expire "Connect to mobile" connection

### ISSUE THREAD

**Issue by biafra23** [safe-global/web-core#701]
## Description

WalletConnect connections ("Connect to Web" on Mobile) are not removed after more than 24h of inactivity

## Environment
 - Browser: Chrome
 - Wallet: Gnosis Safe Mobile
 - Chain: Rinkeby

## Steps to reproduce
 1. On the iOS mobile app: Settings -> Connect to Web -> Scan Code 
 2. Scan "Connect to Mobile" on the web app
 3. Wait 24 hours (or adjust the expiry date on mobile) and make sure the mobile app is not able to tell the web app to drop the connection (use flight mode)
 4. Make sure connection is not available on mobile anymore
 5. Open web app 

## Expected result

Expected behavior: The connection should not be available anymore on web. At least it should be terminated, when it cannot be used

## Obtained result
Observed behavior: The webapp tells me to sign the tx, but the mobile phone never gets the message (because the connection has been dropped on mobile.

This can happen weeks after the connection was established. When at least after 24h it should be expired.

## Screenshots
![image](https://user-images.githubusercontent.com/246473/169466471-ba30fb22-bdc5-4cb6-b715-e127b2c87a3a.png)

**Comment by katspaugh** [comment]
@francovenica @liliya-soroka could you check if this is still the case?

**Comment by francovenica** [comment]
3hs later. At some point it disconnected from prod (where I was connected) but in the phone safe app I'm still connected

**Comment by francovenica** [comment]
Works fine now. I've set the expiration date a few mins in the future and the app disconnected on its own, both in the mobile application and the web application
