### ISSUE TITLE
Add Tally Ho as a wallet option

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/web-core#703]
## Overview

In the product sync we have decided to add Tally Ho as a wallet option. In terms of further maintenance & support we limit our focus on the most used wallet options. 

## Requirements

- [ ] Install onboard module

**Comment by francovenica** [comment]
Looks good. 
I created a wallet to test this. I was able to create a safe and add a new owner. (that's it since I had to use ETH mainnet)
