### ISSUE TITLE
Add thousand separators to review amount

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#705]
## Overview
Large amounts on the review modal can be confusing. As such, we should add thousand separators.

## Requirements
Format token amount in review modal header.

## Screenshot
![image](https://user-images.githubusercontent.com/20442784/166464928-84a5a795-acba-43f7-b211-4cf3eba49820.png)
![image](https://user-images.githubusercontent.com/20442784/166464954-ff985843-1a6c-4be7-b9fd-d28776fb664a.png)

**Comment by DiogoSoaress** [comment]
@safe-global/safe-qa sorry I've merged this by accident (didn't mean to skip QA) so I moved the ticket back to "Ready for QA".

**Comment by liliya-soroka** [comment]
Verified.
Only already opened bug is found with another separator when max option is used in the amount field
