### ISSUE TITLE
[Sefe app load error] Update error icon on dark theme

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#707]
## Bug description
(very minor issue, no need to fix for the release or anything) the icon present on dark theme when a safe app fails to be loaded is from the light theme.

## Steps to reproduce
Kind of tricky, Gnosis Auction starter fails quite often for me.

Open the [safe app](https://web-core.pages.dev/gno:0x73C55F09a025Aada29306DdC04F066F6E383Eb86/apps?appUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2FQmSpfd5UwhUBZxKouqSsY3bFynyDy6sToVLigLwSWRms9s) on dark mode and if it fails we will see this:

![Screenshot 2022-09-28 at 09 58 03](https://user-images.githubusercontent.com/92332710/192723671-f04665d7-fb63-4f4a-8c4d-69aa649ecd23.png)

## Expected result
Dark theme icon present.

## Obtained result
Light theme icon present.

**Comment by yagopv** [comment]
For me the icon is fine 😁. If we need a specific one for dark mode then we need it from design or at least how to change it properly

I can change some colors based on the palette but is going to be as a personal preference. Anyway,  I think it fits fine like this in both themes

**Comment by yagopv** [comment]
Finally changed this by using some magic classes from the global.css file. Take a look @JagoFigueroa

**Comment by JagoFigueroa** [comment]
Espectacular señor! 

<img width="476" alt="Screenshot 2022-10-03 at 12 55 32" src="https://user-images.githubusercontent.com/92332710/193560975-35d0496b-08eb-4ca4-ad76-8e8fac3cb51b.png">

I think we can close this ticket ;)
