### ISSUE TITLE
Unrealistic ledger connection failure prompt

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#708]
## Description
When Ledger wallet connection fails for the first time, error message will be present when trying to reconnect the wallet for a second time

## Environment
 - Browser: Any
 - Wallet: Ledger
 - Safe: 0xfBa7Dd7914673e119708AC79a791feA309DEF7E0 (any will do)
 - Environment: production (rinkeby)

## Steps to reproduce
 1. Connect a ledger wallet 
 2. Set an invalid path to force connection failure (see attached screenshot for reference)
 3. Close or dismiss the pop up
 4. Re-initiate ledger wallet connection

## Expected result
Reference to previous wallet connection failure should not be there.

## Obtained result
Pop up is opened in the same point the user closed it the previous time which can be confusing.

## Screenshots
![ledger connect](https://user-images.githubusercontent.com/92332710/138429161-f948e12d-bc05-4da7-9af7-cf2f03ee93b3.png)

**Comment by iamacook** [comment]
I'm going to close this as it relates to the older version of onboard.
