### ISSUE TITLE
Add more ranges for owned NFTs on Overview widget

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#717]
## Description
For safes with lots of NFTs it can be kind of cute to see that they own more than 10 NFTs

## Requirements
Add more ranges to display on this widget:

<img width="842" alt="Screenshot 2022-09-28 at 12 06 57" src="https://user-images.githubusercontent.com/92332710/192756351-ff8c20df-cc98-4817-897c-4dc264eefef6.png">

**Comment by iamacook** [comment]
We now paginate the NFTs and, as such, only fetch ~10 on intial load. It was very intensive to load all of them in one go before. I'm not sure if we want to consider this.

**Comment by katspaugh** [comment]
Once the CGW rewrite stabilizes, we'll likely make a new endpoint (or extend the Safe info) with the aggregated info needed for the Dashboard. Incl. the NFTs amount, queue size etc.
As of now, like Aaron said, there's no efficient way to retrieve the total count. Closing for now.
