### ISSUE TITLE
(feature) Add Stepper on Reject transaction modal

### ISSUE THREAD

**Issue by alongoni** [safe-global/web-core#718]
Reject popup: Stepper was proposed after user tests to explain where the user is in the process and when to pay gas.    

<img width="521" alt="Screenshot 2022-09-28 at 13 13 14" src="https://user-images.githubusercontent.com/381895/192765225-d5852184-227c-4e03-8ede-7f67e3894c58.png">

### Links
- [Figma mockup](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=1076%3A40781)

**Comment by iamacook** [comment]
I've marked this as blocked after convening with @liliiaorlenko as she is looking into the design in more detail.

**Comment by liliiaorlenko** [comment]
https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2104%3A56376

**Comment by katspaugh** [comment]
Implemented in #1079.
