### ISSUE TITLE
Safe creation - A big icon flickers when cancelling the safe creation

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#723]
## Bug description
If instead of accepting the tx to create the safe you reject it in the wallet, for a second a big icon popsup in the UI

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: any

## Steps to reproduce
 1. Go to safe creation
 2. Get to the final step and submit
 3. Reject the tx in the wallet
 4. See the UI

## Expected result
The icon are always the same size

## Obtained result
The icon increases in size for a split second

## Screenshots
![erorr safe creation](https://user-images.githubusercontent.com/4503659/192787628-4e739d60-7961-4c70-b050-8888ce1c321b.gif)

**Comment by iamacook** [comment]
We're going to close this as the Safe creation is going to be completely reworked soon.
