### ISSUE TITLE
Exchange all icons for those of Figma

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#733]
## What is the feature about

`@mui/icons-material` is used in most places whereas we should be using as many icons as possible from Figma in order to align our design with mobile.

## The list of requirements

- Search for `@mui/icons-material`, replacing their relevant counterpart from Figma.

## Links

- [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=0%3A1)

**Comment by liliya-soroka** [comment]
Please, merge the PR , but leave the ticket in QA ready state :pray:

**Comment by liliya-soroka** [comment]
Verified
