### ISSUE TITLE
[Settings] Tooltip with nonce info is missed near safe nonce

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#736]
## Bug description
Tooltip with nonce info is missed near safe nonce
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/settings/setup
 2.  scroll down to the safe info

Current result: 
<img width="260" alt="image" src="https://user-images.githubusercontent.com/338622/192996728-cce2596d-d58c-4bd6-a843-0d41ed72be47.png">

## Expected result
The tooltip should contain the same info as we have in the rsafe-eact app for the safe nonce
<img width="102" alt="image" src="https://user-images.githubusercontent.com/338622/192996801-a9d71786-ea68-4c4b-916b-79f9a66f22b9.png">

**Comment by katspaugh** [comment]
Where is that tooltip on the old site? I don't see it here: https://gnosis-safe.io/app/eth:0x5f9ee776B85f1aFF123f935C48C528D00a62B0ad/settings/advanced

**Comment by liliya-soroka** [comment]
In the old msite we don't have tooltip but we have the  description under safe nonce. In the new site there is no space for the description , so tooltip was added to the design
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/338622/192999931-3ea0650b-ef0b-4639-a661-7b0d619371ba.png">
