### ISSUE TITLE
* is missing near the enter fields for the mandatory data all over the app

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#742]
## Bug description
"*" is missing near the enter fields for the mandatory data all over the app
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go through the create safe flow or replace owner ( any other flow in the app)
Current result: there is no indication of mandatory data. So the only way is to leave a field empty and check an error message 

## Expected result
Could you add again "*" for all mandatory fields?

**Comment by iamacook** [comment]
This is easily achieved by adding the `required` prop to the relevant input field.

**Comment by liliya-soroka** [comment]
@iamacook , may the fix influence on the error view :


![Image](https://user-images.githubusercontent.com/338622/193318468-cd37e4db-12d7-47bc-b9e1-e6d3b42d0efe.png)

**Comment by iamacook** [comment]
> @iamacook , may the fix influence on the error view :
> 
> ![Image](https://user-images.githubusercontent.com/338622/193318468-cd37e4db-12d7-47bc-b9e1-e6d3b42d0efe.png)

Yes, they are now recognised as required by the browser as well.

**Comment by francovenica** [comment]
LGTM.

Checked in Send funds, send NFT, add onwer, replace owner, AB create entry, Spending limits, Safe creation, Safe adding

NOTE: The "Please fill in this field" doesn't show for dropdowns, but since that's browser behavior I assume is not something we have control over it
