### ISSUE TITLE
Two scrolls when the modal window is scrollable

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#744]
## Bug description
Two scrolls when the modal window is scrollable
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Open the review screen in a replace owner modal window in the safe with many owners
 2. scroll the modal window context 

Current result: https://drive.google.com/file/d/1EECYYXXqVmiRRGPOVlVBezQP9jKoGV4J/view?usp=sharing
## Expected result
1. maybe it makes sense to scroll inside the modal, so the header and the bottom part with buttons of the modal window are always visible?
2.  can the scroll of the main screen be disabled when the modal window is opened?

**Comment by francovenica** [comment]
Looks good.
So from now on no more in-modal scrolling? all modals will be full length and the is the page the one that will scroll?

**Comment by katspaugh** [comment]
Yes, correct

**Comment by francovenica** [comment]
Adding that to the regression checklist then
