### ISSUE TITLE
[Tx confirmation]Confusing text when the last confirmation can be received but the execution is not available

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#745]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to the queued list
 2. click confirm to add the last required confirmation for any tx in the queued list except the tx in the next section

Current result: "Sign or immediately execute this transaction." is displayed to the user but actually, the user can not execute tx as it's not the next for the execution tx in the queued list
<img width="659" alt="image" src="https://user-images.githubusercontent.com/338622/193023726-e378c5ee-4bea-4f2b-9a51-ee7862e26f00.png">

## Expected result
Don't mention execution if the "execution" operation is not available

**Comment by francovenica** [comment]
LGTM

When signing but the tx cannot be executed:
![image](https://user-images.githubusercontent.com/4503659/193722571-05d434c3-44a1-43f2-a1ad-ca274d49a826.png)

Also checked when is ready to be executed (fully signed tx in queue):
![image](https://user-images.githubusercontent.com/4503659/193722607-4a0b7c2a-faca-483e-9349-78f153a6ffd7.png)

And when signing and can also be executed at the same time:
![image](https://user-images.githubusercontent.com/4503659/193722677-740cc25d-64d2-456d-beac-c8c55f2b2127.png)
