### ISSUE TITLE
[Settings]Submit button is hidden on change policy review screen when  selected policy is the same as the current one

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#751]
## Bug description
Submit button is hidden on the change policy review screen when the selected policy is the same as the current one
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to the setting ->set up
 2. click change policy
 Current result: The "submit" button is hidden till the diff from the current policy is selected
<img width="987" alt="image" src="https://user-images.githubusercontent.com/338622/193029826-2682053b-87f7-46fa-a06b-d177cd826d6a.png">

## Expected result
The submit button should be disabled instead of hiding

**Comment by DiogoSoaress** [comment]
@liliya-soroka could we consider one of the solutions I present in the last comment? Providing more info for omiting the Submit button -> https://github.com/safe-global/web-core/pull/803/#issuecomment-1268204908 ?
