### ISSUE TITLE
[Safe creation] Visual issues on dark mode

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#756]
## Bug description
Playing with safe creation on dark mode I found a couple of visual issues affecting this stepper:
<img width="1481" alt="Screenshot 2022-09-29 at 14 47 41" src="https://user-images.githubusercontent.com/92332710/193035697-bfd0cd87-d436-491a-a2a6-f0942e6f8cac.png">

1. Missing dark mode animated icon.
2. (maybe a personal opinion so feel free to ignore this if needed) green bar its too intense for its big size.

**Comment by katspaugh** [comment]
This will be tackled comprehensively in the upcoming Safe creation redesign.

**Comment by iamacook** [comment]
I'm going to close this as it relates to the old design.
