### ISSUE TITLE
[Safe creation] Missing "safe created" pop up on safe creation

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#762]
## Bug description
We are missing this pop up that is present in legacy web when a safe is created:

![Captura de pantalla 2022-09-29 a las 14 32 39](https://user-images.githubusercontent.com/92332710/193043088-1925ae26-b56e-474a-8647-e3619d397b12.png)

## Steps to reproduce
Complete create safe flow.

## Expected result
Pop up at the end providing some nice extra info for users.

## Obtained result
User redirected to /home

**Comment by iamacook** [comment]
We are soon to rework the entire Safe creation flow. I am not sure if this is necessary.

**Comment by JagoFigueroa** [comment]
Feel free to close this ticket if that would be the case señores!
