### ISSUE TITLE
[Settings screen] Not all options are viewable on mobile resolutions

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#763]
## Bug description
When opening the settings screen of the web interface from mobile sections will be hidden for users due to a lack of space & lateral scrolling.

## Steps to reproduce
Either directly from a mobile device or via the the browser's developer tools go to the settings screen.

## Expected result
All sections visible or accessible via lateral scrolling.

## Obtained result
Presentation is mucho bueno but as there is no scrolling, user won't be able to select Spending limits or Safe apps permissions.

<img width="480" alt="cerveza" src="https://user-images.githubusercontent.com/92332710/193060363-5271f293-4065-40be-8d41-a1709094adda.png">

**Comment by iamacook** [comment]
You can scroll left and right on them. Maybe we should [force the scroll buttons](https://mui.com/material-ui/react-tabs/#forced-scroll-buttons) on lower resolutions?

**Comment by katspaugh** [comment]
In this particular case I think there's plenty of space if not for the double paddings (one from the page itself, the second from the card).

**Comment by francovenica** [comment]
Looks good. Scrolls fine in real phones as well.
