### ISSUE TITLE
Owners and threshold are not persisted on Safe creation flow

### ISSUE THREAD

**Issue by DiogoSoaress** [safe-global/web-core#768]
## Bug description
On the Safe creation flow, after setting an owners policy. If the user goes back one step to rename the Safe, the previously set Owners and threshold are gone.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to Safe creation
 2. Add more owners and change the threshold on step 3
 3. Go back to rename the Safe
 4. Back to step 3 the previously setup is lost

## Expected result
Owners and threshold are persisted across steps

## Obtained result
Previously setup is lost

## Screenshots
![owners and threshold gone](https://user-images.githubusercontent.com/32431609/193078926-46a9d87a-a7a4-4b88-bf41-52014f195697.gif)

**Comment by iamacook** [comment]
I investigated this further and it's working, so I'll close this.

![threshold](https://user-images.githubusercontent.com/20442784/193304905-505cfdef-10d0-4587-af11-8b6d23375c62.gif)

This was likely the bug that arose during https://github.com/safe-global/web-core/pull/766.

**Comment by liliya-soroka** [comment]
reopened:
@iamacook , 
1. the back button should be clicked on the owners step to go back to the safe name 
2. click continue to come back to the owners list
Current result: the list of owners is clined 
Expected result: in the safe-react app the list of the owners was saved

**Comment by francovenica** [comment]
Looks good. 
Tried safe creation /adding, going back and forth editing safe names, owners names, policies and checking that the values were stored every time
![safe creation](https://user-images.githubusercontent.com/4503659/194084636-571792d6-fcc6-47b3-87da-770d280a80d4.gif)
