### ISSUE TITLE
List of owned Safes on the welcome page 

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#773]
When opening the app for the first time in a new browser and connecting a wallet, it opens the welcome screen offering to create/add a safe. Whereas the wallet might already have some Safes.

Show the list of owned Safes as a navigation entry point in addition to create/add.

Needs design.

@TanyaEfremova @liliiaorlenko wdyt?

**Comment by liliiaorlenko** [comment]
I think its a good idea, Ill work on a designs

**Comment by katspaugh** [comment]
Attaching our prior ideation just in case:
<img width="649" alt="Screenshot 2022-10-04 at 12 26 21" src="https://user-images.githubusercontent.com/381895/193796535-3ca53bac-a929-4317-a0ab-6e3fa65150f3.png">

**Comment by usame-algan** [comment]
Is this issue solved with #1423?

**Comment by katspaugh** [comment]
Yes, thank you, closing.
