### ISSUE TITLE
[Spending limits] Not possible to set one with decimals

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#774]
## Bug description
I was trying to create a new spending limit of 0.5 eth for one of my owners and it is not possible, we should fix this.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
 1. On any owned safes, go to Settings -> Spending Limits and try to set one with decimals.

## Expected result
(legacy)
<img width="593" alt="Screenshot 2022-09-30 at 08 55 33" src="https://user-images.githubusercontent.com/92332710/193209509-4b515e55-968c-4322-8b6e-56b5383feb06.png">

## Obtained result
(revamp)
<img width="723" alt="Screenshot 2022-09-30 at 08 54 48" src="https://user-images.githubusercontent.com/92332710/193209541-d86ca6b3-b33a-45a2-9d55-aff74de0f6a6.png">

**Comment by francovenica** [comment]
LGTM. 
I can create spending limit with decimals now. 
I can use the spending limit just fine as well

Also it looks better to have a "amount too low/too high" better than the cientific notation.
