### ISSUE TITLE
[Spending limits] Module seen as unknown in tx queue & history 

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#775]
## Bug description
Although the module name is shown in the modules screen
<img width="943" alt="Screenshot 2022-09-30 at 09 08 16" src="https://user-images.githubusercontent.com/92332710/193212876-8b9cecd9-8226-43f3-9f3b-0bbe80f310df.png">

 looks like it fails to be fetched for the tx queue and history screens (I see that this also happens in legacy web).

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
Disable spending limit module for a safe.

## Expected result
On tx details, reflect the name of the module that is being disabled.

## Obtained result

<img width="1468" alt="Screenshot 2022-09-30 at 09 10 53" src="https://user-images.githubusercontent.com/92332710/193213140-264a632c-7c51-4909-9675-ad63a3062404.png">

**Comment by iamacook** [comment]
This was reported yesterday by @liliya-soroka and I've already fixed it. I've linked the relevant PR.

**Comment by JagoFigueroa** [comment]
My bad señor, closing this ticket then. Thanks for letting me know!
