### ISSUE TITLE
[Safe creation] Improve error handling for safe owner configuration

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#789]
## Bug description
The error handling seen on screen when trying to create a safe with repeated owners or invalid addresses needs a little bit of tweaking as after some adding / removing of safe owner configurations that should be valid are stuck with an error on ui.

## Steps to reproduce
Play around on safe creation by adding the same owner address a couple of times and then remove one of the 2 (see video for more examples of this).

## Expected result
UI refreshes as expected when adding / removing owners.

## Obtained result
UI gets a little bit stuck as seen on this video:

https://user-images.githubusercontent.com/92332710/193516532-da39643a-1a72-4bca-8b77-67db422c3f63.mp4

**Comment by francovenica** [comment]
Close as wont fix
