### ISSUE TITLE
Onboard modal - Modal for physical devices can be too long

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#796]
## Bug description
My trezor happen to have a bunch of addresses, making it too long for the viewport. 

## Environment
 - Browser: Chrome
 - Wallet: Trezor
 - Chain: any

## Steps to reproduce
 1. Go to the app and connect with trezor
 2. Unlock it and scan for addresses

## Expected result
Full modal visible with a fix height, and just make the address list scrollable

## Obtained result
![image](https://user-images.githubusercontent.com/4503659/193655921-8825f3aa-4742-4af4-84b6-51343550a8bd.png)

**Comment by katspaugh** [comment]
Closing as won't fix as this is on onboard's side. I'll pass this on to blocknative.
