### ISSUE TITLE
Estimated gas fee fails to be loaded

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#811]
## Bug description
Playing around on optimism I noticed that there seems to be an issue preventing the estimated gas fee to be loaded and shown to the users when I try to execute a transaction.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Optimism, Aurora, BNB

## Steps to reproduce
On optimism chain create + execute a tx (feel free to execute [this one](https://web-core.pages.dev/oeth:0xeb1116466B7eB1372cD1FAf5C26134db69A94cDA/transactions/tx?id=multisig_0xeb1116466B7eB1372cD1FAf5C26134db69A94cDA_0xcb64c18f69b74cb7784e3bb5e0416dcbca862f994c3c20ab112b8bd27f33591c)).

## Expected result
Gas estimation is shown in the transaction modal.

## Obtained result
Estimation is stuck in loading as if it expected some parameters that are not there.

Direct comparison with legacy web:

<img width="1504" alt="Screenshot 2022-10-05 at 09 42 55" src="https://user-images.githubusercontent.com/92332710/194008750-f683eb86-c709-479a-8936-cc6a89c17787.png">

**Comment by JagoFigueroa** [comment]
Updating the title to remove the optimism chain as the same happens for me in Aurora for example (I will continue checking other chains).

**Comment by francovenica** [comment]
I tried to add an owner just to review step to see the estimation in avalanche, optimism and arbitrum. 
It worked fine

**Comment by katspaugh** [comment]
@JagoFigueroa could you check Aurora? I've sent some AETH to my safe but it's not indexing...

**Comment by JagoFigueroa** [comment]
Sorry for the delay! Aurora is good too so all bueno from my side as well 😄
