### ISSUE TITLE
[Pinned safe apps] Pins performed globally instead of per chain

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#814]
## Description
We should keep the same behaviour we had in legacy for pinned apps where the users would see their pinned apps per chain and not globally.

## Steps to reproduce
1. Pin a couple of safe apps on the revamp and check local storage.

2. Do the same in legacy for comparison.

## Expected result
Pinned apps stored per chain:
<img width="889" alt="Screenshot 2022-10-05 at 11 32 52" src="https://user-images.githubusercontent.com/92332710/194031001-0f168f26-1c69-432f-911e-17310f4e9d3d.png">

## Obtained result
Pinned apps are stored globally:

<img width="691" alt="Screenshot 2022-10-05 at 11 44 04" src="https://user-images.githubusercontent.com/92332710/194031505-17328781-f5fd-4bb3-93cb-b2e671d0d13d.png">

**Comment by katspaugh** [comment]
IMHO pins should continue being global (since the ids themselves are global), but we should just filter out the apps that aren't enabled on that chain.

**Comment by katspaugh** [comment]
Actually, pinned apps disappear when switching to another chain and back. 🐞

**Comment by francovenica** [comment]
LGTM.
Apps keeps pinned after switching networks and back
With pinned apps being global, allows them to be shared between networks, which is nice.

![apps pinned](https://user-images.githubusercontent.com/4503659/194986479-bf5e8ad4-ebbc-41ea-8261-2f021d6f4c93.gif)

**Comment by clemoon** [comment]
@katspaugh after checking-in with Lila, we would like that the interface keeps pinned application only specific to the network that it was pinned from. E.g if pinned on one network and network switch takes place, remove the pin. From a user point of view, it makes more sense than the current implementation. Can we reopen this issue please?

**Comment by JagoFigueroa** [comment]
All bueno, thanks! Very nice to have everything on the same key too 👍
