### ISSUE TITLE
Safe upgrade - Error message too dark for the dark theme

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#827]
## Bug description
When trying to update a safe 1.0.0 an error shows up (the console shows that safe 1.0.0) are not compatible
This error message is has the font-color black even in for the dark theme

## Environment
 - Browser: Chrome
 - Wallet: any
 - Chain: any

## Steps to reproduce
 1. Try to update a safe 1.0.0

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/194096910-13b844a0-8fa7-4c4f-894d-797f342a7410.png)

**Comment by francovenica** [comment]
Noticed that other font colors are affected for some reason
![image](https://user-images.githubusercontent.com/4503659/194097176-2a32b648-c8ef-453d-a6ac-c504b8d27b40.png)

**Comment by iamacook** [comment]
Does this all look the same after a hard reload? All seems good on my end.

![image](https://user-images.githubusercontent.com/20442784/194097608-d534c811-db98-4e01-a3eb-99b290b674c1.png)

**Comment by francovenica** [comment]
Tried in FF and it works fine there. The issue was originally reported in Chrome
![image](https://user-images.githubusercontent.com/4503659/194534005-3f79bed4-273c-411b-8998-1bf4b10fd286.png)

**Comment by DiogoSoaress** [comment]
Can we close the issue @francovenica ?
