### ISSUE TITLE
Dashboard safe apps - Claim app must be the first one in the list

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#829]
## Bug description
The $Safe claimin app is not the first one in the list. This is for ETH mainnet and is how it is currenlty working in safe-react prod

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet
 - Env: https://web-core.pages.dev/eth:0xAAb5A43af6599845f2D97EC3c4E23b23528bAaB1/home

## Steps to reproduce
 1. Go to any safe
 2. Check the dashboard > Apps widget

## Expected result
The claiming app should be always the first one, regardless of amount of visits or if it is pinned or not.

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/194198002-99a5b260-0b7a-4948-bfb0-d70965e80912.png)

**Comment by usame-algan** [comment]
Should we use a tag for this as opposed to hardcoding it via the app id?

**Comment by katspaugh** [comment]
I'd say so. It could be also used in the header widget.
