### ISSUE TITLE
Dashboard Safe Apps - The pin/unpin icon is missing

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#830]
## Bug description
The safe apps in the Dashboard should show the Pin/unpin icon. That icon is missing completely

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet
 - Env: https://web-core.pages.dev/eth:0xAAb5A43af6599845f2D97EC3c4E23b23528bAaB1/home

## Steps to reproduce
 1. Go to any safe and open the dashboard
 2. Check the Safe App widget

## Expected result
The apps should show the pin/unpin icon

## Obtained result
The icon is missing

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/194198329-e5584d63-dd8a-420b-b456-bc464c1d22d6.png)

**Comment by katspaugh** [comment]
I think it's good that it's missing there because we had a bug that the apps randomly reorder on bookmark.
@dasanra WDYT?

**Comment by DiogoSoaress** [comment]
Closing in favor of #831
