### ISSUE TITLE
[Safe Apps] Missing Safe App icon in the modal header

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#838]
## Bug description

<img width="636" alt="194274513-5d484717-d843-43ab-be32-ce60bbb24743" src="https://user-images.githubusercontent.com/381895/194284380-20374b14-0616-4461-82f7-8b8d6524d523.png">

## Expected result
The ENS icon should be visible.

**Comment by iamacook** [comment]
It looks like this may be app-specific:

![image](https://user-images.githubusercontent.com/20442784/194282006-d618f3b1-358f-44cb-a199-2d47ee0ddb12.png)

**Comment by usame-algan** [comment]
We could use the `ImageFallback` component here in case it can't be loaded.
