### ISSUE TITLE
Robots.tx – block indexing of Safe-specific pages

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#844]
Only allow /welcome and Safe Apps share pages.

**Comment by mikhailxyz** [comment]
Is this a technical limitation? I believe it's a handy feature to google your Safe address and have the Safe app in the results instead of etherscan

**Comment by katspaugh** [comment]
Hmm, maybe you're right. I'll close this. If marketing requests it, we'll adjust the robots.
