### ISSUE TITLE
[Transaction list] Paginated transactions are missing space

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#846]
## Bug description

The spacing is wrong when loading the next page of transactions.

## Steps to reproduce
 1. Go to the transaction history
 2. Scroll down to load the next page of transactions
 3. Observe missing space between transactions

## Expected result

All transactions in the list have the same spacing to each other

## Obtained result

Transactions inbetween pages are missing spacing

## Screenshots

<img width="1268" alt="Screenshot 2022-10-06 at 12 45 01" src="https://user-images.githubusercontent.com/5880855/194293843-54f93eae-0412-42cc-b406-43d92452eb6e.png">

**Comment by francovenica** [comment]
LGTM
