### ISSUE TITLE
[L2- Arbitrum] Gas price  is bigger than in safe-react 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#855]
## Bug description
Gas price  is bigger than in safe-react 

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain:Arbitrum prod

## Steps to reproduce
 1. Go to https://web-core.pages.dev/arb1:0x861099a9FD94b03471a1002efCa662c3ECAdB10C/transactions/tx?id=multisig_0x861099a9FD94b03471a1002efCa662c3ECAdB10C_0x40b0ca2628b39d7f46d67575f4f3d733e9891062119f00994244581903110407
 2. Click execute tx on web-core and safe-react -> check gas estimation
Current result:
web-core : gas price = 1.7
safe-react : gas price = 0.1

## Expected result
Make sure that the price is proper on web-core

**Comment by francovenica** [comment]
LGTM
For networks EIP1559 the estimation is 1.5 (also for goerli that is not eip1559, but is a test network so not an issue)
For other networks the estimation is 0.1 or lower; Optimism = 0.001 and Aurora = 0.07, but in both cases tx can be executed just fine, so the default estimation is correct

It was checked with how prod works currently
