### ISSUE TITLE
[Epic] Default token lists

### ISSUE THREAD

**Issue by schmanu** [safe-global/web-core#865]
## Overview
We want to build a solution which has a strong **security by default** to protect inexperienced users.

### Default token lists which contain well-known, verified token addresses.
- By default we will only display a list of curated default tokens.
- Transparent curation process
  - For curating these we will use official token lists where possible (e.g. Polygon, Optimism)
  - And selected sources for networks without official lists
- The UI offers a way to toggle between showing all tokens / only default tokens
- The selected list will have an effect on the total balance / displayed tokens in our UI. It will not have an effect on the transaction history.

## Issues / Requirements
Web
- [ ] Toggle between default and all tokens #1549 

Infra
- [ ] Sync default token lists: https://github.com/safe-global/safe-transaction-service/issues/1281

Mobile
- [ ] Toggle between default and all tokens https://github.com/safe-global/safe-ios/issues/2885

## Designs
https://www.figma.com/file/ZKWJPH1MjJIyUDTHYD3kk8/Default-token-lists?node-id=2%3A26&t=bKTHJUzmMmfe6jLa-0

## Links
[Problem Statement](https://github.com/safe-global/safe-pm/issues/86)

**Comment by francovenica** [comment]
Questions:
Apps seems to not take this hiding of tokens in account, for example the "Drain" app will still see all the tokens you hide by setting it to "Default tokens". Is this expected?

Issue:
For spending limit an "undefined" is shown in the table if you already have that token set as an allowance. I tried the same with the manual hiding of tokens and there even if the token is hidden we still show the token name and symbol
In this snapshot, the USDC token is hidden manually, still shows name and symbol:
![image](https://user-images.githubusercontent.com/4503659/216383713-dcc9400e-77c3-4547-aded-77e4578e9cdd.png)

**Comment by schmanu** [comment]
I changed the behavior for safe apps: It only returns the default tokens.

I created a PR for the found issue with spending limits as this already existed prior to this PR:
#1646

**Comment by liliya-soroka** [comment]
Verified.
The GA will be implemented separately in diff PR
