### ISSUE TITLE
[Mobile] Wallet connection – use WalletConnect instead of onboard

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#871]
## Bug description
Most wallets we offer in the onboard popup don't work on mobile, so it's better to just open the WalletConnect popup right away.

**Comment by iamacook** [comment]
[This](https://docs.blocknative.com/onboard/injected-wallets#excluding-wallets) is how you disable wallets per device.

**Comment by katspaugh** [comment]
@francovenica @liliiaorlenko @JagoFigueroa does any of you have an Android phone to test this?

**Comment by francovenica** [comment]
In android it will show a modal of WC to connect but won't give options in the same way iPhone does. Still, if you have MM install it opens it and tries to connect. If you don't have any wallet installed it will open it in a browser basically doing nothing.
That being is a given that anybody who wants to use the safe in a web browser will need some wallet installed in his/her phone.

Is not pretty, but I don't think we can do much about it on our side
![image](https://user-images.githubusercontent.com/4503659/195185497-5ca0cc09-5905-4244-9f76-1413bcbe18b0.png)

**Comment by katspaugh** [comment]
I see, thanks @francovenica. Sounds good enough to me. 👍
