### ISSUE TITLE
[Tx execution]Tx most likely fail message is missed in some cases

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#874]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to https://max-fee.web-core.pages.dev/gno:0x9DF58F04F3e914ED8D972146401C85313A53FecA/transactions/queue
 2. try to execute the tx with the nonce =40
Current result: "Tx most likely fail" message should be displayed if we can detect it without the simulation 
## Expected result
<img width="577" alt="image" src="https://user-images.githubusercontent.com/338622/194888420-7c86c377-a9a4-4761-87c3-5e9310476dce.png">

**Comment by mahdit8** [comment]
@liliya-soroka Btw I'm getting this message lots of places even with custom gas fee. Is this another issue or related?
<img width="608" alt="Screen Shot 2023-03-22 at 18 16 28" src="https://user-images.githubusercontent.com/75958335/226877577-bde86e11-92df-4f33-9d1c-71f791671e16.png">
