### ISSUE TITLE
Replacing the contract interaction feature with the transaction builder

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/web-core#876]
## Overview

The transaction builder has overtaken the contract interaction feature in UX and feature-depth with all its latest updates and since we do not want to maintain both in the future, it is time to sunset the contract interaction feature. 

## Requirements

- [x] link button to the transaction builder Safe App instead of opening the contract interaction module 

## Designs

- [x] design: replace <> symbol with transaction builder logo @liliiaorlenko wdyt?

**Comment by francovenica** [comment]
LGTM
