### ISSUE TITLE
Too much info in the error notification

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#884]
## Bug description
Too much info in the error notification.

<img width="388" alt="Screenshot 2022-10-11 at 17 41 16" src="https://user-images.githubusercontent.com/381895/195137514-f8502d8c-c0cf-4b72-9161-dde7ffa4fdeb.png">

## Suggestion
Hide the JSON trace under a collapsible "Details" section, just like the inline `<ErrorMessage>` does.

If it's an Ethers.js error, it has a `reason` field which should be still displayed uncollapsed, but the initial letter needs to be capitalized.

So in the end it should look like this:

```
ℹ️ Your transaction was unsuccessful.
   User rejected the transaction.

   View transaction
```

**Comment by francovenica** [comment]
Good change. Looks good to me
