### ISSUE TITLE
Mobile viewport - Being able to scroll horizontally in tables is not intuitive

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#888]
## Bug description
Tables can be scrolled horizontally to see all the columns, but is not obvious, there is nothing that tells the user he can do that, so it looks broken

## Environment
 - Browser: Chrome
 - Env: this safe has assets and spending limits created: https://web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/settings/spending-limits

## Steps to reproduce
 1. Go to This safe

## Expected result
There should be a visible scroll bar or something that tells the user that horizontal scrolling is possible

## Obtained result
Without any indication that horizontal scrolling is possible in tables, it looks broken

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/195241802-517d4869-498d-427c-8912-e2c86c05504c.png)
![image](https://user-images.githubusercontent.com/4503659/195241936-1b3c2559-8438-4205-bc5b-22824e7b2e0e.png)

**Comment by katspaugh** [comment]
In Balances, I suggest we hide the Send button on mobile. It's not essential to viewing your balances.

**Comment by katspaugh** [comment]
Actions on mobile should be always displayed on mobile. On desktop it's on hover.

**Comment by francovenica** [comment]
Looks good, the buttons were removed from AB and in assets. The buttons in spending limit and Owners only show up if the person logged in is actually an owner.

**Comment by iamacook** [comment]
> Looks good, the buttons were removed from AB and in assets. The buttons in spending limit and Owners only show up if the person logged in is actually an owner.

This is as agreed due to resolution restrictions.
