### ISSUE TITLE
[Android] - Uploading a csv in the AB errors out and displays [Object object]

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#889]
## Bug description
Trying to upload a csv in the Address book doesn't work.
Tested it in Android

## Environment
 - Browser: Chrome

## Steps to reproduce
 1. Need to have downloaded a csv in your phone already. Export csv feature works fine, you can use that
 2. Try to upload the csv

## Expected result
The AB gets updated

## Obtained result
An error is displayed.

## Screenshots
![](https://user-images.githubusercontent.com/4503659/196483026-f1934dfc-91ba-45e1-b47f-6884d6db0487.png)

**Comment by katspaugh** [comment]
Relevant Sentry error: https://sentry.io/organizations/gnosis/issues/3664091353/?project=6769196&query=is%3Aunresolved&statsPeriod=24h

**Comment by francovenica** [comment]
So, the error is fine, the page doesn't crash anymore, but the reported issue of not being able to upload a csv at all persist; even if the .csv is valid the modal will show you an error that what you uploaded is not a csv

**Comment by katspaugh** [comment]
OK, I'll merge that PR but will keep this issue open to fix that.

**Comment by DiogoSoaress** [comment]
Hmmmm I was just able to upload a AB .csv using Chrome on Android. Can we align on this Franco?

**Comment by francovenica** [comment]
It seems that the error is just for me, we tried in 2 more androids and it worked fine.
It seems to much effort to try to fix something so nish. If people start to complain more about it we can revisit it.
![image](https://user-images.githubusercontent.com/4503659/197240273-4cf0f9c1-a0d7-4d36-a252-a79b2360f3c0.png)
