### ISSUE TITLE
[Mobile] - Change to current network not intuitive

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#897]
## Bug description
(technically not a bug, more of a suggestion)
In desktop, if you are in the wrong network we have a big button in the topbar that asks you to switch, but in mobile is only if you open the Connect display that you see the button, so is pretty hidden
This is an issue specially with the "New Transaction" button that only says "wrong network"

Suggestion: Make that New Transaction button to also have the feature of switching to the expected network.

![image](https://user-images.githubusercontent.com/4503659/195363549-684d45dc-05c6-44d5-89a5-f14fb865e49d.png)
![image](https://user-images.githubusercontent.com/4503659/195363621-1d93e2ba-caa4-4430-b4ca-740010ed04f5.png)
![image](https://user-images.githubusercontent.com/4503659/195363688-a5774fb3-8b72-4d1b-b74a-2d7ab444c4a3.png)

**Comment by katspaugh** [comment]
I suggest we change the "Wrong wallet chain" button in the sidebar with "Switch to X".

**Comment by DiogoSoaress** [comment]
> I suggest we replace the "Wrong wallet chain" button in the sidebar with "Switch to X".

In both views? Or just in mobile

**Comment by francovenica** [comment]
LGTM
