### ISSUE TITLE
Gnosis old logo in the "safe created" tx

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#902]
## Bug description
The very first tx of any safe is its creation. This tx shows the old gnosis logo

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to this safe https://web-core.pages.dev/eth:0xAAb5A43af6599845f2D97EC3c4E23b23528bAaB1/transactions/history

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/195477562-66aaca9e-ea37-4c3f-802c-92bf1a28db39.png)

**Comment by katspaugh** [comment]
Requested an update from backend.
