### ISSUE TITLE
Address Book - Create entry form does not validate after translating ENS

### ISSUE THREAD

**Issue by DiogoSoaress** [safe-global/web-core#909]
## Bug description
When adding an entry to the Address Book, the form is invalid right after translating the ENS.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Go to Address Book
 2. Click to create an entry
 3. Insert `safe20.eth` in the address
 4. Observe the form is invalid at first

## Expected result
The form is valid after translating the ENS name

The E2E test 'should add an entry' works with a ENS name

## Obtained result
The form shows an error and "Save" button is disabled

## Screenshots
<img width="567" alt="Screenshot 2022-10-14 at 11 21 00" src="https://user-images.githubusercontent.com/32431609/195819906-bd7e5a03-687b-4cac-b22b-6309451b04b3.png">

**Comment by francovenica** [comment]
Good catch. 
LGTM, had to register a new ens name in goerli "francotest.eth"
