### ISSUE TITLE
[Smart contract wallet] - Executing a tx still shows the "Execute tx" checkbox

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#930]
## Bug description
NOTE: This issue was originally found in PR #885, but I think is an unrelated issue to that PR

Once a tx is fully sing and can only be executed the "Execute tx" checkbox in the last step should not be present, but it is present if the one signign is another safe 

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Have SafeA be owner of SafeB open them in different tabs
 2. SafeB needs a 1/n owners. Click connect with WC and copy the link
 3. In SafeA open the WC app and paste it. Also in SafeA tab connect with an owner of SafeA
 4. In safeB queue a tx, the tx should be 1/n confirmations needed so now it can only be executed
 5. Try to execute the tx using SafeA as owner

## Expected result
The execute tx checkbox is not present
It should look like this:
![image](https://user-images.githubusercontent.com/4503659/196451473-c1628ad8-3213-44dd-8719-cd54d906f0c7.png)

## Obtained result
The checkbox is there
![image](https://user-images.githubusercontent.com/4503659/196451575-da7f33c9-b853-469f-b347-4c68a463bfcd.png)

**Comment by usame-algan** [comment]
I followed the steps but wasn't able to reproduce the issue.

In step 4 I create a new tx in SafeB, uncheck the execute checkbox and submit. This creates an `approveHash` tx in SafeA. The queued transaction in SafeB shows 0 of 1 confirmations which is correct. After `approveHash` is executed in SafeA, the queued tx in SafeB picks it up and shows 1 of 1 confirmations. Trying to execute it then doesn't display the checkbox.
