### ISSUE TITLE
[Mobile pairing] Mobile pairing icons is missing in the header

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#934]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to https://safe-web-core.staging.5afe.dev/welcome
 2. connect your owner using r mobile pairing
Current result: The icon is missing
## Expected result
Make sure that the mobile pairing and WC are displayed in the header if it was used
## Screenshots
<img width="254" alt="image" src="https://user-images.githubusercontent.com/338622/196465306-cf2ea899-444b-4854-8c86-58f68c296d13.png">

**Comment by iamacook** [comment]
I think this is happening because of the CSS vars. It needs to be rendered as an `svg`, not `img`.

**Comment by francovenica** [comment]
LGTM:
![image](https://user-images.githubusercontent.com/4503659/197286812-bd21ebf1-2fe5-40c1-8fa0-da6f6ccc97c6.png)
![image](https://user-images.githubusercontent.com/4503659/197286819-c1c04740-7ed0-427a-8f58-d22341a95d08.png)
