### ISSUE TITLE
[Safe Creation] A/B test the new design

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#968]
## What is the feature about
We need to analyze how the new design performs against the old one.

The most correct way to do it is to run both versions in parallel and measure the drop-off rate in both.

## The list of requirements

* The new Safe creation should be on a new URL (e.g. `/new-safe/create`) and its components in a corresponding new folder
* The old Safe creation should stay on the old URL
* Add a new A/B hook that would flip a coin and save the variant to the localStorage
* If a user with the B coin goes to the Safe creation, redirect them to `/new-safe/create`
* Add the variant from the localStorage to all GTM events

## The A/B hook
The hook should be generic and work for other A/B tets in the future.

So it should be something like this:

```
const useABTest = (name: string): boolean => {
  const [isB, setB] = useLocalStorage<boolean>(`AB__${name}`, false)
  
  useEffect(() => {
    // Flip the coin if the variant hasn't been determined yet
    setB((prev) => prev ?? Math.random() > 0.5)
  }, [setB])
  
  return isB
}
```

## Links
Epic: https://github.com/safe-global/web-core/issues/864

**Comment by francovenica** [comment]
Is 50/50 alright.
LGTM
