### ISSUE TITLE
[Safe Apps Analysis] 08. Apps most used via WalletConnect (Frontend)

### ISSUE THREAD

**Issue by yagopv** [safe-global/web-core#987]
# What is solves
We are generating a report for the most used apps via wallet connect

# Links
[Notion. Most used apps via WalletConnect](https://www.notion.so/gnosis-safe/Apps-most-used-via-WalletConnect-f4b4c3e9cf9f44359c7ec48c2485251d)

**Comment by yagopv** [comment]
We have an issue here as we need to track events happening inside the Safe App:

We can:

1) Install Tag manager in Safe Apps (Wallet connect) and start tracking inside the app
2) Send some king of event through the communicator and capture it in the web-core in order to trigger tracking there (preferred imo)

Anyway, it can possible means we need to add this information in the the consents for Safe Apps?

**Comment by yagopv** [comment]
We need to agree as well in what is the definition for "most used" as we can consider it connections or initiated transactions.

Anyway in order to track this we need to implement one of the above.

**Comment by clemoon** [comment]
I couldn't see this event tracked inside the GA dashboard

**Comment by liliya-soroka** [comment]
No connection event if the app was disconnected and another one was connected:
1. connect to the app 1 via WC connect
2. refresh the page
3. disconnect
4. connect to the app 2
Current result: there is no connection event for the app 2.

5. try to creat a tx
Current result: There is an event about tx creation from the app 2

**Comment by liliya-soroka** [comment]
Verified, works
