### ISSUE TITLE
[Mobile pairing] Switch network to the correct one from web doesn't work

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#990]
## Bug description
Switch network to the correct one from web doesn't work
## Environment
 - Browser: Chrome
 - Wallet: mobile pairing
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. pair mobile app with the web app
2. change the network on the connection details on mobile
3.  switch network button appears on the web
4. click switch network 
Current result: 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/338622/198265323-264eadb1-c205-4cf0-a551-e25450c83fe0.png">

## Expected result
On safe-react switch connection network from the web to mobile, using "switch network" button on the web is working

## Screenshots
https://drive.google.com/file/d/1ElnWQ7t3RE2yRsIfDB47km6PeT-wNzqm/view?usp=sharing

**Comment by katspaugh** [comment]
safe-react was [handling the pairing module specially](https://github.com/safe-global/safe-react/blob/0d09d940100ac2f0e37b371a6273b51cb490f081/src/logic/wallets/utils/network.ts#L21-L35), whereas web-core just calls `onboard.switchNetwork`.
